### ISSUE TITLE
Assembly instructions for standby altimeter do not include directions to glue Spacers to the Zero Detect Pointer

### ISSUE THREAD

**Issue by Krikeee** [jrsteensen/OpenHornet#1000]
### Discord Username

Krikeee

### Bug Summary

The PDF document for the assembly of the Standby Altimeter does not indicate the 2 spacers (19 and 20) should be glued to the Zero Detection disk (5). Not gluing them would prevent the disk from spinning

### Expected Results

A general note or instruction indicating the parts should be glued together for proper functionality

### Actual Results

Zero Detection disk will not rotate without it being attached to the spacers

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/91638076/f8e85b02-ad62-4eb5-88e0-d399dee0f1cc)

### Applicable Part Numbers

OH2A7A1-112, OH2A7A1-111, OH2A7A1-110

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with 7f4eef5c3328e6ec5bac326899109be38b2794a1
