### ISSUE TITLE
[Bug]: RAD ALT ASSEM issue 

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#1001]
### Discord Username

Ben-F111

### Bug Summary

There maybe an issue with the 2 screws that mount the RAD ALT Stepper mount to the Bezel, these look not accessible when -14 and -15 are pre screwed together

### Expected Results

OH5A2A4-15 - RALT STEPPER STANDOFF - Blocks the 2 x PHS that bolt OH5A2A4-14 - RALT STEPPER MOUNT to the OH5A2A4-14 - RALT STEPPER MOUNT

### Actual Results

remove or move the 2 extra case screws in OH5A2A4-15 - RALT STEPPER STANDOFF and provide a void for the PHS 

see pics below 

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/67782885/03f65bdb-9c55-4109-a977-3980754caf2f)
![image](https://github.com/jrsteensen/OpenHornet/assets/67782885/00f4b95f-86f2-44ed-a23a-48e8e61bbdc9)

### Applicable Part Numbers

OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with 24d533ec21e292addfbba5c7ac95d6ee7b048a5a
