### ISSUE TITLE
[Bug]: Shore Bulkhead Panel: wrong shape for power cable

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1002]
### Discord Username

Higgins

### Bug Summary

The cutout for the power cable extension doesn't fit. Cable has edges with r=0.118 in, cutout is r=0.197 in.

### Expected Results

The cutout needs to have a slightly different shape.

### Actual Results

The power cord doesn't fit the bulkhead.

### Screenshots/Images/Files

<img width="536" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/ded2b054-3b41-43e9-bd5b-33057271dd52">

### Applicable Part Numbers

OHC0013-40

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with ca550d1d7c540c3b80bc04e0d3dc1cd07a00afbe
