### ISSUE TITLE
SVG File for Standby Alt looks to be missing the 3 x "0" s on the face [Bug]: 

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#1007]
### Discord Username

Ben-F111

### Bug Summary

THe Downloaded SVG file for the DIal Face for the Standby looks to be missing the 3 x "0"s

![image](https://github.com/jrsteensen/OpenHornet/assets/67782885/223629ec-406a-4fd3-9d17-3fbe0b1e4f71)

### Expected Results

The face should have 3 "0"s next to the 2 cut outs 
![image](https://github.com/jrsteensen/OpenHornet/assets/67782885/cea9f203-8eb4-45fa-aada-fded7e0edd0b)
### Actual Results

File needs an update 

### Screenshots/Images/Files
![image](https://github.com/jrsteensen/OpenHornet/assets/67782885/372f76db-b7f5-47e0-8ad6-2b7ef382c929)

### Applicable Part Numbers

RMRK_.063_OH2A7A1-204_ALTIMETER DIAL FACE_-_V13

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
For some reason, the tool in fusion wont generate those three zeros. Odd. May have to smack them in with a vector art program.

**Comment by Ben-F111** [comment]
Cheers thanks.

**Comment by kbastronomics** [comment]
load the file into your software,  Lightburn in my case and it's fine
only the preview is in error

![Body1](https://github.com/jrsteensen/OpenHornet/assets/19305697/42c21b77-7198-4584-810e-7ec6f7aed7fc)

once loaded into lightburn
![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/be90dfde-3393-4537-9ed4-f9b307855163)

**Comment by Ben-F111** [comment]
Got the same view on Visio without the O’s

**Comment by kbastronomics** [comment]
its the way visio and the preview render 

this is from visio,   I ungrouped and move the layer

![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/4bf5a00f-d197-4685-b9e1-4d9c93f15b52)

**Comment by jrsteensen** [comment]
Its there, just not colored. Limitation of software visibility until moved into program. Still manufacturable, just not ideal, but no ability to fix at this time.
