### ISSUE TITLE
Include lasering jig in release 

### ISSUE THREAD

**Issue by CorgiStyle** [jrsteensen/OpenHornet#1009]
### Discord Username

CorgiStyle

### Feature/Enhancement Summary

Include the mentioned lasering jig for the UFC/AP/DDI buttons in the release. 

### Justification

Jigs like this enhances the chanse of someone as clumsy as me to actually achive a good result. 

### Applicable Part Numbers

OH1A8A1

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

**Comment by jrsteensen** [comment]
Closed in 48bffcc03a084babf734c8cdf9dc70b5705e1d81
