### ISSUE TITLE
[BUG]: OH2A2A1-1 - ASSY, LEFT LIP MODULE_-_v5.pdf: Nr. 5 missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1010]
### Discord Username

Higgins

### Feature/Enhancement Summary

Nr. 5 in the drawings is missing.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/f6e5c45f-bf64-437e-83ad-3afadd7d7bc6)

### Justification

It helps builders to easily recognize the proper screws.

### Applicable Part Numbers

OH2A2A1-1 - ASSY, LEFT LIP MODULE_-_v5.pdf

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

**Comment by jrsteensen** [comment]
Update as noted. Drawing change only - no change to form, fit or function.

**Comment by jrsteensen** [comment]
Closed with d5fc02c1033c68180c67b0ee55a0fd810586db2b
