### ISSUE TITLE
[Bug]: HID Bus Master rev 3: Mounting holes too large

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1011]
### Discord Username

Higgins

### Bug Summary

The mounting holes of the HID Bus master rev3 are too large. Instead of D=0.12 in they are D=0.167.

### Expected Results

The holes should be D=0.12 in.

### Actual Results

The mounting holes are too large.

### Applicable Part Numbers

ABSIS003-10 ABSIS_HID BUS MASTER

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Top Level Assembly (TLA)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed in 83dbed5b29b3bed196deb757e5683c7ad522b7a1
