### ISSUE TITLE
[Bug]: Manufacturing Files - Mistakes in the name of some Acrylic plates

### ISSUE THREAD

**Issue by Thibaud-54** [jrsteensen/OpenHornet#1013]
### Discord Username

Thib-O #5205

### Bug Summary

Here is some plates 0.25 thick (according to the file name) which actually could be 0.188 as usual. Double checked with Fusion for OH5A6A1-11 INTR LT LIGHTPLATE. I made a Excel table which summarize panel with 0.25 thickness information in the file name. It mainly concerns the Right console.

![image](https://github.com/jrsteensen/OpenHornet/assets/73742549/547b4f75-5565-4f44-94a3-9c55887d43c0)

### Expected Results

Double check/Correct the thickness in the name of the files. 

### Actual Results

The thickness in the file name does not correspond to the real thickness in Fusion.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/73742549/4d1031bf-d709-4593-8d92-49e3bfb64201)

### Applicable Part Numbers

OH5 - Light plates panels

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by Arribe** [comment]
<img width="1099" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/47125808/86f016cb-c485-4d4e-b0a6-7d01cee4604b">

**Comment by Arribe** [comment]
In progress

**Comment by jrsteensen** [comment]
Closed with #1014
