### ISSUE TITLE
[Bug]: Drawing: OH3A3-100 - ASSY, STICK YOKE_-_v17.pdf missing parts

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#1018]
### Discord Username

Arribe

### Bug Summary

Drawing doesn't list 608-2RS bearings and 92125A192 FHCS, M4 x 0.7 mm, 12 mm Long as a parts, nor does it show it on sheet 10 or 11 where they would be installed.

### Expected Results

The drawing should show the bearings and screws, and list them as parts of the OH3A3-119 assembly.

### Actual Results

If one were to build the stick according to the drawings they wouldn't know to buy the 608-2RS bearings and 92125A192 FHCS, and can overlook where they are installed.

### Screenshots/Images/Files

<img width="845" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/47125808/5539061f-d70a-4f92-a5d0-795201dd4559">

### Applicable Part Numbers

OH3A3-100 - ASSY, STICK YOKE

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Flight Stick

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
FN 1 should have its own drawing. Will update.

**Comment by jrsteensen** [comment]
Closed with 9b48ed09b8e85744a749f0d2b87c1807d7ed7207
