### ISSUE TITLE
[Obsolescence]: TLVH4200 LED Red for landing gear assembly

### ISSUE THREAD

**Issue by DenzilLee** [jrsteensen/OpenHornet#1020]
### Discord Username

DenzilLee

### Issue Summary

Red Led TLVH4200 is an obsolete part. #23 in the PDF screenshot

### Applicable COTS Part Number

TLVH4200

### Applicable OH Part Numbers

OH4A2A1-1

### Screenshots/Images/Files

![Screenshot (156)](https://github.com/jrsteensen/OpenHornet/assets/156961886/11ab9742-fcb3-41c6-98ba-62c08a90d7e9)

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Left Console (LCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.

**Comment by jrsteensen** [comment]
Will replace with [HLMP-1321](https://www.digikey.com/en/products/detail/broadcom-limited/HLMP-1321/637558)

**Comment by jrsteensen** [comment]
No change to form/fit/function. Drop in replacement.

Closed with d4323e292d2a7a41cf9475cbe7a06dd0b00ae403
