### ISSUE TITLE
[Bug]: LH/RH Throttle Base Plate incorrectly tagged as Stainless, Release folder not reflecting flat parts material and thickness in file names

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#1024]
### Discord Username

smgvbest (aka Sandra)

### Bug Summary

The Throttle Base plates are both taged as Stainless Steel instead of Aluminum.
Step files in the releases folder do not show the material nor dimensions for any of the 6 plates in the throttle

### Expected Results

These should reflect the actual material to be used and release files should follow the published standard showing the material and thickness in the output files.

### Actual Results

with this information being incorrect users may pay more for parts

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/4a02f2ac-3dc0-4d6c-8ce0-1aa9996f6ca9)
![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/b31f3dac-3a81-4903-ac4a-0fbdae2f9b24)

### Applicable Part Numbers

OH4A9-201 OH4A9-203 OH4A9-102 OH4A9-105 OH4A9-10 OH4A9-11

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Throttle

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Already fixed in June of last year.
