### ISSUE TITLE
[Bug]: Incorrect labeling on ABSIS_ATX_PSU_BREAKOUT in system interconnect PDF

### ISSUE THREAD

**Issue by 5k33tz** [jrsteensen/OpenHornet#1027]
### Discord Username

5k33tz

### Bug Summary

Mismatch between interconnect diagram and silkscreen on PCB. J28, J29, and J30 Incorrectly labeled for ABSIS_ATX_PSU_BREAKOUT on interconnect diagram pdf. 

The interconnect shows the following:
J28 - EXT_5V_IN (unused)
J29 - XDCR_AMP_PWR
J30 - EXT_12V_IN (unused)

Silkscreen for PCB in KiCad has the following:
J28 - EXT_12V_IN
J29 - EXT_5V_IN
J30 - BUTTKICKER IN

Correct labeling on interconnect PDF should read as:
J28 - EXT_12V_IN (unused)
J29 - EXT_5V_IN (unused)
J30 - XDCR_AMP_PWR 

### Expected Results

Correct labeling on interconnect PDF should read as:
J28 - EXT_12V_IN (unused)
J29 - EXT_5V_IN (unused)
J30 - XDCR_AMP_PWR 

### Actual Results

The interconnect shows the following:
J28 - EXT_5V_IN (unused)
J29 - XDCR_AMP_PWR
J30 - EXT_12V_IN (unused)

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/13365308/bfaf243d-1308-4b8d-aca5-1740b0dec079)
![image](https://github.com/jrsteensen/OpenHornet/assets/13365308/ba432b05-d7b2-4431-8589-e60ebc5b5098)

### Applicable Part Numbers

OH-INTERCONNECT - OPENHORNET SYSTEM INTERCONNECT_-_v9.pdf

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with 067946cc90d6b100ca1e01f2cb375c3013cb02bc
