### ISSUE TITLE
[Bug]: Missing Manufacturing/Drawing Files for OH3A2-34 & OH3A2-33 Seat  Pan/Back Cushions

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#1035]
### Discord Username

Lazarus21

### Bug Summary

No manufacturing/drawing files were generated for the Seat Pan and Back Cushions

### Expected Results

There needs to be a drawing detailing the dimensions and material requirements for the cushions

### Actual Results

No files were generated

### Applicable Part Numbers

OH3A2-34, OH3A2-33

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Center Tub (CT)

### Built to print?

- [ ] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
This is currently addressed as a note on the seat drawing. An enhancement of detailing the cusions out will be done in #715. Closing this as a duplicate to that issue.
