### ISSUE TITLE
[Bug]: Radar Altimeter Servo susceptible to burning out due to over voltage.

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#1036]
### Discord Username

Sandra

### Bug Summary

The Micro servo used to the control the FLAG in the Radar Altimeter is a 2.8-4.2 volt (see spec below)
driving this servo at 5V can cause it to burn out.

Specifications:
Voltage: 2.8V-4.2V 
Speed:0.07s / 60 ° 2.8V and 0.05s/60 ° 4.2V 
Torque:0.05Kg/2.5V and 0.075Kg/4.2V
Size: 16.3mm x 13.5mm x 6.3mm
Weight: 1.9g
Plug: micro JST 1.00 pitch

### Expected Results

The servo should be driven within its specified range of 2.8.4,2 volts

### Actual Results

in talking with Ben-F111 he has reported that he's blown multiple servos due to over voltage.   
We should like the voltage going to the servo.   this is both at the +V pin and the PWM pin.  

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/47553af5-2345-40e9-8348-567b0848e961)

### Applicable Part Numbers

HK-5320 - SERVO, DIGITAL, ULTRA-MICRO, 1.7g

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
@kbastronomics Do we have a PN for the PCB side micro JST connector?

A quick look is that there are 1mm spacing JST connectors, but micro JST is 1.25mm spacing. So need a little clarification.

Updated the circuit to the following:
![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/e2fb9fe3-68ed-4279-a5cf-d8744e0bf1ae)

**Comment by jrsteensen** [comment]
Looks like a Micro JST with 1.25mm spacing.

![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/b0e5a5d4-f172-4789-a326-81540c96c8d9)

**Comment by jrsteensen** [comment]
Need to flip pinout; didn't realize pinout in datasheet was viewed from below the PCB.
