### ISSUE TITLE
OH1A1A1-1 missing from OH1A1-1 master cad 

### ISSUE THREAD

**Issue by aesellars** [jrsteensen/OpenHornet#1039]
### Discord Username

aesellars#0166

### Bug Summary

The structure drawing file for the rigid structure is missing from the master cad file on fusion 360 

### Expected Results

The other car files have an assembly structure car file for just the rigid frame, for construction purposes. This file should exist for the upper instrument panel.

### Actual Results

This drawing is missing from the upper instrument panel 

### Applicable Part Numbers

OH1A1-1

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
There is no separate structure assembly for the UIP. Parts are included in the main UIP assembly and due to simplicity of the UIP structure, will not be broken out to a separate structure drawing/assembly.
