### ISSUE TITLE
HOTAS Hat Switch Breakout PCB 

### ISSUE THREAD

**Issue by DenzilLee** [jrsteensen/OpenHornet#1045]
### Discord Username

DenzilLee

### Bug Summary

The PCB has an added circle on the cut later that doesn't need to be there and crosses the printed circuit.

### Expected Results

Added element on the cut layer needs to be removed to avoid being rejected by JLCPCB. 
![unnamed](https://github.com/jrsteensen/OpenHornet/assets/156961886/51e4e8cb-43dc-4850-8be0-d0ee359a2ad6)

### Actual Results

N/A

### Screenshots/Images/Files

![unnamed](https://github.com/jrsteensen/OpenHornet/assets/156961886/21db1c87-570b-4d17-998d-c8603edff885)

### Applicable Part Numbers

OH4A9-123

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Throttle

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Is fixed in commit e970897289d2f91238e2f0d1c322f1c89b9e71db.

Thanks @DenzilLee!
