### ISSUE TITLE
[Bug]: Wrong dimension of indica on OHC0003-A-4RUDGB3

### ISSUE THREAD

**Issue by MartelSimon** [jrsteensen/OpenHornet#1046]
### Discord Username

1_neox_1

### Bug Summary

The dimension of the indica (black) on knob OHC0003-A-4RUDGB3 are not the same as the real knob.

### Expected Results

The dimension of the indica (black) on knob OHC0003-A-4RUDGB3 should be going all the way to the back ring.

### Actual Results

The dimension of the indica (black) on knob OHC0003-A-4RUDGB3 stop before it get to the back ring.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/62399800/568bb46e-c933-4298-9acf-08e8799ed4fb)
![image](https://github.com/jrsteensen/OpenHornet/assets/62399800/4ee2c527-d4b7-4cde-9f25-21cb71597a92)
![image](https://github.com/jrsteensen/OpenHornet/assets/62399800/817804be-97b0-4556-9000-6ac620e41826)
![image](https://github.com/jrsteensen/OpenHornet/assets/62399800/1e3b677a-f1c1-47ca-af2e-ab3e302aafd6)
![image](https://github.com/jrsteensen/OpenHornet/assets/62399800/36ecbc65-535a-4517-a25a-e205edc1a483)

### Applicable Part Numbers

OHC0003-A-4RUDGB3

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Left Console (LCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
I believe this is an artifact from moving over to Fusion.
OHC0003 drawing revision may be required.
