### ISSUE TITLE
[Bug]: VVI Connector pins mislabelled on Standby Instrument Controller

### ISSUE THREAD

**Issue by Krikeee** [jrsteensen/OpenHornet#1053]
### Discord Username

Krikeee

### Bug Summary

The Pin labels for the Standby instrument panel are incorrect for the VVI instrument. Instead of J5-X it should be J7-X

### Expected Results

VVI pins should be labeled with J7 not J5

### Actual Results

They are labeled with J5

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/91638076/22b8e8e6-42d6-4201-b4b2-caa8a3ca20ad)

### Applicable Part Numbers

2A7A1A5

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Thanks @Krikeee for the issue!
