### ISSUE TITLE
[Bug]: Different Electrical Requirements on OH homepage (Dev Wiki) and interconnect PDF

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1062]
### Discord Username

Higgins

### Bug Summary

The Dev Wiki on the OH homepage isn't up-to-date.

### Expected Results

Same information on Wiki and interconnect.

### Actual Results

See pictures.

### Screenshots/Images/Files

<img width="906" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/81c4b400-11db-48aa-b7c9-21a487c2ce4a">

<img width="681" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/62823a7b-2c01-4f7e-a1b0-f81c4fbf643f">

### Applicable Part Numbers

Dev Wiki, Interconnect v12

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Top Level Assembly (TLA)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by kbastronomics** [comment]
26awg is much better for signal cables (not counting those in the BACKLIGHT and/or the BUSS cables.
but wiring from the ALE/ALE Relays to the panels 26AWG should be enough

**Comment by jrsteensen** [comment]
Fixed

![image](https://github.com/user-attachments/assets/519e17eb-9716-45f9-8f07-d8de6dc28385)
