### ISSUE TITLE
[Bug]: UIP construction PDF doesn't explain where to put the wooden inserts

### ISSUE THREAD

**Issue by eHanseJoerg** [jrsteensen/OpenHornet#1063]
### Discord Username

Ulukaii

### Bug Summary

The doc **/release/OH1_Upper_Instrument_Panel/OH1A1-1 - ASSY, UPPER INSTRUMENT PANEL_-_v11.pdf** desrcibes the construction of the UIP. However, the lines for part 62 (INSERT, 8-32, SELF-TAPPING, FOR SOFTWOOD) do not connect with the holes.

This makes it impossible to verify the (probable) location of the inserts without referring to Fusion. 

I do not know if reference to Fusion is required/intended/assumed for the MCAD.

Solution proposal:
Update construction drawing to show proper lines connecting the inserts with the respective holes. As a workorund, add a comment explaining where the inserts should go
![Bild 22 05 24 um 11 55](https://github.com/jrsteensen/OpenHornet/assets/19169901/cf2c531c-e126-41b2-9b6b-175773b8d2dd)

### Expected Results

I expect to be able to construct the structure by solely referring to the PDF.

### Actual Results

PDFs are sometimes not sufficient. This is one instance. Another instance is the LIP (bug rep will be filed). 

### Applicable Part Numbers

OH1A1-1

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fix broken extension lines.
