### ISSUE TITLE
[Bug]: COMM Panel Diagram Missing Label 13 for Potentiometers on the OH4A7A1-1 ASSY

### ISSUE THREAD

**Issue by viajandee** [jrsteensen/OpenHornet#1066]
### Discord Username

ViajanDee

### Bug Summary

The 8 potentiometers on the diagram are missing label 13. It is mentioned in the Parts List but not on the -1 ASSY.

### Expected Results

Label 13 is to be added pointing at one of the 8 potentiometers.

### Actual Results

New users may miss such an important component of the comm panel.

### Screenshots/Images/Files

<img width="727" alt="Screenshot 2024-05-29 at 10 48 23 AM" src="https://github.com/jrsteensen/OpenHornet/assets/86091586/570bc5bc-c572-4eab-92be-2bfc550f126b">

### Applicable Part Numbers

OH4A7A1-1

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Left Console (LCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with #1078
