### ISSUE TITLE
[Obsolescence]: FCS Reset Push Button MB2011SB1W01 by NKK

### ISSUE THREAD

**Issue by viajandee** [jrsteensen/OpenHornet#1067]
### Discord Username

ViajanDee

### Issue Summary

The FCS Reset push button Mfr No. MBN15SB1W01 by NKK is now obsolete and no longer available on DigiKey and Mouser Electronics.

### Applicable COTS Part Number

MBN15SB1W01

### Applicable OH Part Numbers

OH4A6A1-1/4A6A1SW2

### Screenshots/Images/Files

![Screenshot 2024-05-29 at 12 06 23 PM](https://github.com/jrsteensen/OpenHornet/assets/86091586/4522e35d-70d5-4823-8982-de05c238a023)
<img width="539" alt="Screenshot 2024-05-29 at 12 07 34 PM" src="https://github.com/jrsteensen/OpenHornet/assets/86091586/707d59f9-264f-492e-b2cc-b10f08c659fc">
![Screenshot 2024-05-29 at 12 11 41 PM](https://github.com/jrsteensen/OpenHornet/assets/86091586/77ae7bc5-c231-46f2-bbe7-76ec748a86ca)

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Left Console (LCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.

**Comment by jrsteensen** [comment]
Still showing as active and available from a number of sources. Will close without action for now unless something changes.

![image](https://github.com/user-attachments/assets/9180c0d3-ece7-49a6-a801-32715240c3ba)
