### ISSUE TITLE
[Bug]: OH2A3A1-1 AMPCD Module Missing Label

### ISSUE THREAD

**Issue by tunatuk** [jrsteensen/OpenHornet#1072]
### Discord Username

tunatuk

### Bug Summary

On OH2A3A1-1 - ASSY, AMPCD MODULE_-_V3.PDF, label no. 7 is missing for AMPCD Finger Guard B.

### Expected Results

Update to have label for OH2A3A1-16 as no 7 and indicated on the technical drawing

### Actual Results

Label No. 7 is missing from the diagram.

### Screenshots/Images/Files

![AMPCD Missing No  7](https://github.com/user-attachments/assets/ac21c91e-cf26-44f4-8d91-ba2ad4c027a6)

### Applicable Part Numbers

OH2A3A1-16

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed in referenced commit.
