### ISSUE TITLE
[FEATURE REQUEST]: UFC Panel Support: indentation for PCB missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1074]
### Discord Username

Higgins

### Feature/Enhancement Summary

The latest UFC Panel Support model doesn't have an indentation for the PCB. Would look better with one?

### Screenshots/Images/Files

<img width="718" alt="image" src="https://github.com/user-attachments/assets/06eadff4-e1ac-4b30-b239-ff2db9e85be3">

### Justification

Even it is slightly hidden and you'd have to look at it from another angle, the gap between backplate and support structure isn't necessary. Having a "sunk in" PCB would be even more aesthetically pleasing.

### Applicable Part Numbers

OH1A8A1-10

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

**Comment by jrsteensen** [comment]
Once installed, it is completely hidden by the supporting structure.

Going to close this as not planned.

![Image](https://github.com/user-attachments/assets/7e5c49a5-6d6f-40be-886f-831b67c79882)
