### ISSUE TITLE
EVU-F2MFL3B14 pot obsolescence issue

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#108]
EVU-F2MFL3B14 POT is obsolete. Need to locate suitable replacement and replace throughout the sim.

**Comment by jrsteensen** [comment]
Will replace with:

P0915N-FC20BR10K

https://www.digikey.com/product-detail/en/tt-electronics-bi/P0915N-FC20BR10K/987-1762-ND/6155634

**Comment by balzreber** [comment]
The P0915N-FC20BR10K don't seem to have the same screw (shaft) diameter than the old ones. At least they don't fit into the OH1A8A2A-11 - HUD Panel Backplate. (They have a considerably smaller diameter)

**Comment by balzreber** [comment]
I'm referring to the bushing size. But it is almost the same as the rest of the shaft size in this model.

**Comment by balzreber** [comment]
Also, there is a small key thingy on top of the housing.
![IMG_0332](https://user-images.githubusercontent.com/9654244/70387393-1fadbf00-19a5-11ea-8150-c4a3ae1063eb.jpeg)

**Comment by jrsteensen** [comment]
Added CAD model of new pot with commit 92bd91f.

**Comment by jrsteensen** [comment]
Closing issue. Will be addressed in each Release Package issue.
