### ISSUE TITLE
[Bug]: Interconnect Diagram error - 2A7A1W3P1

### ISSUE THREAD

**Issue by Hunstone** [jrsteensen/OpenHornet#1087]
### Discord Username

hunstone

### Bug Summary

In standby instrument section vvi cable  says j7 not j5

### Expected Results

In standby instrument section vvi cable should say j7 not j5

### Actual Results

In standby instrument section vvi cable  says j7 not j5

### Screenshots/Images/Files

![image](https://github.com/user-attachments/assets/3c428f79-0561-4647-9f05-cbb50e1d23e1)

### Applicable Part Numbers

OH-INTERCONNECT -OH-INTERCONNECT - OPENHORNET SYSTEM INTERCONNECT_-_v10.pdf OPENHORNET SYSTEM INTERCONNECT_-_v10.pdf

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Top Level Assembly (TLA)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Was already fixed in #1053
