### ISSUE TITLE
[FEATURE REQUEST]: Backlight LEDs in close vicinity to switches are prone to blinding pilot

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1090]
### Discord Username

Higgins

### Feature/Enhancement Summary

Some backlight LEDs are placed in such a way (and are not being covered by the panel) that they might blind the pilot.

### Screenshots/Images/Files

Example: Master Arm panel.
The LED on the left of the switch (bottom arrow) shines directly into the pilot's eye. In this case I covered it with black tape.
(The other two arrows mark where the backplate should have been closer to the LEDs to prevent light bleeding when there is an error margin between lightplate and backplate.)

<img width="429" alt="image" src="https://github.com/user-attachments/assets/ca7f7bc5-bf9e-48a7-b0d2-baf3d13cce24">

### Justification

Because the light plate holes' diameters are big enough for the nut to easily fit, some of the LEDs aren't covered by the light plate or the engraving plate.
In some situations (especially when everything is dark and the panels are lit) some LEDs are able to light into the pilot's eye directly.

Since a redesign of the panels is unnecessary or plain impossible, the quick'n'dirty way of putting some tape of the edges of said LEDs will help.
Alternatively, a very thin but light-tight washer for the switches would do the trick too.

### Applicable Part Numbers

switches on backlit panels

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Top Level Assembly (TLA)

**Comment by jrsteensen** [comment]
Add lightproofing general practices section to `OH-SPEC-001 - COMPONENT FABRICATION METHODS`.

Recommend keeping bench stock:
1. [Permatex 85120 Liquid Electrical Tape](https://www.permatex.com/products/adhesives-and-sealants/specialty-adhesives-removers/permatex-liquid-electrical-tape/)
2. [Permatex 82180 Black RTV](https://www.permatex.com/products/gasketing/black-gasket-makers/permatex-ultra-black-rtv-silicone-gasket-maker-3-35-oz/)
3. [Soft Ø1mm Rubber O-Ring Stock](https://www.mcmaster.com/1209N1/)
4. Aluminum Foil
5. Electrical Tape
