### ISSUE TITLE
[Bug]: UIP Interconnect diagram Mislabeled L and R DDI

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#1100]
### Discord Username

Arribe

### Bug Summary

Sheet 2 for the UIP's internal displays incorrectly list the L DDI as AMPCD Display, and the R DDI as the STBY INST DISPLAY

### Expected Results

They should be listed as L and R DDI

### Actual Results

L DDI labeled as AMPCD Display, and the R DDI labeled as the STBY INST DISPLAY

### Screenshots/Images/Files

![image](https://github.com/user-attachments/assets/e9baf631-35ea-4ba7-bd2d-d30e00689260)

### Applicable Part Numbers

OH-INTERCONNECT - OPENHORNET SYSTEM INTERCONNECT_-_v10.pdf

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Will be fixed in the PR.
