### ISSUE TITLE
[FEATURE REQUEST]: Revert RS485 Bus Masters to ABSIS Mega Masters

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#1107]
### Discord Username

Noctum

### Feature/Enhancement Summary

Revert from Pro-Micro RS485 Bus Masters to Mega RS485 Bus Masters.

Update Interconnect, UIP, LIP, RC, LC drawings.

### Justification

No need to modify DCS-BIOS core code to support pro-micro.

### Applicable Part Numbers

ABSIS Bus Masters

### Release Version

v0.2.0

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Top Level Assembly (TLA), Upper Instrument Panel (UIP), Lower Instrument Panel (LIP), Left Console (LCON), Right Console (RCON)

**Comment by eHanseJoerg** [comment]
For reference, here is the exact commit that changed to Master from a MEGA to a Micro: [https://github.com/jrsteensen/OpenHornet/commit/356f8010739f2768472c280f88918fc2f5349448](https://github.com/jrsteensen/OpenHornet/commit/356f8010739f2768472c280f88918fc2f5349448)

The gerber files for the MEGA-Master can be found in ECAD / zz_obsolete_for_reference / ABSIS :
[https://github.com/jrsteensen/OpenHornet/tree/356f8010739f2768472c280f88918fc2f5349448/ECAD/zz_obsolete-for-reference-only/ABSIS](https://github.com/jrsteensen/OpenHornet/tree/356f8010739f2768472c280f88918fc2f5349448/ECAD/zz_obsolete-for-reference-only/ABSIS)
