### ISSUE TITLE
[FEATURE REQUEST]: OBOGS panel backplate not rigid enough in PETG

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1109]
### Discord Username

Higgins

### Feature/Enhancement Summary

I don't know whether an acryl backplate would have more rigidity, but my PETG backplate of the OBOGS panel is not rigid enough for the force needed to actuate the OBOGS switch.
Some additional mounting point would be helpful.

### Screenshots/Images/Files

https://github.com/user-attachments/assets/b06876bc-0b0a-42eb-8f29-33f033cd2d0f

### Justification

A more rigid backplate would have a nicer feel and bring more stability to the pit.

### Applicable Part Numbers

OH4A7A2-1

### Release Version

v0.2.0

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Left Console (LCON)

### Miscellaneous Info

The design calls for acryl, I used PETG (which is an often-used substitute).

**Comment by jrsteensen** [comment]
Just mocked up a test with acrylic, and verified it works with no perceivable flex. Going to close this.
