### ISSUE TITLE
Test RS485 communications

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#120]
Since I have an ABSIS MEGA and an ABSIS NANO finished, I will test the RS485 communication between them shortly.

**Comment by petersawka** [comment]
Tested RS485 Communication with ABSIS 2.0 using DCS Bios Test Scripts; 
Confirmed connectivity with DCS with both DDI Test Script (via TI TCA9554) and standard DCS Script for input;

Determined that the connectivity worked with JP1 connected or disconnected on the Nano Shield.

**Comment by jrsteensen** [comment]
Yay. The second issue we will address under #119 and go ahead and close this issue.
