### ISSUE TITLE
ABSIS MOSFET pin order

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#122]
The pin order of the MOSFET's on all the ABSIS boards is Drain/Gate/Source. The MOSFET who is noted in the KiCAD design is IRF3205, and the one noted in the ABSIS BOM.xlsx file is IRLB8721PBF. Both of them have the Pins Gate/Drain/Source. The PCB layouts have to be changed accordingly.

**Comment by balzreber** [comment]
Please also delete all manufacturing files after changing the layout. Since they will be obsolete.

**Comment by amanuense** [comment]
Working on it

**Comment by jrsteensen** [comment]
Closed with #125
