### ISSUE TITLE
Right Console Release Package

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#136]
- [x] Update all knobs (shaft cavity and set screws).
    - [x] RALT Gauge
    - [x] ECS Panel
    - [x] INTR LT Panel
    - [x] SNSR Panel
    - [x] SIM CNTL Panel
    - [x] KY58 Panel
- [x] Replace all EVU-F2MFL3B14 pots with P0915N-FC20BR10K pot.
    - [x] KY58 Panel
    - [x] INTR LT Panel
    - [x] DEFOG Lever
- [ ] Ensure all CNC'd parts have internal radii at corners.
- [ ] Complete all outstanding items assigned in end item project.
- [ ] Add all controller PCBs to MCAD IAW System Architecture.
- [ ] Complete drawings:
    - [ ] OH5A1A1 - ASSY, RIGHT CONSOLE
    - [ ] OH5A1A1A1 - ASSY, RIGHT CONSOLE STRUCTURE
    - [ ] OH5A2A1 - ASSY, HOOK LEVER & INDICATOR
    - [ ] OH5A2A2 - ASSY, WING FOLD HANDLE
    - [ ] OH5A2A3 - ASSY, AV COOL SWITCH
    - [ ] OH5A2A4 - ASSY, RADAR ALTIMETER GAUGE
    - [ ] OH5A2A5 - ASSY, HYD PRESS GAUGE
    - [ ] OH5A3A1 - ASSY, CAUTION LIGHT PANEL
    - [ ] OH5A4A1 - ASSY, ELEC PANEL
    - [ ] OH5A5A1 - ASSY, ECS PANEL
    - [ ] OH5A5A2 - ASSY, DEFOG/WINDSHIELD PANEL
    - [ ] OH5A6A1 - ASSY, INTR LT PANEL
    - [ ] OH5A7A1 - ASSY, SNSR PANEL
    - [ ] OH5A8A1 - ASSY, SIM CNTL PANEL
    - [ ] OH5A9A1 - ASSY, KY58 PANEL
    - [ ] OH5A10A1 - ASSY, RIGHT CIRCUIT BREAKERS
    - [ ] OH5A10A2 - ASSY, CANOPY SWITCH
- [ ] Update interconnect diagram.
- [ ] Check for duplicate hardware.
- [ ] Generate all intermediate/manufacturing files.

**Comment by dnamaster2000** [comment]
STL files for Right Console Structure, all test printed, high poly, unmodified.

[Right Console Structure.zip](https://github.com/jrsteensen/OpenHornet/files/4572252/Right.Console.Structure.zip)

**Comment by jrsteensen** [comment]
Listed all drawings for right console in issue.

**Comment by jrsteensen** [comment]
Combined into #313
