### ISSUE TITLE
MK1101RR02QE Button OH1A2A-14 Master Arm Bracket hole

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#137]
The hole in the Master Arm Panel Bracket OH1A2A-14 is too small for the emergency jettison button MK1101RR02QE. I measured the outer diameter of the button thread to be exactly 0.25 inches.

**Comment by balzreber** [comment]
I know, very individual. But the hole in my bracket is ~0.23 inches.

**Comment by jrsteensen** [comment]
Fixed in commit e94187909686deee69509c8586cc6fc32e86f88c.
