### ISSUE TITLE
UIP Manufacturing Files

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#148]
- [ ] Generate all intermediate/manufacturing files.
    - [x] All UIP DXFs
    - [x] All UIP STLs
    - [ ] OH1A-1_SH[SHEET #]_[SHEET THICKNESS]_MDF.DXF (MDF CNC PARTS)
    - [ ] OH1A-LEGENDS.DXF (LEGEND PLATES)
    - [ ] OH1A-LIGHTPLATES.DXF (LIGHT PLATES)
    - [ ] OH1A-BACKPLATES.DXF (BACKPLATES)
    - [ ] OH1A-INDICATORCOVERS.DXF (INDICATOR COVERS)
    - [ ] OH1A-INDICATORLEGENDS.DXF (INDICATOR LEGENDS)
    - [ ] OH1A-DIFFUSERSGREEN.DXF (INDICATOR DIFFUSERS, GREEN)
    - [ ] OH1A-DIFFUSERSAMBER.DXF (INDICATOR DIFFUSERS, AMBER)
    - [ ] OH1A-DIFFUSERSRED.DXF (INDICATOR DIFFUSERS, RED)
    - [x] All DDI Knobs (Revised for shaft and setscrews)
    - [x] Spin Panel HMD Knobs (Revised for shaft and setscrews)
    - [x] All HUD Panel Knobs (Revised for shaft and setscrews)
    - [x] HUD Panel backplate (Revised for new potentiometer)
    - [x] HUD BIT Box (Revised to remove UFC Controller PCB and associated HW)
    - [x] All UFC Panel Primary Module Parts (Integrated UFCv3)
    - [ ] Regenerate STL for SARI Knob
    - [ ] Regenerate STL for Right EWI Chassis
    - [ ] Regenerate STL for Left EWI Chassis
    - [ ] Regenerate STL for Right EWI Light Channels
    - [ ] Regenerate STL for Left EWI Light Channels.

**Comment by jrsteensen** [comment]
Please make any commits to the MCAD_UIP_Release_Package branch.

**Comment by Luft101** [comment]
the files OH1A-110.stl, OH1A-111.stl and OH1A-116.stl are low-poly, also in the latter, the text is inverted. If you fix the originals, I convert them back to stl when you want

**Comment by jrsteensen** [comment]
Merging with #314
