### ISSUE TITLE
Ejection Seat STL Issues

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#158]
Some of the .stl files are missing/mislabeled.

OH3A2A-44 should be labbled OH3A2A-39
and 41-44 are missing

**Comment by dnamaster2000** [comment]
![image](https://user-images.githubusercontent.com/56710225/71607367-c7528300-2b46-11ea-97bb-ab4f778cbc86.png)
![image](https://user-images.githubusercontent.com/56710225/71607370-d1748180-2b46-11ea-8115-6127ffc41b06.png)

The two screenshots here show the difference between the PDF listing and the files included in the release

**Comment by jrsteensen** [comment]
This was closed by #182
