### ISSUE TITLE
OH3A2A-92 - Emergency Restraint Release Handle - Split part for 3D Printing

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#159]
The part is very difficult to 3D print cleanly, recommend splitting the part like this so it can be printed in 2 halves.

![image](https://user-images.githubusercontent.com/56710225/71636656-0f35e080-2c01-11ea-8209-2227d7f4b9c0.png)

**Comment by hobu3d** [comment]
@dnamaster2000 
Just 'sink' the object in the slicer on z-axis to get only the top half. Print it.
Now turn object 180 degress and sink it again and print.
Glue both objects together. Ready

**Comment by jrsteensen** [comment]
Marking this as a down the road fix, and closing it for now.
