### ISSUE TITLE
Indicator Legends too small

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#161]
The indicator legends on the Eyebrow Warning Indicators left and right are too small. They should be as big as the glass plates they are mounted on, not as big as the hole in the indicator panel.

![IMG_0462](https://user-images.githubusercontent.com/9654244/71748931-5677d780-2e74-11ea-9801-b7930e20d804.jpeg)

**Comment by jrsteensen** [comment]
1152ca970cb183f3a53e607d31d2bd91b6dbb2b1: fixed font sizing in EWI legends. Size should be good, if centered properly. Check size during reprint, perhaps oversize very slightly, then cut to fit. This might be an iterative process. For now, going to close this. Can reopen if not resolved.

**Comment by balzreber** [comment]
Reexport all the UIP ScreenPrints after @jrsteensen fixed them.

**Comment by jrsteensen** [comment]
Updated .55 indicator in 4a235e0a0d6938a73d6f3fc2111e025e38ab16a8.
Updated spin indicator font in 5ca04192a69a265bf7aa0d3d2c93ef0bf82a8e42

**Comment by jrsteensen** [comment]
@balzreber Is this resolved with those two commits?

**Comment by jrsteensen** [comment]
@balzreber Do you have any updates on this issue?
