### ISSUE TITLE
Redesign DDI Shield

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#164]
Redesign DDI Shield to accommodate two rotary encoders instead of potentiometers.

**Comment by jrsteensen** [comment]
Done. Requires manufacturing files. Thanks @balzreber and @amanuense

**Comment by balzreber** [comment]
Found that the I2C pins are routed to the wrong Arduino Pins. They are D4 and D5 currently and should be changed to A4 and A5. I will have a stab at this.

**Comment by amanuense** [comment]
That means the template is wrong we should check other custom pcbs using
i2c including UFC

**Comment by jrsteensen** [comment]
Any update on this?

**Comment by jrsteensen** [comment]
@balzreber Can you provide a status update on this?

**Comment by balzreber** [comment]
I didn't do any work on that. But since I will receive some demo dome switches soon, I hope to assemble the DDI soon and then come back to that error.

**Comment by balzreber** [comment]
I have redesigned the shield. But since I tore up some stuff it needs a thorough review before I'm comfortable ordering an alpha version for testing.

**Comment by jrsteensen** [comment]
Awesome! Please make a pull request so we can review it. 😁

**Comment by jrsteensen** [comment]
This is outdated with the ABSIS 2.0 redesign. Closing this issue.
