### ISSUE TITLE
Add a Normal Time push button on the Sim Control Panel

### ISSUE THREAD

**Issue by bjanders** [jrsteensen/OpenHornet#166]
The Sim Control Panel has a toggle switch for increasing and decreasing game time speed. It would be nice with a "Normal Time" push button on the Sim Control panel. When you fast forward with the toggle switch and then reach the point where you want to resume normal time game play I'd rather press a button than slowing it down with the toggle switch until normal speed is reached.

**Comment by jrsteensen** [comment]
Will look at redesign, including moving the Master Sim Mode switch to the SIM PWR panel on the left console. Alternatively, could potentially combine by converting some momentary toggles to 4-way hats.

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/72640972-3f31f300-3926-11ea-8d97-4d5d262bba5f.png)
WIP
