### ISSUE TITLE
Ejection Seat Manufacturing DXFs corrupted.

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#176]
In this DXF-file most of the screwholes are missing.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/62520296/77259461-e5c9a580-6c81-11ea-9e62-0169510e49d7.png">

----------

All DXFs are corrupted for the seat. Being reworked.

**Comment by jrsteensen** [comment]
Combining #177 into this issue. All DXFs are being reworked for the seat by @Stang51.

**Comment by jrsteensen** [comment]
Closed with #190 .
