### ISSUE TITLE
UIP, STLs are low poly

### ISSUE THREAD

**Issue by Luft101** [jrsteensen/OpenHornet#179]
the files OH1A-110.stl, OH1A-111.stl and OH1A-116.stl are low-poly, also in the latter, the text is inverted. If you fix the originals, I convert them back to stl when you want

**Comment by Luft101** [comment]
![Anotación 2020-03-28 180350](https://user-images.githubusercontent.com/58053727/77828896-8a366680-711e-11ea-9822-a42f0e4b7620.png)

**Comment by jrsteensen** [comment]
Still need to do OH1A-116.stl.
