### ISSUE TITLE
No attachment between Select Jett Dial and Outer shaft

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#185]
There is no connection between the Select Jettison Dial and the Outer shaft
![image](https://user-images.githubusercontent.com/56710225/79401165-5e0c4980-7f56-11ea-8a2b-1d66ec60143e.png)

**Comment by dnamaster2000** [comment]
In my build, i resolved this by creating a bushing to go around the outer shaft, and put a grub screw through the dial and bushing against the outer shaft

**Comment by balzreber** [comment]
This is not released yet. So work in progress. I'm sure Noctum will correct that before release.

**Comment by jrsteensen** [comment]
Will decide if its an actual issue or is fine with gravity retaining button. Marked for further evaluation and reopened for future tracking.

**Comment by dnamaster2000** [comment]
This is related to the outer dial, not the push button

**Comment by jrsteensen** [comment]
Looked at the model closer, its a shaft collar with a corrupted model. It's retained.

Fixing it now, and will replace set screw above it with a SHCS so it clocks the button to the dial.
