### ISSUE TITLE
SIM PWR Panel Switch Holes misaligned to Console Structure.

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#188]
![20200418_193447](https://user-images.githubusercontent.com/56710225/79792943-c45de700-831d-11ea-8502-8af1f7caac10.jpg)

**Comment by jrsteensen** [comment]
Thanks! Will address when I start the left console drawings.

**Comment by L-Walker** [comment]
Working on this issue now, as a combined update I will be making this panel follow the same 4 layer sandwich with the rest of the panels to allow it to be backlit and manufacturable with the same Rowmark legend plate.
