### ISSUE TITLE
HS-35HD Nano Servo Obsolete

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#189]
HS-35HD Nano Servo is obsolete. Will need to replace in design.

Right Console: RALT Gauge
Left Console: FCS Panel, Rudder Trim Knob

**Comment by Higgins-OH** [comment]
It's needed in the FCS panel (rudder trim knob).

**Comment by jrsteensen** [comment]
Thanks!

**Comment by L-Walker** [comment]
https://www.adafruit.com/product/169?gclid=CjwKCAjw2P-KBhByEiwADBYWCj8eNZLTFUT1YC8l7er7LI-Yy6HbaHHs4wmj_m9wKlaE0eDhMVgcQRoCuToQAvD_BwE

**Comment by L-Walker** [comment]
Did we get a reply from them? If not do we have a backup plan?

**Comment by jrsteensen** [comment]
Replaced RALT servo with HK5320
Other two will be replaced with Pololu servo. (HK doesn't have enough torque to actuate reliably.)

**Comment by jrsteensen** [comment]
Closed by @erikscott128 with FCS mech redesign. Thanks Erik!
