### ISSUE TITLE
Unused screw hole in Seat Pan Front B

### ISSUE THREAD

**Issue by bjanders** [jrsteensen/OpenHornet#193]
A very minor issue that really doesn't have any impact on the build, but there is an unused screw hole in Seat Pan Front B.  Go ahead close directly as "won't fix" if you want.
![image](https://user-images.githubusercontent.com/557482/80535839-17810b00-89aa-11ea-9699-3daad27c8bc3.png)

**Comment by jrsteensen** [comment]
Good catch. Will add to list of potential future fixes if I have a real reason to revisit the seat.
