### ISSUE TITLE
Ejection Seat Redesign

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#195]
Redesign Ejection Seat based on RTM's reference mesh:
- [ ] Two part design: Headrest & Main Rails with separate seat bucket, using shims to adjust seat up and down from Neutral Seat Reference Point (NSRP), while maintaining constant design eyebox.
- [ ] Keep seat bucket supports (from floor) as wide as possible to maintain clearance for stick mechanism.
- [ ] Ensure stick does not interfere with seat through full range of motion.
- [ ] Support a 250lb pilot.
- [ ] Ensure sufficient clearance underneath seat to not conflict with stick pitch springs and mechanism.

#### Hardware
- Use 90081A144 Domed Screw Nails as faux rivets throughout.
- Use domed MDF PHS as required.

#### OH3A2A-100 - ASSY, SEAT BUCKET, SJU-17
- [ ] Add cosmetics
- [ ] Add MDF HW
- [ ] Add inserts and machine screws for mounting seat sides to bucket.
- [ ] Add mounting screws for Manual Override Handle switch.

#### IDEAS & BRAINSTORMING
Frame:
2X Machifit 200-1000mm Black 2060 V-Slot Aluminum Profile Extrusion Frame for CNC Tool DIY - 1000mm ($25.75/ea)
4X Machifit 4040 Industrial Aluminum Extrusions Right Angle Inclined Bracket Connector Reinforced Black

Seat Bucket: 
2020 along bottom, 2040 along back with hinge at bottom 
2X Machifit 4040 Industrial Aluminum Extrusions Right Angle Inclined Bracket Connector Reinforced Black

[Aluminum Extrusion](https://www.banggood.com/Wholesale-Aluminum-Extrusions-c-11889.html)

**Comment by bjanders** [comment]
The seat pan base should be extended forward something like this: 
![image](https://user-images.githubusercontent.com/557482/80744039-b763a380-8b26-11ea-9437-4cfc74a76146.png)

I eyeballed it to around 1" wide and 4" long and both arcs with a radius about 2". (I made them 20  x 100mm, radius 45mm).

**Comment by bjanders** [comment]
If you are making changes then you can also fix this non-issue: https://github.com/jrsteensen/OpenHornet/issues/193. The real benefit is probably that someone does not use time to drill a hole that is not actually needed, or wonder if they are missing something since they can't find a use for it.

**Comment by jrsteensen** [comment]
> The seat pan base should be extended forward something like this:
> 
> I eyeballed it to around 1" wide and 4" long and both arcs with a radius about 2". (I made them 20  x 100mm, radius 45mm).
> If you want to be super accurate, then there is screw hole going in from the front into the short edge.

The real kneeguards angle outboard slightly. Adding this with straight kneeguards (necessary due to MDF construction of seat) will only *painfully* affect the user. I probably will not integrate this, though I will consider it.

**Comment by jrsteensen** [comment]
Updated issue to reflect complete seat redesign.

**Comment by uxixu** [comment]
Might mention that the safe arm handle looks like it has safe on the side too low, instead of towards the edge, as it does in game (DCS).

**Comment by jrsteensen** [comment]
@uxixu I'd love to look at it! Please shoot me some pictures, though DCS has enough inaccuracies that it is a reference of last resort on this project.

**Comment by uxixu** [comment]
Google Fu not turning up but seems plausible guven the way it hinges.  A safe apears written on the spine, too. Here's from page 78 of Chuck's Guide. I only have Daco fur the Tomcat but if one has the Hornet version may be there in cockpit picture. 

![Screenshot_20210123-184152_Drive](https://user-images.githubusercontent.com/33010736/105619826-40082b00-5dab-11eb-94e8-190ecb5e37bd.jpg)

**Comment by uxixu** [comment]
Remembered that F-14D used NACES and DACO shows a couple,  though kinda looks like someone hand wrote safe on the side, though engraved on spine.

![20210123_192659](https://user-images.githubusercontent.com/33010736/105620406-9d9f7600-5db1-11eb-859b-742540436d43.jpg)

**Comment by uxixu** [comment]
That was pilot. Here's RIO. Definitely lower than ED's/Chuck's. 

![20210123_193235](https://user-images.githubusercontent.com/33010736/105620521-d0963980-5db2-11eb-98b6-9a780c62e4cc.jpg)

**Comment by jrsteensen** [comment]
It proabably is, I'm looking for verification on the proper model of ejection seat though - the F18 seat we are creating is a late model SJU-17. A much earlier model was used in the F14, so its not an apple to apples comparison.

**Comment by jrsteensen** [comment]
Pushing this to a post-beta release. 

TODO:

- [ ] Rail->Bucket Integration
- [ ] Bucket HW
- [ ] Rail->Pit Integration
- [ ] Add shims under bucket
- [ ] Mount OVRD SW MOUNT
- [ ] Add Seat Bucket Cosmetics
- [ ] Design Seat Placards
- [ ] Add Carbon Fiber Cosmetic Wrap where appropriate.
- [ ] Design headrest/parachute container.

**Comment by jrsteensen** [comment]
Pulled this back to beta1 after some significant work on a v1 seat to bring it to 1.5 was discovered. Decided time was better spent on v2 instead. Seat bucket almost done.

**Comment by jrsteensen** [comment]
- [ ] Add shims under bucket
- [ ] Add seat decals
- [ ] Add faux rivets to headrest. Add rubber pads where appropriate to headrest.
- [ ] Redesign Drogue Deployment Catapult to allow for installation of catapult and parachute container.
- [ ] Redesign Parachute Deployment Rocket to allow for installation of catapult and parachute container.

**Comment by jrsteensen** [comment]
Closed by above reference.
