### ISSUE TITLE
Lower Instrument Panel: Upper Instrument Panel Mount wrong thickness

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#196]
The pilot end of the board is 0.75", but the nose end is 0.77".
<img width="655" alt="Bildschirmfoto 2020-05-02 um 17 07 43" src="https://user-images.githubusercontent.com/62520296/80867947-7b9c1b80-8c97-11ea-93ac-358baf97c3ef.png">

**Comment by jrsteensen** [comment]
You made me panic a little bit, but no, that is not the case. It is trimmed at an angle on the back.

![image](https://user-images.githubusercontent.com/2449496/81097469-d19dd880-8ebc-11ea-84d1-801be6eb2c56.png)

![image](https://user-images.githubusercontent.com/2449496/81097560-f003d400-8ebc-11ea-8217-ec319bbfffcc.png)
