### ISSUE TITLE
STL Files incorrectly sized

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#198]
Went to slice the following files and have found they are incorrectly sized in Release.  
OH1A -107 - UPPER UIP FACE MOUNT, LEFT
OH1A -108 UPPER UIP FACE MOUNT, RIGHT
OH1A -109 UIP DISPLAY PRESSURE FOOT

Added from #200: OH1A8A4A-10 HUD BIT BOX STL

**Comment by dnamaster2000** [comment]
[UIP STL.zip](https://github.com/jrsteensen/OpenHornet/files/4572246/UIP.STL.zip)

**Comment by bnepethomas** [comment]
Looks good - thank you sir

**Comment by jrsteensen** [comment]
Need to add ZIPed STLs to UIP release package.
