### ISSUE TITLE
F/A-18C Hornet™ HOTAS Add-On Grip

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#2]
Require a model for further flight control stick development of the Thrustmaster F/A-18C Hornet™ HOTAS Add-On Grip. This model can either be created in SW2019 (or earlier) or STEP. High fidelity model with an accurate weight and approximate center of mass is required.

**Comment by jrsteensen** [comment]
Photogammetry is how @erikscott128 did a ton of the reference model, and the throttle grips. I don't have the capability, or the grip yet, but its a great solution.

**Comment by VF84Splash** [comment]
I will be getting a 3D scan of the TM Hornet Grip next week. Will post when it's complete

**Comment by jrsteensen** [comment]
Still require this model, previous scan attempt fell through. If anyone else has the capability, it would be extremely helpful.

**Comment by ajmilner85** [comment]
@TomHVR I live in the GTA and just picked up a Hornet grip a couple of weeks ago. Want to try and meet up to scan it? I'm in the US until Monday (Dec 9) but should be free for a few days after that.

**Comment by TomHVR** [comment]
@ajmilner85 i’m down, though was someone else able to get one scanned already, @jrsteensen ?

For scanning it I’ll need to do a babypowder spray to get good topography so you’ll need to wipe it down afterwards and it may smell a bit funny for while.

**Comment by VF84Splash** [comment]
A friend of mine back stateside tried to scan his grip, but without the
baby powder it was too reflective.... and he didn't feel comfortable
putting the baby powder on it.

Jack "Splash"

**Comment by ajmilner85** [comment]
@TomHVR Funny smell I don’t mind, as long as it still works after. Would it be wise to try and mask areas where powder could accumulate, like underneath hat switches, or should I be prepared to do a complete disassembly to properly clean it afterward? If you want to send me a PM on discord I’ll give you my contact info and we can figure out a time to meet. What kind of beer pairs best with photogrammetry sessions?

@VF84Splash That’s understandable. Fortunately I’m willing to do just about anything for the OH cause ;).

**Comment by VF84Splash** [comment]
Well, he did say that he's supposed to be getting a winwing hornet set, and
might do it then. I think if you can tape off the holes good enough it
should be fine, then use an air can or compressor to blow off the baby
powder

**Comment by TomHVR** [comment]
@ajmilner85 the best way to remove it is with baby wipes. Also the shapes of the hat switches isn't super critical so they could be taped off.

**Comment by ajmilner85** [comment]
@TomHVR Thanks for the info. Do you know somewhere that sells those 3D scanning sprays locally? I'd pay the $30 for a can to save myself the time cleaning up the stick, but another $45 for shipping is a bit much!

My schedule has changed a little, so I won't be off until next week now. I'll be off from the 17th-19th. Would you be available to meet on any of those days?

**Comment by jrsteensen** [comment]
Scan completed and raw files and mesh are here: https://drive.google.com/drive/u/3/folders/1pmYYV0Go6fy9XnuyHh0wUaClncg6AGXd

Thanks @ajmilner85 and Jump 'n Shootman for the awesome work.

If any skilled modelers have time, I need a solid STEP generated from the mesh. (Native files can be SW (2019 or earlier) or Fusion 360.)

**Comment by erikscott128** [comment]
I'm looking to get back into the swing of things. I'll lake care of this one.

**Comment by jrsteensen** [comment]
Oops. Not quite closed. Got reference mesh, now we need to model it and add buttons and mounting interface.
