### ISSUE TITLE
ABSIS Nano Lite

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#20]
Create a ABSIS Nano Lite to minimize board footprint, remove 12V lines, and replace DIP switch with two pin header (Short header to enable PGM).

**Comment by amanuense** [comment]
Do you have an outline drawing. Or something smaller will do?

**Comment by jrsteensen** [comment]
Just minimal footprint. No specific critical footprint. A reduction in width along the long axis of the nano is ideal.

**Comment by jrsteensen** [comment]
ECAD complete. Require MCAD model.

**Comment by jrsteensen** [comment]
910251f
Updated Lite to:

- remove mounting holes
- minimize footprint
- combine I/O headers into a single header.
