### ISSUE TITLE
AMPCD Pot mounting hole wrong size

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#202]
The hole for the pot is the wrong size/shape and missing the key hole on the back, The shell is also too thick, not enough thread passes through to the front for the nut.

![image](https://user-images.githubusercontent.com/56710225/81230508-9cc67a00-8fbf-11ea-8752-9ffe53657b0f.png)

**Comment by jrsteensen** [comment]
@dnamaster2000 How thick is the nut that is included with the pot? Its not in the datasheet for the pot.

**Comment by dnamaster2000** [comment]
0.092 inches (3/32)

**Comment by jrsteensen** [comment]
@dnamaster2000 And hex width, if you have it?

**Comment by dnamaster2000** [comment]
.31 across the flats .35 diagonal 

i think the thickest it could be mounted to would be about 1/8th

**Comment by dnamaster2000** [comment]
There is also a .401 diameter lock washer .036 thick

**Comment by jrsteensen** [comment]
To maintain enough panel thickness, you will have to forgo the lock washer. Otherwise fixed. :) Thanks!
