### ISSUE TITLE
Hole Mismatch between UIP Bit Box and Bit Box Lid

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#203]
There are 4 holes on the near Pilot Lid on bit box Lid (OH1A8A4A-11 - HUD BIT Box Lid.STL) versus just two on the box itself (OH1A8A4A-10 HUD BIT BOX.stl) On Far Right and Mid Right hand side.  And thanks for rescaling the bit box - it works a treat.

**Comment by jrsteensen** [comment]
Can you post pictures please?

**Comment by bnepethomas** [comment]
![IMG_2849](https://user-images.githubusercontent.com/16440158/81359019-5c7c0e80-911b-11ea-9a0c-13e90959f20d.jpg)
Here you go sir

**Comment by jrsteensen** [comment]
This is intentional - there isn't clearance for the screws below it once LEDs and everything is installed. Pretty sure I specified some shorter screws for those two holes for cosmetic purposes.

**Comment by bnepethomas** [comment]
cool - I was thinking about having a shallower hole for comestic purposes

**Comment by jrsteensen** [comment]
Thanks for bringing it up though! Keep it up!
