### ISSUE TITLE
Left Console: USB hub screws not aligned with inserts

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#204]
Absolutely super-minor mini-issue.
<img width="839" alt="Bildschirmfoto 2020-05-07 um 22 48 04" src="https://user-images.githubusercontent.com/62520296/81343495-63703600-90b5-11ea-9b01-0153e9c13829.png">
<img width="428" alt="Bildschirmfoto 2020-05-07 um 22 48 21" src="https://user-images.githubusercontent.com/62520296/81343501-65d29000-90b5-11ea-8b35-397eb290007c.png">

**Comment by L-Walker** [comment]
Solved with commit 95a59d1
