### ISSUE TITLE
UIP: Release STLs not scaled correctly.

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#205]
- [ ] OH1A -112 MFD LOWER SUPPORT C.stl
- [ ] OH1A -113 HUD PANEL AFT SUPPORT.stl
- [ ] OH1A -114 HUD PANEL CONNECTION BRACKET.stl
- [ ] OH1A -115 UIP CENTRAL TIE BRACKET.stl
- [ ] OH1A -116 MFD LOWER SUPPORT A, RIGHT.stl
- [ ] OH1A7A-14 KNOB, KORRY, RD239-A1G2.stl
- [ ] OH1A8A2A-11 HUD PANEL BACKPLATE.stl
- [ ] OH1A4A-10 - EWI Legend Plate, Left.STL
- [ ] OH1A4A-11 - EWI Chassis, Left.STL
- [ ] OH1A4A-12 - EWI Light Channels, Left.STL
- [ ] OH1A4A-13 - Pushbutton Indicator Standoff.STL
- [ ] OH1A6A-10 - EWI Legend Plate, Right.STL
- [ ] OH1A6A-11 - EWI Chassis, Right.STL
- [ ] OH1A6A-12 - EWI Light Channels, Right.STL

And a two possible left overs - wher there is a correctly scaled name - but old files exist.
- [ ] OH1A -108 UPPER UIP FACE MOUNT, RIGHT.stl
- [ ] OH1A8A4A-10 HUD BIT BOX.stl

Cheers
Peter

**Comment by bnepethomas** [comment]
Found a couple of files, updated original - this should be it as I've stepped through all files now.

**Comment by jrsteensen** [comment]
Added changed EWI files. They require STL generation. (Fixed the connector interference.)

**Comment by L-Walker** [comment]
All sorted, OH1A -109 UIP DISPLAY PRESSURE FOOT was an additional duplicate with incorrect scaling and has been deleted. The correctly scaled version remains.

**Comment by jrsteensen** [comment]
Closed IAW PR #223
