### ISSUE TITLE
Rudder Pedal Interface Plate - mount holes for Solenoid  

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#209]
The solenoid has 4 mounting holes, 2 are M3 and 2 are M4 (on each side) the holes on the gantry interface plate are lined up for the M3 holes, but M4 in size.

![image](https://user-images.githubusercontent.com/56710225/81744065-b27ce900-9470-11ea-8026-4dfa9f57a870.png)

**Comment by dnamaster2000** [comment]
There may be additional issues with this part, the solenoid is a push type, pushing the other way, needs to be rotated 180, which would leave an issue with retention of the actuator.

**Comment by jrsteensen** [comment]
@dnamaster2000 Not sure I'm completing understanding the issues you are seeing. Can you explain a little more in depth with pictures?

**Comment by dnamaster2000** [comment]
![20200530_211507](https://user-images.githubusercontent.com/56710225/83342244-0e41d180-a2bb-11ea-8ce9-50c66bdc0682.jpg)

The solenoid needs to be mounted in this direction to push the locking arm out of battery, but in this direction the actuator will just fall out the front.  if mounted the other way around, (ignoring the issue of holes in the wrong spot) it wont fit.

The second photo shows even with the locking arm fully to the rear, the solenoid will not be mountable, and would be facing the wrong way.
![20200530_211942](https://user-images.githubusercontent.com/56710225/83342277-7db7c100-a2bb-11ea-90f4-f263041d774b.jpg)

**Comment by jrsteensen** [comment]
How would you propose we fix it? Any alternate PNs in mind?

**Comment by jrsteensen** [comment]
Referenced Wrong Issue...
