### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#21]
Create a parts list for the major end items and top level assembly.

- [ ] Left Console
- [ ] Lower Instrument Panel
- [ ] Upper Instrument Panel
- [ ] Right Console
- [ ] Center Tub
- [ ] SJU-17 Ejection Seat
- [ ] Top Level Assembly

**Comment by ScottyMac52** [comment]
This may not be the right place to ask this but I am looking to build just a simple F/A-18C instrument panel, UFC etc. out of MDF but I am having an extremely hard time sourcing blueprints or drawings?

**Comment by jrsteensen** [comment]
> This may not be the right place to ask this but I am looking to build just a simple F/A-18C instrument panel, UFC etc. out of MDF but I am having an extremely hard time sourcing blueprints or drawings?

Hop on our discord - that's a more appropriate place to discuss. Right now this project doesnt have any drawings available.

**Comment by jrsteensen** [comment]
Moving this to Top Level Release Package.
