### ISSUE TITLE
COMM PANEL Legend Plate Text Adjustment

### ISSUE THREAD

**Issue by L-Walker** [jrsteensen/OpenHornet#210]
![Capture](https://user-images.githubusercontent.com/65761897/82651470-8bd46480-9c5f-11ea-9a7f-3971947360f6.PNG)

ISSUES:

- [ ]  The Position marks for the MIDS B knob have triangular end caps. They need to be squared off.

- [ ]  The MASTER EMERG/NORM Outline circle is off-center. The inside circle needs to be shifted towards the seat a couple of mm.

Arrows in Blue on the photo. Quick 2min fix in Solidworks.

**Comment by jrsteensen** [comment]
Closed with 40218c8
