### ISSUE TITLE
Antenna Elevation Pot is Obsolete and needs to change

### ISSUE THREAD

**Issue by MrMagicMan** [jrsteensen/OpenHornet#211]
The antenna elevation potentiometer cannot be sourced, a secondary one was assembled. but the body and D connector were the incorrect size (the wheel may have been sized for 0.25" vs 6mm)

**Comment by jrsteensen** [comment]
TODO: Replace EVU-F2MFL3B14 pot with P0915N-FC20BR10K

**Comment by L-Walker** [comment]
Any update @MrMagicMan

**Comment by MrMagicMan** [comment]
I was told there was a redesign, i've wasted countless hours on this so i'm out till its far more solid.

**Comment by jrsteensen** [comment]
Ended up using the P081N-271F2CBR10K pot to prevent interferences once the PCBs were integrated. This will be solved in next commit.
