### ISSUE TITLE
Pushbutton switch MSPS103B (Ldg gear panel) is obsolete

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#212]

**Comment by L-Walker** [comment]
Evaluate guarded jett button switch.

**Comment by jrsteensen** [comment]
[Also evaluate Greyhill 30-252 BLK](https://www.digikey.com/en/products/detail/grayhill-inc/30-252-BLK/2417135)

**Comment by Ben-F111** [comment]
The switch button used for SELECT JETT and RUDDER TRIM works perfect. And fits. I painted the top black. Looks the part and is cheap. 
![image](https://user-images.githubusercontent.com/67782885/134415645-6efdd60d-99c7-4d19-8785-7cfbf417a453.jpg)
![image](https://user-images.githubusercontent.com/67782885/134415668-a64d8781-af26-4eaa-b4e1-ccb44008e704.jpg)

**Comment by L-Walker** [comment]
@jrsteensen with your approval, I can use the switch Ben is recommending.

**Comment by jrsteensen** [comment]
@L-Walker please do!

**Comment by L-Walker** [comment]
Changed as per commit 63b0aae also added a little press fit switch cap to fill the hole and allow it to be painted.
![warn tone silence button](https://user-images.githubusercontent.com/65761897/136639090-8f58c481-6b7d-49ce-ab78-123ed980a111.PNG)
