### ISSUE TITLE
ABSIS MEGA serial select switch for RS-485

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#220]
The ABSIS MEGA needs a switch to select if RS-485 uses Serial 1 or Serial 0. This is needed because the bus terminating MEGA needs Serial 0 for USB comms with the PC and therefore has to use Serial 1 for RS-485. On all slave MEGAs RS-485 has to run over Serial 0 since the NANO only has Serial 0.

(This is a continuation of now closed issue ##123)

**Comment by balzreber** [comment]
Testing is done. Unfortunately, the RS-485 communication on MEGA Slave only works over Serial0, not Serial1. So we need to go with a switch to select which Serial to use.

**Comment by balzreber** [comment]
On hold to test new software. Some new DCS Flight Panel mods might be able to select the Serial to use for RS-485 comms.

**Comment by jrsteensen** [comment]
Fixed in ABSIS_2.0.
