### ISSUE TITLE
Jet Select - some LEDs in different orientation to others

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#222]
Feel free to junk this as it may be by design or due to constraint
![Screen Shot 2020-06-14 at 8 13 08 am](https://user-images.githubusercontent.com/16440158/84580082-08013880-ae17-11ea-8766-bfb9013cc452.png)
 - but noted that the orientation of the LEDs on the Left Hand Side of the Jet Select Button are reversed in orientation to the remaining LEDs on the PCB.  Its a possible source of build errors.

Cheers Peter

**Comment by jrsteensen** [comment]
Requires further investigation to determine if bug or not.
