### ISSUE TITLE
Add Salute Button

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#231]
Add a salute button to the cockpit. Should be somewhat hidden and easily accessible to the right hand away from the stick.

Location: Bottom of canopy switch box, use FCS Reset switch or similar low profile switch.

**Comment by Higgins-OH** [comment]
While you're at it: The canopy switch box feels a bit wonky when activating the canopy switch atm (PETG, 15% gyroid infill). Maybe some sort of additional internal strut would help?
