### ISSUE TITLE
Caution light and J1 issue

### ISSUE THREAD

**Issue by Kerube** [jrsteensen/OpenHornet#235]
issue with the Caution lights and the PCB, J1 lands on top of the face plate. ended up having to sand down the connector pins to make it work.

**Comment by jrsteensen** [comment]
Did you use the new ones from a couple weeks ago? I increased the openings for connectors.

**Comment by Kerube** [comment]
ah, nope. sorry.

**Comment by jrsteensen** [comment]
As you were, I was thinking of EWI. Can you provide some measurements/location/detail pics of the issue so I can update the model?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kerube** [comment]
[
![cai](https://user-images.githubusercontent.com/60160689/87266550-8a6f2d80-c493-11ea-87f0-046226cadeb8.jpg)
](url)

**Comment by Kerube** [comment]
here is the image for the Caution Advisory and in red are J1 pins and the Indicator case.

**Comment by L-Walker** [comment]
Just to update this, I will be creating a replacement PCB for this using the RGB pixel controllable backlighting system being deployed everywhere else in the pit, I intend to place the connectors saddling each side of a divider alleviating this issue. There will be 2 Molex Mini-Fit connectors.
