### ISSUE TITLE
JETT panel PCB orientation and parts size

### ISSUE THREAD

**Issue by Kerube** [jrsteensen/OpenHornet#237]
Found an issue with JETT Panel PCB. is oriented wrong.
And a small request if possible. all the components seem to be 402 footprint
Can they be changed to 602?
After buying so many 602 parts it would not make sense to change to 402
![JETT PCB error](https://user-images.githubusercontent.com/60160689/87852564-083a9b00-c8d1-11ea-87dc-7265f317541b.jpg)

**Comment by jrsteensen** [comment]
Thanks for the report - I just verified this issue in ECAD.

As far as request for 0602, unfortunately, we aren't able to physically accommodate that on this PCB. 

During the redesign, it should be designed so the front (LEDs) can be assembled by jlcpcb as a requirement.

**Comment by L-Walker** [comment]
This issue is now redundant due to this PCB being replaced with one based on the Backlighting system.
