### ISSUE TITLE
RWR PCB is missing R11.

### ISSUE THREAD

**Issue by Kerube** [jrsteensen/OpenHornet#240]
RWR PCB is missing R11 and trace to U2 pin 23.
![RWR Board Missing R11 anc connection to U2 pin23](https://user-images.githubusercontent.com/60160689/89103974-c6871580-d3e3-11ea-92d0-1d1ffa9473f7.JPG)
![RWR SCH R11](https://user-images.githubusercontent.com/60160689/89103991-e585a780-d3e3-11ea-8584-168b83e62782.JPG)

**Comment by L-Walker** [comment]
This issue is now redundant due to the PCB being redesigned with ABSIS 2.0 and Backlighting.
