### ISSUE TITLE
Backpanels issues

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#242]
1. 0.125" almost too thick for mounting Pot P0915N-FC20BR10K (standard volume pots)
2. Hole diameters for A12505RNZQ rotary switches too small.
3. Right console KY58: cutouts for pots' nubs missing.

**Comment by jrsteensen** [comment]
@Higgins-OH I'm going to need more information on all these to be able to take action on any of it.

Thanks!

**Comment by Higgins-OH** [comment]
Sorry, I‘ll elaborate tomorrow or the day after!

**Comment by Higgins-OH** [comment]
Re-open as separate, better explained issues.
