### ISSUE TITLE
Rotary switch HS13Z-D (SNS, KY58) is obsolete

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#243]

**Comment by L-Walker** [comment]
After investigation, All H13Z-D rotaries can be replaced with the same A12505RNZQ switches used elsewhere in the pit. This switch has a lock ring that allows it to have between 2 and 8 positions with the same 45 deg. index angle.

**Comment by Ben-F111** [comment]
I have this swatch and confirm it will operate per the requirements.

**Comment by L-Walker** [comment]
@jrsteensen I have changed the last switch to the A12505RNZQ with commits to the ABSIS 2.0 Branch. Completion of this issue upon your approval.
