### ISSUE TITLE
EXT lights backplate cutouts for pots missing, hole diameter too big

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#245]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The used pots need a small cutout to prevent turning.
Hole diameter is 0.188" but should be 0.148" (as seen at Comm panel, left console).

### Expected Results/How It Should Work:
Small cutouts for the nubs.

### Actual Results/How It Does Work:
No holes.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
<img width="486" alt="Bildschirmfoto 2020-08-05 um 12 50 29" src="https://user-images.githubusercontent.com/62520296/89404508-69a89980-d71a-11ea-98c5-8995bded1a3a.png">
<img width="679" alt="Bildschirmfoto 2020-08-05 um 12 44 25" src="https://user-images.githubusercontent.com/62520296/89404242-edae5180-d719-11ea-823e-0d6d7a2c20f5.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
INT lights backplate

**Comment by L-Walker** [comment]
For the record this is incorrectly labeled INT lights panel, it actually refers to the EXT Lights Panel on the right console.

**Comment by Higgins-OH** [comment]
Thank you for noticing!

**Comment by L-Walker** [comment]
@jrsteensen The changes to complete this issue are included in commit [d0a675c](https://github.com/jrsteensen/OpenHornet/commit/d0a675c2168bb1c3cb62f6e4a84cc7e34bb45d3d)
Completion of this issue is available upon your approval.
![InkedINTR LT Panel Pot Holes_LI](https://user-images.githubusercontent.com/65761897/106554314-33d05a80-656f-11eb-8912-4f5042d14c49.jpg)
