### ISSUE TITLE
DISP button colliding with canopy rail trim

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#248]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
DISP button colliding with canopy rail trim

### Expected Results/How It Should Work:
Either the button needs to be reshaped or the rail needs a small cutout. Given the cutout's fragility altering the button shape might be better.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
<img width="850" alt="Bildschirmfoto 2020-08-09 um 13 09 00" src="https://user-images.githubusercontent.com/62520296/89731278-f5d1fe00-da45-11ea-989a-4ca5c82dd44f.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
DISP_Button_Head, Canopy Rail Trim

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/127070194-fa5b9d1f-9fa7-4a18-949f-b031dc98fa0b.png)

Added .875 hole at location specified (concentric with button shaft) to left console canopy rail trim.

@L-Walker Does this affect your upcoming commit?
