### ISSUE TITLE
OBOGS Knob: Cutout for axis missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#249]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
OBOGS Knob: Cutout for switch axis missing.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
<img width="870" alt="Bildschirmfoto 2020-08-09 um 15 36 23" src="https://user-images.githubusercontent.com/62520296/89733530-510bec80-da56-11ea-9d07-1367e22d7511.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
OBOGS Knob

**Comment by L-Walker** [comment]
Changes:

Added - .25" Hole for switch shaft.
Added - Locking grub screw hole for the standard 8-32 x .093" cup point grub screw used on all other knobs.
Added - Recess for excess switch mounting thread to be hidden inside the knob, allowing mounting closer to the panel.
Added - Indicia arrow. Eyeballed it from 3 different hornet reference images.
Added - 91375A187 - SCREW, SET, 8-32 X .093, CUP POINT, HEX DRIVE, 18-8 to the OBOGS panel assembly.
![obogs knob 3](https://user-images.githubusercontent.com/65761897/127796274-4df96c0f-7bdb-44d2-8da2-54913390497d.PNG)
![obogs knob 4](https://user-images.githubusercontent.com/65761897/127796442-658df10f-b990-4fa5-be25-d24028e964b6.PNG)
 Commit: https://github.com/jrsteensen/OpenHornet/commit/dd582f8f71374baa33c58818ef8e5fb72c222a67
