### ISSUE TITLE
Altimeter Bezel: Hole for rotary encoder too small

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#250]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
EC12E2420802 needs a hole with 9mm diameter, at the moment it has only 7mm.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
<img width="727" alt="Bildschirmfoto 2020-08-11 um 15 07 12" src="https://user-images.githubusercontent.com/62520296/89900969-b261c600-dbe4-11ea-8f83-419f1a7eac71.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
EC12E2420802, Altimeter Bezel

**Comment by L-Walker** [comment]
Solved with commit https://github.com/jrsteensen/OpenHornet/commit/e7d93be0d75cef33814d916cda297ebb2c0d9852
