### ISSUE TITLE
ECS panel - Suit/Cabin Temp upper knob: hole too small for pot axis

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#251]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The upper knob doesn't fit the pot's axis: hole too small.

### Expected Results/How It Should Work:
The hole needs to be bigger.

### Actual Results/How It Does Work:
knob hole: 0.064" diameter, pot axis: 0.069" diameter

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
PTH902-030F-103B2, Korry RD239-A1G1 v2

**Comment by L-Walker** [comment]
Commit [c827606](https://github.com/jrsteensen/OpenHornet/commit/c827606cb9df997b60852a551570eccd9aad81eb) included the required updates to ensure a smooth fit, re-sized the hole following the part data sheet's recommended panel mount pattern. The backlighting PCB hole for this pot was also changed and 
MCAD part file re-exported to reflect the change.
@jrsteensen This issue can be completed if you are happy with this.
![ECS Pot Clearance](https://user-images.githubusercontent.com/65761897/106575319-0fd14100-6590-11eb-942f-c9a345204056.PNG)
