### ISSUE TITLE
6630S0D-C28-A103 (Radar Altimeter Pot) obsolete

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#252]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
6630S0D-C28-A103 obsolete

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
6630S0D-C28-A103

**Comment by Ben-F111** [comment]
The 3590S-2-103L works, however the 2 x holes in the rear need to move as this POT is "deeper"

**Comment by Ben-F111** [comment]
Note, the DCS BIOS is designed for a Rotary ENC, not a POT, however the POT is the best option, otherwise there will be ongoing sync issues with the SIM, I have raised with DCS FP team to investigate.

**Comment by L-Walker** [comment]
### Changes:

****Added** - Bourns 3590S-2-103L
Replaced** - 6630S0D-C28-A103 with 3590S-2-103L
**Changed** - Both of the connectors to clear the new pot

![rad alt 2](https://user-images.githubusercontent.com/65761897/127821565-48bf884d-e843-41e2-a3cd-68e974203da6.PNG)
![rad alt 1](https://user-images.githubusercontent.com/65761897/127821575-211a1d2e-1562-46b7-874f-340a8fe2bd16.PNG)

**Comment by kbastronomics** [comment]
I have an updated PCB for the RADALT that also fixes the the servo flag issue with it blowing servo's
its being tested by other members now.   once proven I'll submit a PR for it
