### ISSUE TITLE
Add ~1mm to outside edge of Radar Alt Bezel

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#253]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The Radar Alt bezel hardly covers the panel cutout and leaves ugly gaps. If it were just 1mm wider on each side the hole would be covered completely.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
<img width="577" alt="Bildschirmfoto 2020-08-23 um 08 59 11" src="https://user-images.githubusercontent.com/62520296/90973133-5e79aa00-e51f-11ea-88b7-2f286be2e883.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
Radar Altimeter Bezel

**Comment by L-Walker** [comment]
@jrsteensen simple fix but it goes whacky when I try to modify any of the dimensions of the bezel extrusion. I think you will understand the dimensions better.

Image of the dimension count below. 
![rad alt bezel](https://user-images.githubusercontent.com/65761897/127765677-96d5430a-b9ba-4cc5-b298-a44f829c1a86.PNG)

**Comment by jrsteensen** [comment]
Added .062 around perimeter, finagled around knob to clearance from adjacent components. Resolved in d0bfe71.
