### ISSUE TITLE
Drills and edge OFFSET between UIP FLoor Right longerons/ Glareshield 

### ISSUE THREAD

**Issue by Thibaud-54** [jrsteensen/OpenHornet#269]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
(Please summarize your issue here. Be specific.)

There is an offset between the drills in the FLOOR part and the corresponding drills/holes in the both right LONGERONS (INBOARD AND OUTBOARD). There is also an offset (air gap) between floor / Spin recovery bracket and right glareshield.
Both offsets are identical (around 2.5 mm).

### Expected Results/How It Should Work:
(Explain how you think it should work here. Be very specific.)

The drills should be repositioned by modifying the FLOOR part only until they become coincident again with the corresponding longerons. Lengthen the FLOOR part. SPIN RECOVERY BRACKET should be also modified by remove the "lip" and remove all of the air gap next to the right glareshield.

### Actual Results/How It Does Work:
(Explain how it actually works here. Be very specific.)

Please check picture below.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
![image](https://user-images.githubusercontent.com/73742549/98463667-15033780-21bd-11eb-8dd8-32c681036583.png)
![image](https://user-images.githubusercontent.com/73742549/98464296-2e5ab280-21c2-11eb-9280-41784f231ed5.png)
![image](https://user-images.githubusercontent.com/73742549/98464313-4a5e5400-21c2-11eb-8f70-091046109c51.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [X] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
UIP Floor.sldprt
Spin panel module bracket.sldprt

**Comment by jrsteensen** [comment]
Completed in referenced commit above.
