### ISSUE TITLE
Parking Brake - Switch Spacing

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#279]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The space for the switches is about 1.5mm larger than the switch housing, resulting in loose switches, that cannot be clamped.  also results in problems with the housing if clamped, it may collapse as there is nothing in the middle.

### Expected Results/How It Should Work:
reduce width by 1.5mm (or imperial equilivant)

### Actual Results/How It Does Work:
(Explain how it actually works here. Be very specific.)

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
![image](https://user-images.githubusercontent.com/56710225/103331304-436df800-4a33-11eb-85b9-9addd6dfdc9f.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Will reduce the clearance to .01 inch (0.254mm) on either side. (Same as I use for the DDI/AMPCD buttons.)
