### ISSUE TITLE
Parking Brake - Thin Wall

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#280]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
One of the walls of the switch screw housing needs to be extended slightly, there is not enough space to close in the holes in 3d printing.

### Expected Results/How It Should Work:
(Explain how you think it should work here. Be very specific.)

### Actual Results/How It Does Work:
(Explain how it actually works here. Be very specific.)

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
![image](https://user-images.githubusercontent.com/56710225/103331351-8b8d1a80-4a33-11eb-8e4a-2dde9048f5fb.png)
 vs
![image](https://user-images.githubusercontent.com/56710225/103331358-96e04600-4a33-11eb-930a-f76c8bb2f6b9.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Added .0625 of material to outside wall.
