### ISSUE TITLE
Landing gear panel has wrong text

### ISSUE THREAD

**Issue by bjanders** [jrsteensen/OpenHornet#285]
### Summary:
The OH landing gear panel says "EMERG ROTATE AND TURN", but it should say "EMERG ROTATE AND PULL". Also, it should contain an arrow to the left of "AND". 

I know the left console is not released yet, but reporting anyway so it isn't forgotten.

### Screenshots:

![image](https://user-images.githubusercontent.com/557482/103695573-84bb5600-4fa5-11eb-9bf5-eac28200d44f.png)

![image](https://user-images.githubusercontent.com/557482/103695617-9d2b7080-4fa5-11eb-9aaa-f0462379c7db.png)

### Category:
*Check one or more items.*
- [X ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
Landing Gear Panel Legend Plate.sldprt

**Comment by L-Walker** [comment]
@jrsteensen This was included in your cleanup merge of ABSIS 2.0 If you are happy it can be closed as completed.
