### ISSUE TITLE
Glareshield Mount Tabs missing in UIP Release 3D Folder

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#293]
OH1A-10 and OH1A-11 STL files are not present in the folder.  Also in MCAD there is a generic Glareshield Mounting tab- but not a specific left or right Glareshield Mounting Tab

**Comment by jrsteensen** [comment]
MCAD: The glareshield mounting tab has two configurations, one left and one right. 

The STL issue is valid.

**Comment by L-Walker** [comment]
Both have been generated and are in the release folder.

Commit: https://github.com/jrsteensen/OpenHornet/commit/7ba332ccf9a846098da23a506dcffa8ccdc415e2
