### ISSUE TITLE
DCS-BIOS Possibly missing Functions for Sim Control Panel

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#294]
A possible heads-up.

Whilst DCS-BIOS has aircraft specific commands - I'm yet to find DCS-BIOS commands for doing things such as changing views or pausing the Sim.  Possibly need to either use an additional native LUA interface, or present them Sim Control panel elements as a HID.

**Comment by jrsteensen** [comment]
Listed in interconnect to present as HID.
