### ISSUE TITLE
FCS Panel corners need to be rounded

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#30]
The panel for the FCS does not have rounded corners like the other panels. attached images compare FCS with SNSR panels.
![Rounded](https://user-images.githubusercontent.com/56710225/67065475-741e8600-f13c-11e9-89b9-a190b94d599d.PNG)
![Sharp](https://user-images.githubusercontent.com/56710225/67065476-741e8600-f13c-11e9-9bb0-c4d9fe28bd21.PNG)

**Comment by jrsteensen** [comment]
IIRC, add .0625 radius to corners of FCS panel.
