### ISSUE TITLE
ABSIS Nano Shield Bus Out and Nano USB Cable Clearance Issues

### ISSUE THREAD

**Issue by petersawka** [jrsteensen/OpenHornet#300]
### Summary:
When the Arduino Nano is installed in the Shield and the Bus Out Molex is installed (none EOL situation). The USB Cable is being torqued when installed

### Expected Results/How It Should Work:
There should be no torque applied to the USB Port when trying to program the NANO

### Actual Results/How It Does Work:
There is torque against USB Port of Nano
![image](https://user-images.githubusercontent.com/1192511/107859880-5412db80-6df1-11eb-9fe5-6e924ab39b51.png)

### Screenshots:
![image](https://user-images.githubusercontent.com/1192511/107859887-583ef900-6df1-11eb-9a96-f1ee1dc5be02.png)

### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [X] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Just unplug the Nano/Mega for programming. Will keep this noted for ABSIS 3.0.
