### ISSUE TITLE
Park Brake shaft enhancement

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#302]
### Summary:
update to construction of the park brake shaft, removal of the 4 holes, add a slot

### Expected Results/How It Should Work:
currently there are 4 x indents to marry with the 3 ball springs for the park brake, the construction proposes these are installed by 2 x intersection holes. these holes must be at 90 deg to meet the 2 x top ball springs, they are difficult to make

### Actual Results/How It Does Work:
in real life with standard shop tools (including a drill press) these are hard to get right, this also reduces the structural strength of the 1/4 rod with more than half the material removed in a small area. My first shaft broke at this point while tapping the hole for the screw, it weakened the entire rod

The 90 deg position of the handle (PARK/EMERG) is created via the screw and bushing below the indents, thus I propose the 4 x indents can be changed to a slot

I suggest 1 x 360 indent (slot) (see pics below)  is made using a drill and file, this took about 1-2 mins with the below process and resulted in a stronger handle and better constructability, function was not effected, the result actually improved function if the holes cant be created perfectly.

1, mark the location of the indent (same as the prior 4 x holes)
2, insert the rod into a drill (I used a battery drill)
3, whilst the drill is turning, score the position with a blade
3, progressively create the indent  to a depth of 1-1.5mm using a
--> pointed file (secure the mark)
--> small rounded file (main body)
--> slightly larger rounded file to (create top groove)

![BP_Shaft_1](https://user-images.githubusercontent.com/67782885/111210324-d5d86d80-8618-11eb-84d1-265fbf16cfdb.jpg)
![BP_Shaft_2](https://user-images.githubusercontent.com/67782885/111210330-d7a23100-8618-11eb-8b68-d156e5882521.jpg)

![image](https://user-images.githubusercontent.com/67782885/111211439-1f758800-861a-11eb-9540-430b9a1fe832.png)

![image](https://user-images.githubusercontent.com/67782885/111221712-94e75580-8626-11eb-8175-d386a1fd0d95.png)

### Category:

- [X] MCAD (SolidWorks)

### Type:

- [X ] Feature Enhancement

### Applicable End Item:

- [X] Left Console

### Associated Filename(s):
Parking Brake Mechanism Shaft  (and)   Parking Brake Handle Mechanism

**Comment by jrsteensen** [comment]
Resolved in 21bd19b. Replaced cross drill in parking brake shaft with .0625" groove with external radius.
