### ISSUE TITLE
Landing Gear adjustment hole required

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#306]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
On completing the build of the landing gear it  was found a hole is required to "adjust" the ball spring for the pull / rotate track

### Expected Results/How It Should Work:
The head of the ball spring is plastic and can be damaged if it is too tight or whilst trying to remove it

### Actual Results/How It Does Work:
A hole in the revers part of the housing allows an allan key to be used to adjust this

### Screenshots:

![image](https://user-images.githubusercontent.com/67782885/121254128-41b33500-c8ed-11eb-85df-f2c7a9139c9a.png)
![image](https://user-images.githubusercontent.com/67782885/121254268-690a0200-c8ed-11eb-8a4c-f7b5b57e407c.png)

### Category:
- [X] MCAD (SolidWorks)
### Type:
- [X ] Feature Enhancement

### Applicable End Item:
- [X] Left Console

### Associated Filename(s):
Landing Gear Lever Track.SLDPRT

**Comment by jrsteensen** [comment]
Resolved in 4d531b0.
