### ISSUE TITLE
Landing Gear Housing, installation holes required

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#307]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
When installing the the 2 x PHS Screws for the Gear solenoid, there is no access to "tighten the screws" it is suggested 2 x holes are made in the MCAD for the housing to allow a PHS screw driver to install these screws

### Expected Results/How It Should Work:
the 2 x screws hold on the solenoid, currently there is no access to tighten these

### Actual Results/How It Does Work:
adding 2 x holes will allow the screw driver to pass through the print and tighten the screws.

### Screenshots:
![image](https://user-images.githubusercontent.com/67782885/122134941-f10a8180-ce82-11eb-8ed5-b7f34d2558f3.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)

### Type:
*Check one item.*
- [X] Feature Enhancement
### Applicable End Item:
*Check one item.*
- [x] Left Console

### Associated Filename(s):
Landing Gear Lever Mount

**Comment by jrsteensen** [comment]
Resolved in 4d531b0. Also, an offset Philips head screwdriver like the one shown can be utilized in this location without the clearance holes.

![image](https://user-images.githubusercontent.com/2449496/127023769-9221b1eb-b2e6-4afc-a12e-d30c989079e0.png)
