### ISSUE TITLE
Radar ALT Plugs

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#308]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
Please confirm the proposed PIN outs for the RADAR ALT - Current known wires require 15 pins, 12 are currently shown

### Expected Results/How It Should Work:
Main Stepper - 4 Pins (Plug 1)
Servo - 3 Pins (Plug 1)
(7 Pins total)
R/G LED 3 Pins (Plug 2)
Switch - 2 Pins (Plug 2)
POT or ROT 3 Pins (Plug 2)
(8 pins total)

Yes sharing a common/ GND might work, but I feel 2 x 8 way plugs required

Design might need 2 x MD80PL100

### Actual Results/How It Does Work:
The Radar ALT used 2 Plugs MD80PL100 and MD40PL100, this provide 12 pins, my count is 15 pins at a min are required

### Screenshots:
![image](https://user-images.githubusercontent.com/67782885/122135766-7478a280-ce84-11eb-8cd9-e82a42c8fa5c.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
### Type:
*Check one item.*
- [X] Feature Enhancement

### Applicable End Item:
*Check one item.*

- [X] Right Console

### Associated Filename(s):
RADAR ALT - In general

**Comment by L-Walker** [comment]
### Changes

**Changed** - MD40PL100 to MD80PL100. Now there are 14 pins + 1 spare available.

![rad alt connectors](https://user-images.githubusercontent.com/65761897/127831583-16fe9aed-ec40-4fe0-a5d1-6bb908e89872.PNG)
