### ISSUE TITLE
Radar Alt (Radar Altimeter Limit Indexer Ring) - requires stoppers

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#309]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The main indexer gear for the Radar Alt currently has open teeth for its entire ring, this allows the indexer ring to be continually turned past the 0 many times

### Expected Results/How It Should Work:
The Pointer should stop at 50 or be limited to 50 (or behind the mask), to do this the teeth (gap) between 22-24 should be solid, this inhibits the ring from passing the 50 (5,000 ft)

### Actual Results/How It Does Work:
Without these teeth blocked the ring can go back to the 0 position, but really be set at 5,000 +

### Screenshots:
![Radar Altimeter Limit Indexer Ring](https://user-images.githubusercontent.com/67782885/122302259-32636580-cf45-11eb-848f-e8f28c058dba.jpg)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
- [X] MCAD (SolidWorks)

### Type:

- [X] Feature Enhancement

### Applicable End Item:
- [X] Right Console

### Associated Filename(s):
Radar Altimeter Limit Indexer Ring

**Comment by jrsteensen** [comment]
Resolved in c44fccf.
