### ISSUE TITLE
KY58 Panel - Rotary Switch - A12505RNZQ

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#311]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
KY58 Panel - Rotary Switch - A12505RNZQ - Incorrect Part Number

### Expected Results/How It Should Work:
KY58 Panel - Rotary Switch - A12505RNZQ - Is a 8 Pole 45 Deg Switch, should be a 36 Deg Switch to align with the Text

IMPORTANT - this is not a replacement Potential replacement Part Number 

### Actual Results/How It Does Work:
The 45 Deg Switch does not align with the text

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
![image](https://user-images.githubusercontent.com/67782885/125209738-50bb4780-e2de-11eb-9b69-3a2daa2d4da3.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] ECAD (PCB Design or other electrical hardware)

### Type:
*Check one item.*
- [X] Bug

### Applicable End Item:
*Check one item.*
- [X] Right Console

### Associated Filename(s):
N/A

**Comment by jrsteensen** [comment]
Requested model of 71BD36-01-1-AJN from Grayhill.

**Comment by jrsteensen** [comment]
Closed in referenced issue.
