### ISSUE TITLE
Standby Instrument Panel monitor. 

### ISSUE THREAD

**Issue by ddanois** [jrsteensen/OpenHornet#318]
### Summary:
(TFT, LCD, 11.6IN, 1920X1080P, COLOR monitor for Standby Instrument Panel may not be available. I placed an order with Aliexpress with a price listed at $179.00 two weeks ago. Today I received an email that my order had been canceled as the item was no longer available. When I checked the Aliexpress site, the monitor is still listed but it's now showing a price of $299. Not sure that this source is reliable and we may need another source or monitor)

### Category:
- [X] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
### Type:
- [X] Bug
### Applicable End Item:  
- [X] Lower Instrument Panel (LIP)

**Comment by Ben-F111** [comment]
https://www.ebay.com.au/itm/202763964355

**Comment by jrsteensen** [comment]
Displays to evaluate:

https://www.aliexpress.com/item/1005001658860376.html?algo_pvid=e7396022-36dc-404a-8eb7-2da9eba45061&algo_exp_id=e7396022-36dc-404a-8eb7-2da9eba45061-4

**Comment by jrsteensen** [comment]
Will also evaluate a reversion to analog instruments.

**Comment by jrsteensen** [comment]
After the vote on discord, it looks like we will be going the analog/digital route, with analog ALT/AS/VVI gauges, and a 7" LCD for the SARI/RWR. I will maintain the option to back the standby instrument module with an 11.6" screen in case people want to go with this option instead. #344 will track this effort.
