### ISSUE TITLE
Update/Add Selected L/R Console PCBs to Backlighting System

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#321]
Update the following PCBs to use the Backlighting System:
**Left Console:**
- [x] GEN TIE BACKLIGHT PCB
- [x] UPDATE SIM PWR PANEL BL PCB

**Right Console:**
- [x] GENERATE STEP/SLDPRT FOR CHECKLIST PLACARD AND ADD TO MCAD
- [x] DESIGN AV COOL BL PCB AND ADD TO MCAD.
- [x] ADD SLDPRT FROM ECAD TO MCAD FOR ALL BACKLIGHTING PCBS

### Category:
- [x] ECAD (PCB Design or other electrical hardware)
### Type:
- [x] Feature Enhancement
### Applicable End Item:
*Check one item.*
- [X] Left Console
- [X] Right Console

### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
@L-Walker Can you status this?

**Comment by petersawka** [comment]
@L-Walker it appears the latest commit to Beta on the Right Console is missing the links to the following file:
![image](https://user-images.githubusercontent.com/1192511/132899458-7ed185e4-eb2d-4f33-a297-a35255013602.png)

**Comment by L-Walker** [comment]
Yes you are quite right I need to move these to MCAD and out of the backlighting folder directory.

**Comment by L-Walker** [comment]
Can someone correct me if I am wrong, but the file reference issues should be fixed now.

**Comment by L-Walker** [comment]
SIM Power BL PCB has been created and is in the assembly. d57c7f3
AV Cool has been added to the right console and the relevant changes made. 03b97b8
Right console backlighting PCBs are all in MCAD. 66b039d

SIM PWR PCB

![SIM PWR PCB V3 Front](https://user-images.githubusercontent.com/65761897/136652424-e9d7ab9a-eae6-4ae3-a777-82515f40d6c0.png)
![SIM PWR PCB V3 Back](https://user-images.githubusercontent.com/65761897/136652426-b418f072-8cca-47a7-9389-1f23eaed25fb.png)
