### ISSUE TITLE
Replace "toolbox" gears in ELEC & HYD PRESS.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#322]
### Summary:
Replace the oversized gears with fixed gears in the ELEC & HYD PRESS Gauges.

### Screenshots:
![image](https://user-images.githubusercontent.com/2449496/127774777-2d5758f2-dead-4418-b859-827f9d0882d9.png)

**Comment by L-Walker** [comment]
Talk to Ben about what he has done with this to make it work and potentially hoover up some part files for them.

**Comment by L-Walker** [comment]
I am tapping out of this one, they need a bigger re-design than my skills can muster up.

**Comment by jrsteensen** [comment]
Closed in referenced commit. (Eliminated gears by using dual needle microstepper.
