### ISSUE TITLE
Add "NO" Placard to KY-58.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#325]
### Summary:

Add non-backlit "NO" placard between 4-40 screws at top of KY58 panel. Write or engrave SN in reverse on placard.

### Screenshots:
![image](https://user-images.githubusercontent.com/2449496/127778739-15c6bca1-cc5a-417f-b30e-7c7632fad9b4.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
### Type:
*Check one item.*
- [X] Feature Enhancement
### Applicable End Item:
- [X] Right Console

**Comment by L-Walker** [comment]
### Changes

**Added** - KY58 NO Legend Plate
**Changed** - Mounting screw mates to include additional legend plate

![KY58 NO 2](https://user-images.githubusercontent.com/65761897/127828113-fc6a31a3-542e-4493-8074-6e91143693d4.PNG)
![KY58 NO](https://user-images.githubusercontent.com/65761897/127826995-baf73a24-e166-41f1-ad44-08a7920db338.PNG)
