### ISSUE TITLE
Backlighting Controller PCB Connector Arrangement

### ISSUE THREAD

**Issue by L-Walker** [jrsteensen/OpenHornet#328]
The Molex mini-fit Jr connectors need to have at least 5mm more space between them in the Y axis to allow the connector clip to latch over the board header.

### Expected Results/How It Should Work:
Connector clips onto the board header

### Actual Results/How It Does Work:
Connector clip collides with the board header above it for rows 2 and 3 of the 2x2 connectors.

### Screenshots:
![OH BL Collision](https://user-images.githubusercontent.com/65761897/129669190-a763bcb5-b536-4c68-a001-37584d94bff9.jpg)

# Proposed Changes
![OH BL Collision new design idea](https://user-images.githubusercontent.com/65761897/129669199-5e40a6b9-1fe6-4484-85a7-38f9f46d5869.jpg)

### Suggested new header style to be used
![11376-01a](https://user-images.githubusercontent.com/65761897/129669392-b822a9a0-5a61-4fe7-9956-94fd6256a832.jpg)

### Category:
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
ABSIS Backlighting Controller?

**Comment by jrsteensen** [comment]
@L-Walker, do you have a PN for the stackable headers (preferably LCSC/JLCPCB?)

**Comment by L-Walker** [comment]
Good point, let me look up their catalogue and add it to our spreadsheet of JLC parts.

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/130303474-d8c7c6d5-c132-4d06-8922-f84d99326715.png)

?

**Comment by L-Walker** [comment]
Looks good to me

**Comment by jrsteensen** [comment]
It was.
