### ISSUE TITLE
Cabin Pressure Mounting - suggestion 

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#329]
### Summary:
Alternate suggestion for the Cabin Pressure Alt

### Expected Results/How It Should Work:
A Minor changes is suggested to the Cabin Pressure Indicator Body to allow this to no longer require needing gluing at final assembly 

Extending the "Shadow" of the front Bezel to the Cabin Pressure Indicator Body (adding a 3mm lip) allowed this to be screwed 'Sandwiched' to the Lower Center Pedestal Face

see pictures below

### Actual Results/How It Does Work:
Currently it appears once the Cabin Pressure Gauge is constructed, there is no obvious way to attach the bezel to the main body other than gluing, this removes the future chances to correct any issues.

### Screenshots:
![image](https://user-images.githubusercontent.com/67782885/130306079-af5eacbb-8dfb-429d-8f68-8c7fef77225e.png)
![image](https://user-images.githubusercontent.com/67782885/130306122-603f5e95-797a-4377-bc2b-548d7b2fbf5e.png)

![image](https://user-images.githubusercontent.com/67782885/130305874-d291dd76-21e8-496b-8417-5b0c6a188866.png)
![image](https://user-images.githubusercontent.com/67782885/130305981-9d35fd25-e36f-4e4b-8e88-6fabea183e0e.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)

### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
Cabin Pressure Indicator Case

**Comment by jrsteensen** [comment]
I like it. Lets do it!

**Comment by jrsteensen** [comment]
Added a .125 mounting flange to the FWD edge of the case in F929cc9.
