### ISSUE TITLE
New Mag Switch Design / Clashes

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#334]
### Summary:
Whilst the new mag switch design is functional, there are several "Clashes" within the existing Left Console that need addressing
**NOTE: This is Ben's design, and the OH variant has not yet been developed.**

### Expected Results/How It Should Work:
minor re designs are required to accommodate the longer mag switch body

SNSR Panel MOLEX connectors need to move to allow for the Mag Sw, Pic Below
LEFT AUX Panel, requires a modification to the LEFT AUX SPACER BRACKET

### Actual Results/How It Does Work:
The new body clashes with some items / structures

### Screenshots:
![image](https://user-images.githubusercontent.com/67782885/130853350-c532a725-efd8-469c-8431-bc477ac8a720.png)
![image](https://user-images.githubusercontent.com/67782885/130854338-7858e859-7f41-4746-83b8-bc22526569b5.png)
![image](https://user-images.githubusercontent.com/67782885/130854993-60465c90-c5b6-44d6-b112-7ed2a25d1270.png)
![image](https://user-images.githubusercontent.com/67782885/130855084-efe22134-99ce-4d20-b714-5f0a263c883f.png)

### Category:
- [X] MCAD (SolidWorks)
### Type:
- [X] Feature Enhancement
### Applicable End Item:
- [X] Left Console
### Associated Filename(s):
SNSR Panel PCB V2
SNSR Panel Back Plate
Left Console - Left AUX Spacer

The file I used is located here, but note, this is also modified for the winwing

https://github.com/Ben-F111/Ben-F18-Sim-Pit/blob/main/Mag%20Switch/ENG_CRANK/Left%20Console%20-%20Left%20Aux%20Spacer-MS-xbar%20v1.step

**Comment by jrsteensen** [comment]
This issue is mitigated by the vertically arranged mag switch design. Closing this.
