### ISSUE TITLE
AMPCD - finger Guards enhancement

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#339]
### Summary:
The current AMPCD Bezel design requires to printed face up, removing the ability to print face down on a smooth bed

### Expected Results/How It Should Work:
for visual reasons it is better to print bezels face down, removing the print lines in a face up situation, however the current AMPCD figure guards do not allow for this. removing the finger guards as done with the DDI allows the print to be printed face down and the finger guards added after printing.

My files are located here, but may be now an older version

GitHub\Ben-F18-Sim-Pit\AMPCD

### Actual Results/How It Does Work:
current designs only allow for face up printing, ironing does help, but achieving a smooth finish is not possible.

### Screenshots:

Face down Print
![Test_Fit](https://user-images.githubusercontent.com/67782885/131265312-6c179087-316f-4292-9cfe-72eb7cb83435.JPG)
![Build Plate_0 2mm](https://user-images.githubusercontent.com/67782885/131265313-1afb07f0-10d6-47e8-86d3-2dd4cc23fab2.JPG)
![Build Plate_0 1mm](https://user-images.githubusercontent.com/67782885/131265316-f690b589-6e5f-4bc2-9fe9-cd15f162d1e7.JPG)

Face up Print

![Org-OH_Print](https://user-images.githubusercontent.com/67782885/131265320-ce9bfd05-d41b-44be-9c69-eaf83e1ea711.JPG)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
AMPCD Bezel

**Comment by jrsteensen** [comment]
Closed with f44da5d
