### ISSUE TITLE
Add Fourth Mounting Point for Skew AMPCD

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#347]
### Summary:

The AMPCD Center Pedastal Mount is only secured to the wooden frame by three mounting points. This results in it being slightly askew.

### Expected Results/How It Should Work:
A fourth mounting point should be added to properly square the AMPCD. 

### Actual Results/How It Does Work:
With the fourth mounting point added there will be no room for the AMPCD to be skew. There is an issue with clearance from the screen for the Standby Instrument panel, this will be resolved once the panel is made fully analog. In the meantime, the fourth mounting point will have to go into the roof of the LIP. See second image.

### Screenshots:

![Screenshot (428)](https://user-images.githubusercontent.com/68113057/132573881-fd51244d-1273-4a40-af51-b0d874c21150.png)
![Screenshot (431)_LI](https://user-images.githubusercontent.com/68113057/132574850-267f6e1b-a3d1-4106-bf8e-e5a40c4f77a1.jpg)

### Category:
- [X] MCAD (SolidWorks)
### Type:
- [X] Bug
### Applicable End Item:        
- [X] Lower Instrument Panel (LIP)

### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
@Lazarus94 Can you define as to what "slightly askew" specifically means so I can further evaluate this issue?

**Comment by jrsteensen** [comment]
@Lazarus94 Not to come off as a broken record, but can you be more specific? Some pictures, measurements, etc? Three mounting points should restrain all degrees of freedom.

**Comment by Lazarus94** [comment]
@jrsteensen Not at all. Sorry was on mobile.

Whilst having 3 mounting points does fully secure it there are two on the left side (front facing) and two on the right. The right sides mounting point is at the bottom corner which leaves the top right corner loose. The print is flexible to a degree and the pressure from the other mounting points seems to push it out a bit. See the images below. Its hard to tell in the photos but the Pedestal is at an angle. 

![IMG-6923](https://user-images.githubusercontent.com/68113057/134185722-00d7db3e-bfa5-4dab-9d72-4a604f892897.jpg)
![IMG-6927](https://user-images.githubusercontent.com/68113057/134185734-8dcce0d8-2e0f-4c11-bf4e-e176f7455b25.jpg)
![IMG-6926](https://user-images.githubusercontent.com/68113057/134185739-17a8475c-8d9a-49a2-8bc6-94cb5029574a.jpg)
![IMG-6925](https://user-images.githubusercontent.com/68113057/134185743-87932c12-7655-45ea-aa91-8c8d0bda8ff0.jpg)

**Comment by russellmm** [comment]
Are you saying to move Screw at location #1? One thing I did was add the panels to Right/Left inboard footwell walls prior to installing those inboard footwell walls to the LIP structure. This ensured that the alignment of those 2 pieces was correct once screwed into the "upper instrument panel mount"

The only area I am see a little flex is at location #2 as that panel is allowed to float there. But that may simply be because I need to print that piece with more infill to make it stronger.

![20210921_090536](https://user-images.githubusercontent.com/35648773/134209260-a16aa3b4-37c7-4b71-a0dc-aa7c2800a880.jpg)

**Comment by Lazarus94** [comment]
@jrsteensen @russellmm I've just had another look and it was my error! I made a mistake when installing the Pedestal. Sorry about that I think the issue can be closed.

**Comment by jrsteensen** [comment]
Sounds good! Thanks for the update Laz!
