### ISSUE TITLE
Canopy Bracket Clearance

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#351]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
There is a lack of clearance for the two extra buttons on the Canopy Bracket. The fit is too tight for the buttons to go in without significant force.

### Expected Results/How It Should Work:
The buttons should slide in with some resistance but ultimately be fastened by the buttons' nut. 

### Screenshots:
![IMG-6916](https://user-images.githubusercontent.com/68113057/133933060-04e906b0-93c6-4151-9de8-8e6e9485c54c.jpg)
![IMG-6917](https://user-images.githubusercontent.com/68113057/133933066-f22bddc1-70cc-4b38-9a8c-45bf606d30ff.jpg)

### Category:
*Check one or more items.*
- [ X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
Canopy Bracket: Canopy Bracket
Button: PV2F24011 - SWITCH, PUSHBUTTON, FLAT, OFF-(ON)

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/133933434-74011a2c-eccd-4427-9ebc-1243ca77712d.png)
![image](https://user-images.githubusercontent.com/2449496/133933403-fa7f245c-8787-44e0-a0ae-e0bbaf1bf1ea.png)

This switch was at 16mm DIA hole, which was the bottom end of the tolerance. Bumped to 16.1 DIA hole, to bring it to nominal tolerance.

This switch does not have a anti-rotation feature, so it relies on being a low gap slip fit and will require some level of force to install.

Closed with commit 8bc7638.
