### ISSUE TITLE
UFC PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#36]
- [x] Requirements definition
- [x] Schematic completed
- [x] PCB routed
- [ ] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
UFC revB is complete

**Comment by jrsteensen** [comment]
UFC requires full manufacturing file creation.

**Comment by jrsteensen** [comment]
PR #73 addresses this. Closed.

**Comment by jrsteensen** [comment]
Whelp, MAX6953 IC is obsolete and end of life. Going to have to redesign - either find suitable new ICs to control option displays, or source new displays. Either way a major redesign is required.

**Comment by amanuense** [comment]
That's a bummer. Next week we launch my current project. I'm going to get
some free time once I finish documentation, trainings, and some plans. I'll
be able to make time to check that then.
It will be a good opportunity to work on my idea of the mezzanine and make
it modular

**Comment by jrsteensen** [comment]
Agreed to a degree! I've also working on the MCAD to allow for discrete LEDs so we can replicate the real displays a little more closely. Only trade off is we will likely have to have the LEDs done when fabbed via jlc or similar.

![image](https://user-images.githubusercontent.com/2449496/69504641-f4759b00-0ee1-11ea-87b1-8ca8008972c0.png)

![image](https://user-images.githubusercontent.com/2449496/69504649-035c4d80-0ee2-11ea-87ad-109d5551093c.png)

**Comment by jrsteensen** [comment]
Starting UFC 2.0. Will open new issue with new requirements.
