### ISSUE TITLE
Cockpit Decals

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#363]
Part Number | Nomeclature | Designed? | Integrated Into Model?
-- | -- | -- | --
OH3A3-9001 | DECAL, STICK GRIP |  ✅  | ✅
OH4A1-9001 | DECAL, GROUND POWER |  ✅  | ✅
OH5A1-9001 | DECAL, CANOPY |  ✅  | :white_large_square:
OH5A1-9002 | DECAL, FCS BIT |   ✅   | :white_large_square:
OH1A1-9001 | DECAL, TV LENS |   ✅   | ✅
OH4A1-9001 | DECAL, RH GRIP ASSY |   ✅   | ✅
OH4A1-9002 | DECAL, LH GRIP   ASSY |   ✅   | ✅

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/140768128-dca978f4-4016-4cc9-bffa-748c7d3afce8.png)
FCS Bit Placard Dims
@insurgus

**Comment by insurgus** [comment]
Stick decal OH3A3-9001 - DECAL, GRIP ASSY

**Comment by jrsteensen** [comment]
CLosed with referenced PR

**Comment by jrsteensen** [comment]
Need to leave this open until I put them in MCAD. Oops.

**Comment by jrsteensen** [comment]
Completed.
