### ISSUE TITLE
Add adjust bolts underneath Seat Arm and Manual levers in new seat design

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#366]
This may already be addressed as part of hte new seat design - but one thing that was a challenge with the prelrease seat was getting the levers sitting just right so the microswitches activated correctly.
Could we add a heat insert in the levers so a bolt can be installed to adjust the trigger point for the microswitch (which is what I think at least the real seat arm has).

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/135870315-49567d64-2621-4d38-9bd4-eeba4f3e3b94.png)
Micro switches are activated by mechanism now that feature a TON of adjustability. It shouldn't be a problem. Thanks for the heads up though!
