### ISSUE TITLE
Add Buttkicker power amplifier to console

### ISSUE THREAD

**Issue by L-Walker** [jrsteensen/OpenHornet#369]
### Summary:

- [ ] Obtain CAD model for Kenwood X502-1 power amplifier.
- [ ] Add Kenwood X502-1 power amplifier to one of the consoles.

Link to product page: https://www.kenwood.com/usa/car/excelon/x502-1/

Amplifier chosen as discussed due to its worldwide availability, 12V power in, ability to connect remote volume knob, and class D efficency.
## Images
![dbox62_01](https://user-images.githubusercontent.com/65761897/135940926-52d4101c-4178-4385-8ca0-9ea9177c8fe3.png)
![dbox63_01](https://user-images.githubusercontent.com/65761897/135940937-7fa1115e-143e-410b-a9ff-f77c254ee7cc.png)

<img width="766" alt="Screen Shot 2021-10-05 at 11 11 25 am" src="https://user-images.githubusercontent.com/65761897/135940950-7be4f31d-4327-4811-9981-3289e79a9728.png">

**Comment by jrsteensen** [comment]
@DG Can you add the info about the remote pot here?
@Ramjet Can you add your model here or PR it to the repo?

**Comment by jrsteensen** [comment]
@dnamaster2000 Can you add the info about the remote pot here?
@Ramjet64 Can you add your model here or PR it to the repo?

**Comment by jrsteensen** [comment]
Added amp to LIP, v33, located centerline, 4 inches from the back edge of the upper instrument panel mount (OH2A1A1-38). Installed with 4x 6-32 X 1.25 PHS, washer, and nylock nuts. Will need to drill clearance holes in UIP to clearance nuts on top side.

![image](https://user-images.githubusercontent.com/2449496/160431164-24c35545-9137-41f5-8abf-a934a26852dc.png)

**Comment by jrsteensen** [comment]
Closing with LIP v33 save.

**Comment by Ramjet64** [comment]
That looks great.
Will be able to assist again soon.

Dai
