### ISSUE TITLE
AP Button PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#37]
- [ ] Requirements definition
- [x] Schematic completed
- [x] PCB routed
- [x] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
ready for review

**Comment by balzreber** [comment]
Amanuense, cold you please do the review? If you are ready, I then create all the necessary manufacturing files. Thanks.

**Comment by jrsteensen** [comment]
@balzreber Review completed. Good to go!

**Comment by jrsteensen** [comment]
PRs #71 and #74 address this. Closed.
