### ISSUE TITLE
Swap pin 2 and 3 of Q1 on DDI/AMPCD Controller

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#372]
### Summary:
Swap pins 2 and 3 of Q1 on DDI/AMPCD controller. 

**Workaround:** If you already have the current version of the controller, just install the through hole MOSFET with existing pin 1 to pin 1, pin 2 of the MOSFET to pin 3, and pin 3 of the MOSFET to pin 2 of the PCB.

**Comment by jrsteensen** [comment]
Manufacturing files not updated. Will require manufacturing files before issue can be closed. (Gerber's, BOM, P&P file)

[JLCPCB Instructions 1](https://support.jlcpcb.com/article/149-how-to-generate-gerber-and-drill-files-in-kicad)
[JLCPCB Instructions 2](https://support.jlcpcb.com/article/84-how-to-generate-the-bom-and-centroid-file-from-kicad)

**Comment by L-Walker** [comment]
Solved in commit c860438

Changed - Layout of silkscreen items to optimize readability and aesthetics.
Added - OH Logo on front silkscreen
Added - New manufacturing files (Have been tested going into JLCPCB)
Removed - Old manufacturing files.
![ddi_ampcd_controller](https://user-images.githubusercontent.com/65761897/137625157-c25dffa6-1a59-4c9a-8b0b-bb226e6853bf.png)
![ddi_ampcd_controller 2](https://user-images.githubusercontent.com/65761897/137625158-98026da9-1aca-40d2-85ac-168d4b4e5db6.png)
