### ISSUE TITLE
Overtravel in Hook Lever Mechanism

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#376]
### Summary:
There is a "third position" with the hook lever likely due to over travel where the spring plunger (84835A14) skips over the top of the hook lever body.

### Expected Results/How It Should Work:
There should be only two positions for the hook.

### Screenshots:
![Screenshot (438)_LI](https://user-images.githubusercontent.com/68113057/137383947-5836f2ea-a7be-4ad1-913a-eb51ea8d7bfc.jpg)
The plunger is jumping over onto the yellow highlight.

See video - https://discord.com/channels/392833351238811648/648196206496972811/898289199516614729

### Category:
*Check one or more items.*
- [X ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by erikscott128** [comment]
Mechanical stop added to CAD model. Replaceable wear area still to-do. 
![image](https://user-images.githubusercontent.com/6752310/164131318-815352a0-6189-4bb6-98f9-46892b99fcf6.png)
