### ISSUE TITLE
Master Mode Button PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#38]
- [ ] Requirements definition
- [x] Schematic completed
- [x] PCB routed
- [x] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
ready for review

**Comment by balzreber** [comment]
Amanuense, cold you please do the review? If you are ready, I then create all the necessary manufacturing files. Thanks.

**Comment by jrsteensen** [comment]
@balzreber Review completed. Good to go!
