### ISSUE TITLE
Add following notes to ECS Panel Drawing

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#383]
1) Acceptable alternate switch for PTH902-030F-103B2:
  - PTH902-030F-203B2

2) How to make the ECS Bleed Air a Continuous Rotation 4-pos switch:
  - A12405RNZQ Switch
  0) Add a stripe between switch halves with a paint marker or torque stripe compound to establish a rotational index of the halves of the switch.
  1) Pry 4 tabs apart gently with a flat head screwdriver. (Gently locking the switch in a vice by its shaft may prove helpful.)
  2) There are two spring loaded ball bearings inside that may launch out when opened. Gently remove the cover now.
  3) As shown in the picture, there are two tabs that interface with each other to form a stop.
  4) Grind the tab off the shaft side with a small file.
  5) Carefully reassemble switch.

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/138102218-ce4c255c-1ae9-47b2-b9c6-d56bbcac4886.png)

**Comment by Ben-F111** [comment]
During re assem, install 1 ball then the spring in the upper portion, then align the upper portion with the vacant side with the ball tunnel, whilst holding both sections slightly ajar, re install the second ball down the ball shoot. firmly closing the switch upper portion with the housing once installed, you may need a small flat tool to assist, ie a hex driver

![image](https://user-images.githubusercontent.com/67782885/187584159-7255ae86-9137-4397-813f-c591f276bb63.png)

**Comment by jrsteensen** [comment]
Added note to issue #549
