### ISSUE TITLE
ECS Panel Backplate

### ISSUE THREAD

**Issue by L-Walker** [jrsteensen/OpenHornet#388]
ECS Panel needs the backlighting holes added in the backplate again.

Seems to have disappeared

Attached is the illustrator manufacturing file for it that shows it did exist at one point.
[ECS Panel Backplate.AI.zip](https://github.com/jrsteensen/OpenHornet/files/7414312/ECS.Panel.Backplate.AI.zip)

**Comment by erikscott128** [comment]
ECS Panel has been swiss-cheesed. Some LEDS need repositioning to provide sufficient clearance from countersunk holes: 
![leds](https://user-images.githubusercontent.com/6752310/162559065-bf2d002a-1f4f-4092-b80f-43d0e752d15d.png)

**Comment by jrsteensen** [comment]
This change should be incorporated at the same time as #425 to the backlighting PCB @L-Walker

**Comment by jrsteensen** [comment]
Fixed in ECS v21
