### ISSUE TITLE
IFEI PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#39]
- [ ] Requirements definition
- [x] Schematic completed
- [x] PCB routed
- [ ] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
PCB is completed, schematic looks incorrect need to fix.

**Comment by amanuense** [comment]
revisited schematic, it is correct.

**Comment by jrsteensen** [comment]
IFEI has new schematic, routing, and reviewed. @balzreber Ready for manufacturing files.

**Comment by jrsteensen** [comment]
Closed with PR #81
