### ISSUE TITLE
.55 SQ Indicator PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#40]
- [ ] Requirements definition
- [x] Schematic completed
- [x] PCB routed
- [ ] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
PCB ready for review

**Comment by jrsteensen** [comment]
Closed this with PR #76
