### ISSUE TITLE
add tolorence to left aux panel for select jett panel backlight pcb

### ISSUE THREAD

**Issue by russellmm** [jrsteensen/OpenHornet#402]
### Summary:
I noticed that after I printed the Left AUX Panel, I was unable to seat the select jett panel backlight pcb into the cutout of the panel

### Expected Results/How It Should Work:
I expected to be able to seat the select jett panel backlight PCB into the recessed area of the left AUX Panel 

### Actual Results/How It Does Work:
the recessed area was too tight (especially after using filler/paint) to fit the backlight panel. I suspect that if this was CNC'd that it would actually fit since you would not be using as much filler paint. But I see no downside to adding a little tolorence to the recess area so that it sits in that area regardless of how you create the Aux Panel (CNC or 3D Print).

### Screenshots:
![2021-11-03 09_18_58-eDrawings](https://user-images.githubusercontent.com/35648773/140101014-7092ba5e-b3a9-4c4d-b4ba-fc25f75f3185.jpg)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
"left aux panel.sldprt"

**Comment by jrsteensen** [comment]
Closed in referenced commit.
