### ISSUE TITLE
DDI/AMPCD Arduino Shield

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#41]
- [ ] Requirements definition
- [x] Schematic completed
- [x] PCB routed
- [x] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
found we are missing a pullup for the IRQ line. we are also missing bypass caps for the ICs

**Comment by amanuense** [comment]
missing rotaty switch, created issue #52 to track this separately

**Comment by jrsteensen** [comment]
> found we are missing a pullup for the IRQ line. we are also missing bypass caps for the ICs

This references the DDI and AMPCD bezel (#32, #33) not this issue.

**Comment by jrsteensen** [comment]
> missing rotary switch, created issue #52 to track this separately

TODO for this PCB:

- [ ] Remove 1x POT connector
- [ ] Add 4 pin connector for DDI rotary (3 DI + GND)
- [ ] Add 2x 3 pin connector (2 DDI + GND) for AMPCD HDG/CRS toggles
- [ ] Fix i2c addressing.

**Comment by jrsteensen** [comment]
Bug fixed with PRs #54 and #55. Ready for review, Gerber generation, and MCAD generation.

**Comment by jrsteensen** [comment]
Completed in PR #64.
