### ISSUE TITLE
HUD Panel Backlighting MCAD Model Update Required

### ISSUE THREAD

**Issue by L-Walker** [jrsteensen/OpenHornet#413]
Updated positions of the LEDs around pot positions, to allow pot mounting nut to clamp onto the PCB without crushing the corner of an LED.

The Kicad file has been updated, but a matching STEP file needs to be exported and imported into the SW assembly.

**Comment by jrsteensen** [comment]
Fixed in UIP v56.

**Comment by jrsteensen** [comment]
Also, backplate received some additional swiss cheese adjustment in the above version.
