### ISSUE TITLE
Add collar to AMPCD buttons to reduce wobble.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#419]
![image](https://user-images.githubusercontent.com/2449496/144755690-f7e065fc-bf64-4a2c-8974-cc2780b7a138.png)

Also, correct insert interference with switch LED.

**Comment by Ben-F111** [comment]
I am also noting the insert is clashing with the LED, thus not allowing the button to be pressed down all the way, have you also noted this

**Comment by Ben-F111** [comment]
![20F062DF-93C7-4CB1-8FDE-8A70B8D4571A](https://user-images.githubusercontent.com/67782885/145898519-f6d5cd39-8b81-486b-81b2-d4e45b6634ea.jpeg)

best pic I could get

**Comment by jrsteensen** [comment]
Added small indexing features to button and reduced internal height of insert to resolve issue. Saved in OH2A3A1-1 v7.
