### ISSUE TITLE
Caution Lights PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#42]
- [ ] Requirements definition
- [ ] Schematic completed
- [ ] PCB routed
- [ ] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
created branch to cleanup the caution lights project folder.

**Comment by jrsteensen** [comment]
Closed in PR #82
