### ISSUE TITLE
Addition Support for RWR Control PCB

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#421]
### Summary:
The RWR PCB needs additional support  near the BIT FAIL button as the PCB excessively flexes when the button is pressed.  Or as a workaround add support material at the rear of the PCB (as per photo)

### Expected Results/How It Should Work:
Add a extension to the PCB along with a new heat nut in the MCAD above the DISP TYPE switch

### Screenshots:
![IMG_5251](https://user-images.githubusercontent.com/16440158/147374470-5be13158-9bc5-45ce-a674-6a36a814eb46.JPG)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [X ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by jrsteensen** [comment]
@celemourn, this one is all yours!

**Comment by jrsteensen** [comment]
Added .125 THK Support Plate behind PCB and increased PCB mounting HW length to compensate. Fixed in RWR Control ASSY v4.
