### ISSUE TITLE
Add additional support for Bleed Air Shaft

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#422]
### Summary:
In the current build of the ECS bleed air mechanism the gears occasionally bind which appears to be caused by the shaft not holding true.  Add support at the rear of the assmembly to hold shaft true

### Expected Results/How It Should Work:
Add rear support which is fractionally larger than the shaft.  As per the attached step file

### Actual Results/How It Does Work:
With the shaft no longer wobblying the gears no longer jam - have built and tested

### Screenshots:
![Screen Shot 2022-01-06 at 6 05 31 am](https://user-images.githubusercontent.com/16440158/148281866-32be94f0-eb5b-4858-914d-df53a7898494.png)

### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

### Associated Filename(s):
Bleed Air Mechanism Mount.sldprt

**Comment by bnepethomas** [comment]
I've got the step file if it is of interest to get the measurements

**Comment by jrsteensen** [comment]
@bnepethomas Can you attach the step file to this issue please?

**Comment by jrsteensen** [comment]
Completed by @erikscott128
