### ISSUE TITLE
COMM Panel Knob change (VOX)

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#424]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
the VOX Knob on the COMM Panel is shown as a KORRY RD239, but research shows it should be a TS3750, as per the ones on the HUD Panel

### Expected Results/How It Should Work:
Change knob to TS3750,

### Actual Results/How It Does Work:
Change knob to TS3750,

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
![image](https://user-images.githubusercontent.com/67782885/156449741-a584b701-e77d-4503-a63d-2847c0fc359d.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
COMM Panel

**Comment by jrsteensen** [comment]
Verified across multiple sources and this change will need to happen. Thanks @Ben-F111!

**Comment by Ben-F111** [comment]
![055A24C4-D538-4727-AC06-31D7015D395A](https://user-images.githubusercontent.com/67782885/156683385-f81e15f8-8a83-49bc-9aed-40b786f9b3d0.jpeg)

looks the part in the Pit. Thanks John.

**Comment by Lazarus94** [comment]
Fixed in V5 of Comm Panel (F360)

**Comment by jrsteensen** [comment]
Verified change, good work @Lazarus94!
