### ISSUE TITLE
Hitec HS-35HD for FCS Panel Obsolete

### ISSUE THREAD

**Issue by erikscott128** [jrsteensen/OpenHornet#426]
### Summary:
The servo HS-35HD by Hitec is obsolete. Need to identify and integrate a new servo. 

### Expected Results/How It Should Work:
Need to identify and design for a new servo that is easily available. This may work: https://www.sparkfun.com/products/18285

### Actual Results/How It Does Work:
Product is obsolete: https://www.sparkfun.com/products/retired/11882

### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Duplicate issue of #189 . WIll add you as assignee on 189. - we need to evaluate the FCS panel and Rudder Trim Knob.
