### ISSUE TITLE
RWR Control Panel PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#43]
- [x] Requirements definition
- [x] Schematic completed
- [ ] PCB routed
- [ ] Schematic/PCB reviewed
- [x] BOM generated
- [x] Gerbers generated
- [x] MCAD generated

**Comment by amanuense** [comment]
PCB needs work. looks started but never finished.

**Comment by jrsteensen** [comment]
Replace footprint for MAX487 with Housings_SOIC:SOIC-8+3.9x4.9mm_Pitch1.27mm. (Wrong footprint as is.)

**Comment by jrsteensen** [comment]
@balzreber This is ready for manufacturing files.

**Comment by jrsteensen** [comment]
Closed with PR #91
