### ISSUE TITLE
Left Lower Instrument Panel Printability Concerns

### ISSUE THREAD

**Issue by erikscott128** [jrsteensen/OpenHornet#434]
### Summary:
Left lower instrument panel has some printability issues that could be resolved

### Expected Results/How It Should Work:
Left lower instrument panel should be printable without excessive use of support material

### Actual Results/How It Does Work:
Significant overhangs make printing difficult. Recommend separating these flanges into separate pieces that are screwed in, similar to what is done on the right side. 

### Screenshots:
![image](https://user-images.githubusercontent.com/6752310/164874624-e1d47aa0-339c-489f-96a8-ee595dadc1e6.png)
Highlighted faces show the overhangs that should be separated

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH2A2A1-10

**Comment by Ben-F111** [comment]
On our pit. These have been replaced with screw on supports. After screen is installed.

**Comment by erikscott128** [comment]
@Ben-F111 Can you provide pictures of your solution?

**Comment by jrsteensen** [comment]
Agreed. Can you implement it @erikscott128?

**Comment by erikscott128** [comment]
Complete: 
![image](https://user-images.githubusercontent.com/6752310/179380704-88bc4e6c-a916-4a2e-b4f1-85ab6992babd.png)
