### ISSUE TITLE
Rudder Gantry not properly secured.  Missing Nuts to secure bolts & 4x bolts too short

### ISSUE THREAD

**Issue by Exprezz0** [jrsteensen/OpenHornet#435]
### Summary:
8x-_Part No.: 92316A536_ missing nuts to secure the gantry brackets together assuming the brackets aren't meant to be tapped.  4x of the bolts (located on top) don't protrude through the bracket far enough to attach nuts.

### Expected Results/How It Should Work:
The 8x bolts securing the gantry brackets and rudder pedals are .500inch long.  Recommend replacing with _Part No.: 91251A540 - SHCS, .25-20 X .750, STEEL, BLK_ and a washer **OR** _Part No.: 91309A542 - HHCS, .25-20 X 1.00, STEEL, ZINC_ and _Part No.: 95615A120 - NYLOC NUT, .25-20, GR5, STEEL_

All parts are already located in COTS and don't require the need to add additional pieces.

### Screenshots:
![image](https://user-images.githubusercontent.com/81926396/167584622-be4e5896-119c-4f44-9c07-71e67361accc.png)
![image](https://user-images.githubusercontent.com/81926396/167584734-8dcdc38a-4d62-440f-b012-53c131f291d9.png)
![image](https://user-images.githubusercontent.com/81926396/167584811-bab8c60c-8767-4e49-b446-8ee01ac105a5.png)

### Category:
*Check one or more items.*
- [X] MCAD (F360)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ ] Feature Enhancement
- [X] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH2A1-1 - ASSY, LOWER INSTRUMENT PANEL

**Comment by jrsteensen** [comment]
Design intent was to tap the holes, but a floating bolted joint may be preferable.

**Comment by jrsteensen** [comment]
Changed to bolted interface in assy, rudder pedals v5
