### ISSUE TITLE
Position file errors for the Standby Altimeter PCB during Manufacturing.

### ISSUE THREAD

**Issue by aegis53** [jrsteensen/OpenHornet#437]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
I submitted the Standby Altimeter Gerber zip file to [JLCPCB.com](https://jlcpcb.com/)
for manufacture, upon reviewing the component placement prior to submission I noticed that R2 and R3 were not placed 
correctly on their respective pad positions. All other components were correctly placed.

The components were approx. 3-5 mm to the left of where I thought they should be, but clearly not located on the pad position.
This looked strange so I had the PCB reviewed prior to manufacture, when the PCB came back after this review R2,R3 were correctly
placed. See attached screen shot.

### Expected Results/How It Should Work:
R2 and R3 should be correctly placed over the PCB pads 

### Actual Results/How It Does Work:
n/a

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.

![Standby Altimeter](https://user-images.githubusercontent.com/108637227/177120918-16c77641-2910-4913-a9bb-6c6bd04c528c.JPG)

## More Information
*Add an "X" in the square 
brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ ] Feature Enhancement
- [x] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
- [ ] 
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

\\GitHub\OpenHornet\ECAD\PCBs\OH_Specific\Functional\standby_altimeter\manufacturing\gerbers.zip

Regards B

**Comment by Ben-F111** [comment]
Noted on the latest revision, no issues and proved working, no clash either with any componants, 

PCB By JLPCB


![IMG_2478](https://user-images.githubusercontent.com/67782885/197621876-76a66e7c-5683-4079-b576-52e8d1564940.jpg)
![IMG_2392](https://user-images.githubusercontent.com/67782885/197621884-1abb2b32-9ccd-4521-bcbd-114c31f604f0.JPG)

**Comment by Exprezz0** [comment]
Fixed with #592.
