### ISSUE TITLE
Assembly of Standby Altimeter Vid29 Stepper and J1 Header Pin

### ISSUE THREAD

**Issue by aegis53** [jrsteensen/OpenHornet#438]
### Summary:
When assembling the Standby Altimeter PCB there is an issue between the placement/soldering of the J1 Header Pins and the Stepper, if the Stepper is mounted first on the PCB it is not possible to then solder J1 headers in position as based on the current PCB stencil and footprint both parts overlap each other. Referring to the previous Solidworks Assembly files the Stepper appears to be mounted flush with the PCB, this being the case the only option would be to solder J1 first, then trim the pins flush with the board, then solder the stepper to the board. Otherwise the alternate work around is not to mount the stepper flush with the board but raise it slightly (2-3mm) which is possible.

### Expected Results/How It Should Work:
The J1 Header pins should not interfere with the placement and positioning of the stepper.

### Actual Results/How It Does Work:
Looking at the picture (2) attached screen shots you will see that on the PCB stencil Picture (2) that the foot prints/outlines for both parts on the PCB overlap. Picture (1) from Solidworks the pins clearly interfere with the stepper. Picture 3 shows another view from the front of the board.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*

![Standby Altimeter clearance](https://user-images.githubusercontent.com/108637227/178225269-c7d5de72-e288-4e4f-ad28-44df6d9f8673.JPG)
![Standby Altimeter clearance - 3](https://user-images.githubusercontent.com/108637227/178225368-4f48e626-d3e5-4018-8c75-e2784c153584.JPG)

## More Information
![Standby Altimeter clearance - 2](https://user-images.githubusercontent.com/108637227/178225310-17f56adc-cb5c-4ac2-9266-2d4bbe7ce066.JPG)

*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Is trimming the back side of the pins flush with the surface an acceptable solution? (Because moving those drives more redesign work than just this PCB.)

**Comment by aegis53** [comment]
Hi John,

Three to four options as I see it,

1. Redesign of PCB, not practical at this time.
2. Trimming Header Pins after soldering as suggested, that was my first
thought as well. Fine by me, but could be tricky for some and there's a
small
chance of damaging the board.
3. Raise the Stepper motor off the board, it's possible as the coil pins
are of sufficient length to do this however they would then take all the
mechanical
strain holding the stepper to the pcb. Should not cause other issues, I
hope! but does move the stepper forward towards the front by the same
amount.

4. Modified (3) raise the stepper using 1-1.5 mm plastic strip just enough
to allow header pin clearance and the strip helps the stepper mount flush
to the board..... see attached photo I only had 2 mm strip, it's just a
little too much, so will go with 1-1.5mm it think.

This (4) is probably what I'll do to raise the stepper 1-1.5mm and it
should just be enough. I will advise how it goes after its built

Note the Airspeed/VVI PCB also has the same issue. Do you want me to raise
another issue for that?

Regards

Bryan

**Comment by aegis53** [comment]
Hi J,

THe last tweek is to push down on the Header pins slightly prior to
soldering so that the plastic carrier slides don a little and has them
just protruding from the PCB......

B

**Comment by aegis53** [comment]
Work Arounds as built and tested Raise the Stepper 1.5mm off the PCB using some Evergreen Strip super glued to the Stepper underside, allows adequate clearance for the stepper to clear the J1 Header pins, I also pushed down slightly on the Header
plastic carrier to reduce their height once protruding through the PCB. See attached photos.
![Workaround 2](https://user-images.githubusercontent.com/108637227/179386285-a27d2ee3-7682-441d-9c21-c2d549147a34.jpg)
![Workaround 1](https://user-images.githubusercontent.com/108637227/179386287-0dab81cd-2670-4945-aa2b-59198134daed.jpg)
![Workaround 3](https://user-images.githubusercontent.com/108637227/179386289-6a57903b-dcf5-48cd-967b-377b491f920f.jpg)

**Comment by aegis53** [comment]
Additional Build Notes. 
1. Raising the stepper reduces the clearance for the Zero Detect Wheel.
2. OLED modules need additional support as they don't fit firmly into the headers and this forms a pivot point on one end, they move freely and would likely interfere with Zero detect wheel. See Video.
3. Will continue build, may require longer spacers to increase height/clearance, however this will probably also mean having to increase OLED Header height using over length header pins.


https://user-images.githubusercontent.com/108637227/181904242-4a416afa-5544-4a30-9448-b36838cc4b54.mp4

**Comment by jrsteensen** [comment]
What about just some double sided tape or hot glue on the VID to support the OLEDs? May be the cheapest/easiest/most expedient solution to support the OLEDs fully.

**Comment by jrsteensen** [comment]
You have the wheel right there so that wouldn't work. Let me think on it.

**Comment by jrsteensen** [comment]
Adjusted connector position, reversed NeoPixel Pinout. Will have to support OLEDS with hot glue from the front, trim glue flat on back so as to not interfere with Zero wheel. Closed with standby instrument module v6 and commit 95c0459.
