### ISSUE TITLE
JETT Select PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#44]
- [x] Requirements definition
- [x] Schematic completed
- [ ] PCB routed
- [ ] Schematic/PCB reviewed
- [ ] BOM generated
- [ ] Gerbers generated
- [ ] MCAD generated

**Comment by amanuense** [comment]
file appears corrupted.

**Comment by jrsteensen** [comment]
File not corrupted, schematic may need further evaulatuion.

**Comment by jrsteensen** [comment]
Complete reeval required. PCB file is based on RWR and wrong, schematic requires analysis. Not ready for manufacture.

**Comment by jrsteensen** [comment]
0b05959 - Schematic added in ECAD_JETT_SELECT_PCB branch. Schematic ready for review.

**Comment by amanuense** [comment]
wilco

**Comment by jrsteensen** [comment]
@balzreber Just need manufacturing files and we will be golden.

**Comment by balzreber** [comment]
Will do!

**Comment by jrsteensen** [comment]
Closed with #142
