### ISSUE TITLE
Schematics Using 1938 Neopixel/RGB LED's show Incorrect Pin Outs/Labelling

### ISSUE THREAD

**Issue by aegis53** [jrsteensen/OpenHornet#445]
### Summary:
KiCAD Schematic drawings such as Standby Altimeter and Airspeed/VVI show the following pinouts for the 1938 Neopixel LED's
Pin 1 - DATA_OUT
Pin 2 - VSS/GND
Pin 3 - VDD +5V
Pin 4 - DATA_IN
See PCB Snip.
![Standby Alt Schematic Snip](https://user-images.githubusercontent.com/108637227/179699471-f77bcc22-8214-4d8f-b543-81a6f2c21e1a.JPG)
and 
[Standby Altimeter.pdf](https://github.com/jrsteensen/OpenHornet/files/9139093/Standby.Altimeter.pdf)

### Expected Results/How It Should Work:
This would appear to be opposite from the picture shown at the following link
https://core-electronics.com.au/neopixel-diffused-5mm-through-hole-led-5-pack.html  for ADA-1938 Neopixel LED.
If you assume Pin 1 is on the Left side of the picture then all PINS have been transposed, most importantly Power and Ground.

I have not found an actual data sheet for the 1938, even the following link on DigiKey is incorrect, it shows the correct LED but
the "Datasheet" link takes you to a WS2812 Surface Mounted LED.
https://www.digikey.com.au/en/products/detail/adafruit-industries-llc/1938/6827082?s=N4IgTCBcDaIIwE4DMAOEBdAvkA

Searching for compatible LEDS reveals the APA106 as an alternate. The Pinouts for this device which were tested on an Arduino
are as follows: See Datasheet snip.
![APA106](https://user-images.githubusercontent.com/108637227/179701857-25dec515-ff45-4bbf-b040-72d26e78e3e8.JPG)

Pin 1 - DATA_IN
Pin 2 - +5V/VDD
Pin 3 - VSS/GND
Pin 4 - DATA_OUT
 

### Actual Results/How It Does Work:
This would make the PCB drawing incorrect, especially in the context of a Multisided PCB, as the orientation flips when looking from
the other side. 

1. The drawing needs to be corrected, probably the KiCad symbol object has the wrong pinouts.
2. As this is a stand alone Lighting circuit on the PCB it is a simple matter resolve during soldering. (If you make it yourself.)
On a PCB the Square Symbol on a device represents Pin 1. however based on the wiring it's opposite. 

See Standby Altimeter PCB.  If looking from the other side the pins are now in reverse, this should work as its a stand alone circuit on the board. If the LED is mounted as such the wiring through to J1 becomes correct despite Pin 4 or the LED being soldered to Pin1 on the PCB track.
J13 - Is correct as DATA_IN and (RED)
J1 - is correct as DATA_OUT (YELLOW)
Most importantly this also transposes +5V and GND to the correct pins on the LED.

![Standby Alt 1938](https://user-images.githubusercontent.com/108637227/179708101-fe36100e-7f9c-46b4-a58c-0c57334e33b8.jpg)

### Screenshots:
See included Pictures

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
PCB SCH files for the Standby Altimeter and Airspeed/VVI use this 1938 LED,, I have not reviewed others but its possible more exist.

**Comment by jrsteensen** [comment]
Completed in all relevant PCBs.
