### ISSUE TITLE
ECM Button Holder needs Tabs

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#455]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
ECM Button Holder needs Tabs

### Expected Results/How It Should Work:
The button for the ECM JETT requires a way of retaining the button housing 

### Actual Results/How It Does Work:
The current .55 housing does not allow for a retention method 

### Screenshots:
![image](https://user-images.githubusercontent.com/67782885/183195005-97de4b34-0c15-4088-8e7e-1168b05166b6.png)

![image](https://user-images.githubusercontent.com/67782885/183198018-0f7187f5-2c00-409c-8d18-b3bc08ffd16e.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH2A5A1-105 - .55 SQ INDICATOR BASE

**Comment by Ben-F111** [comment]
![92730F1F-FE7F-4B6F-9C51-B77904632772](https://user-images.githubusercontent.com/67782885/183200260-e44ecd25-bd0c-4303-b2b1-81314f8e50b7.jpeg)

completed unit


![BCF80250-542B-4572-BF26-CFB9C41198DD](https://user-images.githubusercontent.com/67782885/183200415-171e8647-efad-41b5-8391-a985a9cce2fb.jpeg)

**Comment by jrsteensen** [comment]
Fixed in ECM Panel v4
