### ISSUE TITLE
Add 2 Screw holes to KY58 Aft Legend and Light Plates

### ISSUE THREAD

**Issue by russellmm** [jrsteensen/OpenHornet#456]
When creating the KY58 panels, I noticed there was no screw holes to connect the Aft Legend and Light plates to the Backplate. I assume the intent is to weld/glue them but was curious if this was how the aircraft was done. In researching, I was able to find one image of the KY58 on Wikipedia at a Crypto muesum. 

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*

![KY-58_VINSON,_airborne_or_shipborne_-_National_Cryptologic_Museum_-_DSC08023](https://user-images.githubusercontent.com/35648773/183282355-a74a1273-3da0-4fca-9cd3-4f6ce71b597d.jpg)

https://en.wikipedia.org/wiki/KY-58#/media/File:KY-58_VINSON,_airborne_or_shipborne_-_National_Cryptologic_Museum_-_DSC08023.JPG

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by russellmm** [comment]
This link says its for battery install and they have a few images without the screws. So maybe its not really needed
http://www.jproc.ca/crypto/ky58.html

**Comment by Ben-F111** [comment]
Will
Send 
Pic
Later. But yes. Glue.
