### ISSUE TITLE
Landing Gear Pushbutton Switch Issue

### ISSUE THREAD

**Issue by Stang51** [jrsteensen/OpenHornet#462]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The Warning Tone Silence Pushbutton "Barrel" is too short - Not enough extension after passing through the Legend Plate. 

NOTE  -  The Legend Plate used in the Pictures is for testing purposes only

### Expected Results/How It Should Work:
The Warning Silence Pushbutton should extend through the Legend Plate by a minimum of .125"

### Actual Results/How It Does Work:
Currently with the "Original Solidworks Design", the Warning Silence Pushbutton extends through the Legend Plate by less that 0.0625".   This makes it very hard to actually press the button far enough in, so that the contacts in the switch touch.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
![978997AF-E124-40A9-86D2-513E94933F42](https://user-images.githubusercontent.com/57641429/184404337-8915269c-9803-46b8-b094-f3776fe03cf3.jpg)

![F6BF4A5A-0C25-4663-9AA6-900A46547B51](https://user-images.githubusercontent.com/57641429/184404403-103c0608-41fc-4f1a-bed5-ed4114270a52.jpg)

**Comment by jrsteensen** [comment]
This was addressed at a previous time. (Replaced with KM1101RR02QE switch)
Closing with no action required.

**Comment by jrsteensen** [comment]
I may have been a bit too hasty on closing this. Erik, can you look at this as part of #441?

**Comment by jrsteensen** [comment]
Nope, already addressed with change of switch and custom switch cap. Closing this with no action.
