### ISSUE TITLE
Make OpenHornet fully USB 3.0.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#466]
Decide if we want to make all hubs USB 3. Can be facilitated with minor wiring changes and no changes to bulkhead connections, just increases cabling and hub cost somewhat.

- [x] Replace USB 2.0 HUB in UIP
- [x] Replace USB 2.0 HUB in RC
- [x] Replace USB 2.0 HUB in LC
- [x] Update LC Interconnect
- [x] Update RC Interconnect
- [x] Update LIP Interconnect
- [x] Update RC>LIP Bulkhead with USB 3 Connector
- [x] Update LC>LIP Bulkhead with USB 3 Connector
- [x] Update LIP>LC Bulkhead with USB 3 Connector
- [x] Update LIP>RC Bulkhead with USB 3 Connector
- [x] Update UIP>LIP Bulkhead with USB 3 Connector

**Comment by russellmm** [comment]
Yes please. USB3 likely to be available longer than USB2

**Comment by jrsteensen** [comment]
Yeah, might as well future proof it. We will implement this.

- [ ] Replace USB 2.0 HUB in UIP
- [ ] Replace USB 2.0 HUB in RC
- [ ] Replace USB 2.0 HUB in LC
- [ ] Update LC Interconnect
- [ ] Update RC Interconnect
- [ ] Update LIP Interconnect
- [ ] Update RC>LIP Bulkhead with USB 3 Connector
- [ ] Update LC>LIP Bulkhead with USB 3 Connector
- [ ] Update LIP>LC Bulkhead with USB 3 Connector
- [ ] Update LIP>RC Bulkhead with USB 3 Connector
- [ ] Update UIP>LIP Bulkhead with USB 3 Connector
