### ISSUE TITLE
Mount all LIP components on left side.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#468]
Mount all hubs and other electronics into the left side of the LIP.

**Comment by jrsteensen** [comment]
@russelm If you just want to status track here, that would be great.

**Comment by russellmm** [comment]
All items Mounted but will need to think of a new design for the bottom of the PSU as the nuts hit. Will try to think of something that 3D prints well that also works in that tight space. Could just use the top bracket on the bottom as well if you think it would be strong enough

**Comment by russellmm** [comment]
Mounting completed of electronic bay items. Changed the holes/fasteners used per our discussion

**Comment by jrsteensen** [comment]
Completed with B1HWF Milestone of LIP.
