### ISSUE TITLE
VVI Bezel - currently single body

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#471]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
(VVI Bezel Printing)

### Expected Results/How It Should Work:
(Where posible its prefered to print 'display" parts Face down on the printer bed)

### Actual Results/How It Does Work:
(The new VVI Bezel is a single part with the ring protrusion attached to the body, this is not allowing the Bezel visible face(s) to be printed flat on the bed, thus providing a superior print finish with limited post processing, 

suggest the VVI Bezel and Ring are 2 independent Bodies (or 2 STLs in the final) that can be printed face down then glued prior to printing

Printing the Standby Gauge Bezels Face down also removes the needs for any support material )

### Screenshots:
I have split and will upload resulst later today

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by russellmm** [comment]
could just split it and a dab of glue and its good to go
![2022-08-30 14_09_58-Autodesk Fusion 360](https://user-images.githubusercontent.com/35648773/187544055-5f5c9e12-55b3-48f9-b10c-261632d7cb5f.jpg)

**Comment by Ben-F111** [comment]
yes, correct, noting there a some ppl that dont know how to do that, the request is to relased STL's to be split already 

I would split if from the top of the BEZEL face, as a smaller ring, not the entire section including the Dial Ring

Will have pics later today

**Comment by Ben-F111** [comment]
![1FA56671-083C-487A-ADFF-45ED15688B1F](https://user-images.githubusercontent.com/67782885/187612524-48aa8ac5-8dc5-4f4b-88f4-916a93e9f790.jpeg)

top Bezel printed as 2 parts. 
![Uploading 5FA960A2-1D56-4700-81C4-11C6A999D1A1.jpeg…]()

**Comment by Ben-F111** [comment]
![Uploading 661CC6F3-2DCB-4ADD-AFC3-E471071E525E.jpeg…]()

**Comment by jrsteensen** [comment]
![Image](https://user-images.githubusercontent.com/2449496/189495684-71fe86f2-cd9b-443b-9d60-a0d9d462c11e.png)
![Image](https://user-images.githubusercontent.com/2449496/189495691-24897c38-c355-49ce-b162-3402b25c9d7c.png)

Completed in VVI v7.

**Comment by russellmm** [comment]
looks great!
