### ISSUE TITLE
Fix Joints in LIP Assembly.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#474]
![Image](https://user-images.githubusercontent.com/2449496/189163507-7a5128e6-aaf3-4643-91eb-bcdd976ffb79.png)

![Image](https://user-images.githubusercontent.com/2449496/189163581-1b8cce57-65c7-406e-8c31-2f4eb2fea357.png)

![Image](https://user-images.githubusercontent.com/2449496/189163722-301c1485-12dd-414d-8b71-d6215502212e.png)

**Comment by russellmm** [comment]
I fixed the middle picture. I did not see the top picture or bottom picture issues

**Comment by jrsteensen** [comment]
Completed with B1HWF Milestone of LIP.
