### ISSUE TITLE
Redesign Rudder Trim Knob Mechanism

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#475]
Existing Rudder Trim Mechanism does not work. (Servo is underpowered.)

Evaluate Rudder Trim Knob Mechanism and redesign as appropriate.

**Comment by Ben-F111** [comment]
I can update to the servo I used. It works great. ?

**Comment by jrsteensen** [comment]
Yes please! I would rather do that for Beta1, and we can do a full redesign at a later time if required.

**Comment by Ben-F111** [comment]
Update F3D  and servo type provided to @jrsteensen for evaluation as used in my pit.

**Comment by jrsteensen** [comment]
Thanks for that @Ben-F111. @erikscott128 came up with a motorized pot (pot with an integrated DC motor) that I'm excited to try out. I archived all your stuff for future reference if required. 

FCS panel is completed, just waiting to close until I redesign the interfering APU ABSIS PCB mount in the console assy.

**Comment by jrsteensen** [comment]
Complete in LC v123. So so close! One more issue!
