### ISSUE TITLE
Create a Gerber Package File Standard

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#483]
Will be documented here: https://github.com/jrsteensen/OpenHornet/wiki/Build-Package-Requirements

**Comment by jrsteensen** [comment]
Will be included in PR #592

**Comment by Exprezz0** [comment]
Will be complete with ECAD merge:

![image](https://user-images.githubusercontent.com/81926396/228070849-d54ae965-3b90-418c-baea-bda476ab0795.png)

**Comment by Exprezz0** [comment]
Implemented in #592.   Update to standard:  There will only be **ONE** consolidated BOM per PCB and no longer two separate BOMs for TOP and BOTTOM layer components.
