### ISSUE TITLE
Create Drawing: OH1A6 - ASSY, PANEL, SPIN RECOVERY

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#496]
Create drawing OH1A6 - ASSY, PANEL, SPIN RECOVERY.

**Comment by jrsteensen** [comment]
IN CHECK

[OH1A6-1 - ASSY, PANEL, SPIN RECOVERY_-_v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11131139/OH1A6-1.-.ASSY.PANEL.SPIN.RECOVERY_-_v1.pdf)

**Comment by kbastronomics** [comment]
How does one attach the Spin Indicator,   that's not clear or I'm blind and am missing it

**Comment by jrsteensen** [comment]
No, valid catch - it gets bonded to the backplate. Unfortunately its too thin to be able to have a mounting boss easily attached, since the full clearance is required from the rear to insert the legend stack.

- [ ] Add note detailing bonding of SPIN indicator.

**Comment by jrsteensen** [comment]
Added bonding note

[OH1A6-1 - ASSY, PANEL, SPIN RECOVERY_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11131337/OH1A6-1.-.ASSY.PANEL.SPIN.RECOVERY_-_v2.pdf)

**Comment by jrsteensen** [comment]
Self-checked. Added to RC Release package and closed.
