### ISSUE TITLE
Create Drawing: OH1A7 - ASSY, PANEL, HUD

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#497]
Create drawing OH1A7 - ASSY, PANEL, HUD.

**Comment by jrsteensen** [comment]
ON HOLD - BL PCB interference issues with nuts and poorly placed LEDs.

**Comment by Exprezz0** [comment]
Drawing ready to be completed.  PCB and Fusion 360 Models have been updated per commit: cbd3a8d2b94fde9d1af5b288b04dab8aa95fb0d0

**Comment by jrsteensen** [comment]
MCAD Changes TODO for me:

- [ ] Reorganize panel from -100 to -1
- [ ] Move inserts to -10
- [ ] Evaluate BLK LVL and AOA knobs - not sure we should have the white circle visible.

**Comment by jrsteensen** [comment]
Drawing completed, self-checked and added to RC Release Package

[OH1A7-1 - ASSY, PANEL, HUD_-_v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11302319/OH1A7-1.-.ASSY.PANEL.HUD_-_v4.pdf)
