### ISSUE TITLE
Create Drawing: OH2A7A1 - ASSY, STANDBY INSTRUMENT MODULE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#509]
Create drawing OH2A7A1 - ASSY, STANDBY INSTRUMENT MODULE.

Add drawing note to every LCD screen in pit to ensure screen is installed in the proper orientation - the buy display LCDs appear to have a unilateral view angle and installation orientation is critical. 
- [ ] Use local note to indicate power connector position of LCD. "LCD Orientation Critical. Orient with power connector as shown."

**Comment by Ben-F111** [comment]
Build Note, Zero Sensor within the gauges

Add to the drawing
###Zero Sensor Tip Must be painted as per F360 - with at least 3 coats of Spray-paint. ###

the Photo Sensor we are finding is penetrating Resin Prints, heat shrink

Painting the tip will stop the beam

**Comment by jrsteensen** [comment]
IN CHECK

[OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE_-_v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11243043/OH2A1A1-1.-.ASSY.LOWER.INSTRUMENT.PANEL.STRUCTURE_-_v4.pdf)

**Comment by jrsteensen** [comment]
Uploaded wrong drawing.

[OH2A7A1-1 - ASSY, STANDBY INSTRUMENT MODULE_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11301657/OH2A7A1-1.-.ASSY.STANDBY.INSTRUMENT.MODULE_-_v2.pdf)

Self-Checked and added to RC Release Package
