### ISSUE TITLE
Create Drawing: OH4A1A1 - ASSY, LEFT CONSOLE STRUCTURE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#512]
Create drawing OH4A1A1 - ASSY, LEFT CONSOLE STRUCTURE.

- [ ] Add flag note to console drawings referencing rib interfacing printed parts. "Part printed to maximum material condition. Removal of .02" MAX material on MDF interfacing surfaces authorized."

**Comment by jrsteensen** [comment]
IN CHECK

[OH4A1A1-1 - ASSY, LEFT CONSOLE STRUCTURE v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11470722/OH4A1A1-1.-.ASSY.LEFT.CONSOLE.STRUCTURE.v5.pdf)

**Comment by jrsteensen** [comment]
Completed, added to RC package and closed.

**Comment by Exprezz0** [comment]
Removed Duplicate Hex Nut located on OH4A1A1-27 - AFT LEFT CONSOLE CANOPY RAIL BRAKET

![Image](https://github.com/jrsteensen/OpenHornet/assets/81926396/971fdd05-74bd-48a8-bc30-756908590738)
