### ISSUE TITLE
Create Drawing: OH4A3A2 - ASSY, PARK BRAKE HANDLE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#515]
Create drawing OH4A3A2 - ASSY, PARK BRAKE HANDLE.

**Comment by ajmilner85** [comment]
Reminder to add note to clip lower limit switch arm to avoid contacting End Cap.

**Comment by jrsteensen** [comment]
Minor geometry issues in model:

- [ ] Fix in main body
- [ ] Add threads to shaft.

![Image](https://user-images.githubusercontent.com/2449496/229372565-6cca8416-22f7-4fb7-b3ae-d4e2a727a5ef.png)

**Comment by jrsteensen** [comment]
IN CHECK

[OH4A3A2-1 - ASSY, PARK BRAKE HANDLE_-_v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11133124/OH4A3A2-1.-.ASSY.PARK.BRAKE.HANDLE_-_v1.pdf)

**Comment by jrsteensen** [comment]
Moved to RC Release Package and closing this one.
