### ISSUE TITLE
Create Drawing: OH4A3A3 - ASSY, BRAKE PRESS GAUGE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#516]
Create drawing OH4A3A3 - ASSY, BRAKE PRESS GAUGE.

**Comment by jrsteensen** [comment]
IN CHECK

[OH4A3A3-1 - ASSY, BRAKE PRESSURE INDICATOR_-_v3.pdf](https://github.com/jrsteensen/OpenHornet/files/9641088/OH4A3A3-1.-.ASSY.BRAKE.PRESSURE.INDICATOR_-_v3.pdf)

**Comment by jrsteensen** [comment]
[OH4A3A3-1 - ASSY, BRAKE PRESSURE INDICATOR_-_v5.pdf](https://github.com/jrsteensen/OpenHornet/files/9641135/OH4A3A3-1.-.ASSY.BRAKE.PRESSURE.INDICATOR_-_v5.pdf)

SLIGHTLY UPDATED

**Comment by Lazarus94** [comment]
IN CHECK

[OH4A3A3-1 - ASSY, BRAKE PRESSURE INDICATOR v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11129204/OH4A3A3-1.-.ASSY.BRAKE.PRESSURE.INDICATOR.v5.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
