### ISSUE TITLE
Create Drawing: OH4A4A1 - ASSY, FIRE TEST PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#517]
Create drawing OH4A4A1 - ASSY, FIRE TEST PANEL.

**Comment by russellmm** [comment]
You call out #10 bubbles twice. Probably not needed per discussion yesterday but it's nit picking :)

**Comment by jrsteensen** [comment]
This was a case that I thought it provided additional clarity by doing so, but the argument could be made either way.

**Comment by jrsteensen** [comment]
Completed with drawing v8
