### ISSUE TITLE
Create Drawing: OH4A4A2 - ASSY, EXTERNAL LT PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#518]
Create drawing OH4A4A2 - ASSY, EXTERNAL LT PANEL.

**Comment by Lazarus94** [comment]
IN CHECK

[OH4A4A2-1 - ASSY, EXTERNAL LT PANEL v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11129356/OH4A4A2-1.-.ASSY.EXTERNAL.LT.PANEL.v5.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK
![image](https://user-images.githubusercontent.com/2449496/229306434-1ed0d8ba-dfe3-4eea-8c3a-2213ed80e067.png)

**Comment by jrsteensen** [comment]
Backcheck comments incorporated and added to RC Release Package and closed.

[OH4A4A2-1 - ASSY, EXTERNAL LT PANEL_-_v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11132944/OH4A4A2-1.-.ASSY.EXTERNAL.LT.PANEL_-_v6.pdf)
