### ISSUE TITLE
DDI/AMPCD Shield Bezel Changes

### ISSUE THREAD

**Issue by amanuense** [jrsteensen/OpenHornet#52]
TODO for this PCB:

- [ ] Remove 1x POT connector
- [ ] Add 4 pin connector for DDI rotary (3 DI + GND)
- [ ] Add 2x 3 pin connector (2 DI + GND) for AMPCD HDG/CRS toggles
- [ ] Fix i2c addressing.

**Comment by jrsteensen** [comment]
i2c issue not on shield. i2c issue on AMPCD Button Board (#33).

**Comment by jrsteensen** [comment]
Issue resolved with #54 and #55.
