### ISSUE TITLE
Create Drawing: OH4A5A1 - ASSY, FUEL PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#520]
Create drawing OH4A5A1 - ASSY, FUEL PANEL.

**Comment by jrsteensen** [comment]
IN CHECK

[OH4A5A1-1 - ASSY, FUEL PANEL_-_v1.pdf](https://github.com/jrsteensen/OpenHornet/files/9641325/OH4A5A1-1.-.ASSY.FUEL.PANEL_-_v1.pdf)

**Comment by jrsteensen** [comment]
Added paint callout to -15 guard.

[OH4A5A1-1 - ASSY, FUEL PANEL_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/9641390/OH4A5A1-1.-.ASSY.FUEL.PANEL_-_v2.pdf)

**Comment by Lazarus94** [comment]
IN CHECK

[OH4A5A1-1 - ASSY, FUEL PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11129178/OH4A5A1-1.-.ASSY.FUEL.PANEL.v3.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
