### ISSUE TITLE
Create Drawing: OH4A5A2 - ASSY, APU/ENG CRANK PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#521]
Create drawing OH4A5A2 - ASSY, APU/ENG CRANK PANEL.

**Comment by jrsteensen** [comment]
IN CHECK

[OH4A5A2-1 - ASSY, APU ENG CRANK PANEL_-_v1.pdf](https://github.com/jrsteensen/OpenHornet/files/9641449/OH4A5A2-1.-.ASSY.APU.ENG.CRANK.PANEL_-_v1.pdf)

**Comment by jrsteensen** [comment]
ADDED MISSING PO NOTE

[OH4A5A2-1 - ASSY, APU ENG CRANK PANEL_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/9641454/OH4A5A2-1.-.ASSY.APU.ENG.CRANK.PANEL_-_v2.pdf)

**Comment by Lazarus94** [comment]
[OH4A5A2-1 - ASSY, APU ENG CRANK PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11129096/OH4A5A2-1.-.ASSY.APU.ENG.CRANK.PANEL.v3.pdf)

IN CHECK

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.

**Comment by jrsteensen** [comment]
Added to release package

[OH4A5A2-1 - ASSY, APU ENG CRANK PANEL_-_ v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11227220/OH4A5A2-1.-.ASSY.APU.ENG.CRANK.PANEL_-_.v6.pdf)
