### ISSUE TITLE
Create Drawing: OH4A7A2 - ASSY, OBOGS PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#524]
Create drawing OH4A7A2 - ASSY, OBOGS PANEL.

**Comment by Lazarus94** [comment]
Move to _In Progress_

**Comment by Lazarus94** [comment]
[OH4A7A2-1 - ASSY, OBOGS PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11123058/OH4A7A2-1.-.ASSY.OBOGS.PANEL.v3.pdf)

**Comment by Lazarus94** [comment]
[OH4A7A2-1 - ASSY, OBOGS PANEL v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11123496/OH4A7A2-1.-.ASSY.OBOGS.PANEL.v6.pdf)

Correction use this one. Added trail lines

**Comment by jrsteensen** [comment]
### Check Comments

- [ ] Add Resin Note to 2.3
- [ ] FN 17 not ballooned
- [ ] FN 20 not ballooned
- [ ] Add `INITIAL RELEASE` to rev history description field.

![image](https://user-images.githubusercontent.com/2449496/229175248-661d8aa9-ccd2-4d4f-a29a-1cae4f03dd3c.png)

**Comment by Lazarus94** [comment]
[OH4A7A2-1 - ASSY, OBOGS PANEL v7.pdf](https://github.com/jrsteensen/OpenHornet/files/11124341/OH4A7A2-1.-.ASSY.OBOGS.PANEL.v7.pdf)

IN BACKCHECK

**Comment by jrsteensen** [comment]
Saved to RC release package, and marked complete.
