### ISSUE TITLE
Create Drawing: OH4A7A4 - ASSY, ANT SEL PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#526]
Create drawing OH4A7A4 - ASSY, ANT SEL PANEL.

**Comment by jrsteensen** [comment]
IN CHECK

[OH4A7A4-1 - ASSY, ANT SEL PANEL_-_v1.pdf](https://github.com/jrsteensen/OpenHornet/files/9641509/OH4A7A4-1.-.ASSY.ANT.SEL.PANEL_-_v1.pdf)

**Comment by Lazarus94** [comment]
[OH4A7A4-1 - ASSY, ANT SEL PANEL v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11125257/OH4A7A4-1.-.ASSY.ANT.SEL.PANEL.v2.pdf)

IN CHECK

**Comment by jrsteensen** [comment]
Saved to RC Release Package and closed.

**Comment by Lazarus94** [comment]
Should be LC :)

**Comment by jrsteensen** [comment]
RC being release candidate, not right console in this context. :)

**Comment by Lazarus94** [comment]
Aaah whoops!
