### ISSUE TITLE
Create Drawing: OH4A8A1 - ASSY, LEFT CIRCUIT BREAKERS

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#527]
Create drawing OH4A8A1 - ASSY, LEFT CIRCUIT BREAKERS.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
[OH4A8A1-1 - ASSY, LEFT CIRCUIT BREAKERS v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11125173/OH4A8A1-1.-.ASSY.LEFT.CIRCUIT.BREAKERS.v2.pdf)

IN BACKCHECK

**Comment by jrsteensen** [comment]
IN BACKCHECK

[OH4A8A1-1 - ASSY, LEFT CIRCUIT BREAKERS_-_v2-CHK1.pdf](https://github.com/jrsteensen/OpenHornet/files/11125215/OH4A8A1-1.-.ASSY.LEFT.CIRCUIT.BREAKERS_-_v2-CHK1.pdf)

**Comment by Lazarus94** [comment]
[OH4A8A1-1 - ASSY, LEFT CIRCUIT BREAKERS Drawing v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11127001/OH4A8A1-1.-.ASSY.LEFT.CIRCUIT.BREAKERS.Drawing.v3.pdf)

**Comment by jrsteensen** [comment]
Good as-is. Added to RC release package and closed.
