### ISSUE TITLE
Create Drawing: OH4A8A3 - ASSY, NUC ENABLE SWITCH

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#529]
Create drawing OH4A8A3 - ASSY, NUC ENABLE SWITCH.

**Comment by Lazarus94** [comment]
[OH4A8A3-1_-_ASSY_NUC_WEAP_SWITCH_Drawing_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11093011/OH4A8A3-1_-_ASSY_NUC_WEAP_SWITCH_Drawing_v2.pdf)

Questions:

1 Is Rowmark included as a flat part?
2. What is meant by REV?
3.  Did I explode the model correctly or should I have done it differently?

**Comment by Exprezz0** [comment]
I noticed the placard, too.  Says rowmark, so you'd think it would be like the rest of the panels, but the model shows it as a sticker/printed as part of the PETG.  Same thing as the L/R circuit breaker boxes

REV = Revision.

If you can move the placard (which I don't remember if you can or not), then I'd separate it from the box a little more.

**Comment by jrsteensen** [comment]
IN BACKCHECK

[OH4A8A3-1_-_ASSY_NUC_WEAP_SWITCH_-_v2-CHK1.pdf](https://github.com/jrsteensen/OpenHornet/files/11095258/OH4A8A3-1_-_ASSY_NUC_WEAP_SWITCH_-_v2-CHK1.pdf)

**Comment by jrsteensen** [comment]
Use this one, missed one little thing (The "LEFT CONSOLE" in the title block)

[OH4A8A3-1_-_ASSY_NUC_WEAP_SWITCH_-_v2-CHK2.pdf](https://github.com/jrsteensen/OpenHornet/files/11095323/OH4A8A3-1_-_ASSY_NUC_WEAP_SWITCH_-_v2-CHK2.pdf)

**Comment by Lazarus94** [comment]
Thanks John, that helps a lot. I’ll send the corrected version this afternoon.

**Comment by Lazarus94** [comment]
[OH4A3A1-1.-.ASSY.SELECT.JETT.PANEL_-_v5-CHK1.pdf](https://github.com/jrsteensen/OpenHornet/files/11114280/OH4A3A1-1.-.ASSY.SELECT.JETT.PANEL_-_v5-CHK1.pdf)

**Comment by Lazarus94** [comment]
[OH4A8A3-1 - ASSY, NUC WEAP SWITCH Drawing v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11115067/OH4A8A3-1.-.ASSY.NUC.WEAP.SWITCH.Drawing.v5.pdf)

**Comment by jrsteensen** [comment]
Just as a minor note: Drop the word "Drawing" from the PDF. The PDFs should be named per the redlines in -CHK2. `<DWG #> - <DWG TITLE>_<REV>_v<VER>.pdf`

Thanks Laz! Saved to the release candidate package.
