### ISSUE TITLE
Create Drawing: OH10A1A1 - ASSY, SIM PWR PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#530]
Create drawing OH10A1A1 - ASSY, SIM PWR PANEL.

**Comment by Lazarus94** [comment]
Move to _In Progress_

**Comment by Lazarus94** [comment]
[OH10A1A1-1 - ASSY, SIM PWR PANEL v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11123492/OH10A1A1-1.-.ASSY.SIM.PWR.PANEL.v4.pdf)

**Comment by Lazarus94** [comment]
[OH10A1A1-1 - ASSY, SIM PWR PANEL v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11123681/OH10A1A1-1.-.ASSY.SIM.PWR.PANEL.v6.pdf)

Done. Thank you.

**Comment by jrsteensen** [comment]
We are entering the realm of nitpicky, but:

![image](https://user-images.githubusercontent.com/2449496/229170626-9dec90b6-9da6-4d13-809a-8f281db19dd0.png)

**Comment by Lazarus94** [comment]
[OH10A1A1-1 - ASSY, SIM PWR PANEL v7.pdf](https://github.com/jrsteensen/OpenHornet/files/11124283/OH10A1A1-1.-.ASSY.SIM.PWR.PANEL.v7.pdf)

IN BACKCHECK

**Comment by jrsteensen** [comment]
Drawing completed and added to RC release package. Great work, thank you!
