### ISSUE TITLE
Create Drawing: OH2A1A1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#539]
Create drawing OH2A1A1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE.

- [ ] Add flag note to console drawings referencing rib interfacing printed parts. "Part printed to maximum material condition. Removal of .02" MAX material on MDF interfacing surfaces authorized."

**Comment by Ben-F111** [comment]
Build Note, Zero Sensor 

Add to the drawing
###Zero Sensor Tip Must be painted as per F360 - with at least 3 coats of Spray-paint. ###


the Photo Sensor we are finding is penatraiting Resin Prints, heat shrink

Painting the tip will stop the beam

**Comment by jrsteensen** [comment]
IN CHECK

[OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11128238/OH2A1A1-1.-.ASSY.LOWER.INSTRUMENT.PANEL.STRUCTURE_-_v2.pdf)

**Comment by jrsteensen** [comment]
Updated to latest structure with mods to facilitate future mechanical SARI and new discrete screen based solutions for RWR and SARI.

[OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE_-_v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11242935/OH2A1A1-1.-.ASSY.LOWER.INSTRUMENT.PANEL.STRUCTURE_-_v4.pdf)

**Comment by jrsteensen** [comment]
Self-Checked and added to RC Release Package

[OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE_-_v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11301670/OH2A1A1-1.-.ASSY.LOWER.INSTRUMENT.PANEL.STRUCTURE_-_v6.pdf)
