### ISSUE TITLE
Create Drawing: OH5A2A3 - ASSY, AV COOL SWITCH

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#544]
Create drawing OH5A2A3 - ASSY, AV COOL SWITCH.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK 



[OH5A2A3-1 - ASSY, AV COOL SWITCH v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11220557/OH5A2A3-1.-.ASSY.AV.COOL.SWITCH.v2.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.

**Comment by Exprezz0** [comment]
Will need to be rechecked after I update PCB based on #625 and #594.  I'll update this once I finished fixing the PCB and F360 panels

**Comment by jrsteensen** [comment]
Updated:

1. Latest PCB
2. Changed SxAL switch PN to correct OHC PN
3. Fixed title block error.

[OH5A2A3-1 - ASSY, AV COOL SWITCH_-_v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11301621/OH5A2A3-1.-.ASSY.AV.COOL.SWITCH_-_v5.pdf)

Added to RC Release Package.
