### ISSUE TITLE
Create Drawing: OH5A2A4 - ASSY, RADAR ALTIMETER GAUGE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#545]
Create drawing OH5A2A4 - ASSY, RADAR ALTIMETER GAUGE.

- [ ] Add note to drawing to trim leads of NeoPixel/BL LEDs, and solder them with jumper wires to PCB. Do not direct mount them to the PCB: 

![Image](https://user-images.githubusercontent.com/2449496/227736153-05da1bcf-2fb5-4558-b03d-cd6c0f815106.png)

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK

I will fix the trail lines on Sheet 1 just want to make sure everything else is fine. May also need to add an additional detail view of the assembly



[OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11517478/OH5A2A4-1.-.ASSY.RADAR.ALTIMETER.GAUGE.v3.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

- [ ] Break title between TITLE_1 and TITLE_2.
  ![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/5ef4ff39-281f-43ed-8b51-16fb7240f664)
- [ ] What does Indicator Type A note apply to?
- [ ] Fix trail lines throughout (just noting so it isn't forgotten.)
- [ ] Move `TRIM LEADS OF NEOPIXELS...` note to local note next to balloon of FN 32 and delete sheet 3. (Images are not necessary.)
- [ ] Add to finish note for knob text to be insignia white.
- [ ] Add missing balloons for FN 20, 23, 31.

**Comment by Lazarus94** [comment]
IN BACKCHECK

Do you think additional views are required or fine as is?

[OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11518993/OH5A2A4-1.-.ASSY.RADAR.ALTIMETER.GAUGE.v4.pdf)

**Comment by jrsteensen** [comment]
Extra view can't hurt.

- [ ] Update to show the -24 printed gears and the 8-32 set screws.

**Comment by Lazarus94** [comment]
IN BACKCHECK



[OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE v8.pdf](https://github.com/jrsteensen/OpenHornet/files/11522711/OH5A2A4-1.-.ASSY.RADAR.ALTIMETER.GAUGE.v8.pdf)

**Comment by jrsteensen** [comment]
One last super nitpicky comment:

![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/b72cd1c3-eda2-4fb1-9ef0-c6db42f19498)

Otherwise, perfect.

**Comment by Lazarus94** [comment]
Ah whoops will fix

**Comment by Lazarus94** [comment]
IN BACKCHECK



[OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE v9.pdf](https://github.com/jrsteensen/OpenHornet/files/11522728/OH5A2A4-1.-.ASSY.RADAR.ALTIMETER.GAUGE.v9.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release package and closed.
