### ISSUE TITLE
Create Drawing: OH5A2A5 - ASSY, HYD PRESS GAUGE

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#546]
Create drawing OH5A2A5 - ASSY, HYD PRESS GAUGE.

**Comment by Lazarus94** [comment]
IN CHECK



[OH5A2A5-1 - ASSY, HYD PRESS GAUGE v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11414179/OH5A2A5-1.-.ASSY.HYD.PRESS.GAUGE.v1.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
