### ISSUE TITLE
Create Drawing: OH5A3A1 - ASSY, CAUTION LIGHT PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#547]
Create drawing OH5A3A1 - ASSY, CAUTION LIGHT PANEL.

**Comment by Exprezz0** [comment]
Updated with Rev 4; ready for drawing.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A3A1-1 - ASSY, CAUTION LIGHT PANEL v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11343105/OH5A3A1-1.-.ASSY.CAUTION.LIGHT.PANEL.v1.pdf)

**Comment by Lazarus94** [comment]
IN CHECK 

Slightly Updated



[OH5A3A1-1 - ASSY, CAUTION LIGHT PANEL v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11343124/OH5A3A1-1.-.ASSY.CAUTION.LIGHT.PANEL.v2.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

![Image](https://user-images.githubusercontent.com/2449496/235550278-a159f3de-97a2-4ab1-95b9-bb15ba638b76.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A3A1-1 - ASSY, CAUTION LIGHT PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11414084/OH5A3A1-1.-.ASSY.CAUTION.LIGHT.PANEL.v3.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
