### ISSUE TITLE
Create Drawing: OH5A4A1 - ASSY, ELEC PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#548]
Create drawing OH5A4A1 - ASSY, ELEC PANEL.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK

Previously drawn by Erik. Updating to current standard.

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A4A1-1 - ASSY, ELEC PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11220364/OH5A4A1-1.-.ASSY.ELEC.PANEL.v3.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

![image](https://user-images.githubusercontent.com/2449496/231806639-d28f7e72-3bbe-41c6-bda7-81344e58c139.png)
![image](https://user-images.githubusercontent.com/2449496/231806956-748023ca-ffce-4a5f-8b36-2d9d78c1adf0.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A4A1-1 - ASSY, ELEC PANEL v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11223949/OH5A4A1-1.-.ASSY.ELEC.PANEL.v6.pdf)
