### ISSUE TITLE
Create Drawing: OH5A5A1 - ASSY, ECS PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#549]
Create drawing OH5A5A1 - ASSY, ECS PANEL.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK 

[OH5A5A1-1 - ASSY, ECS PANEL v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11302016/OH5A5A1-1.-.ASSY.ECS.PANEL.v2.pdf)

**Comment by Exprezz0** [comment]
Saved ASSY, ECS PANEL as version 34 after updating child component dependencies for the -100 and -200 subassemblies.

**Comment by Lazarus94** [comment]
IN CHECK

**Comment by Exprezz0** [comment]
Needs to be updated based on issue #712

**Comment by jrsteensen** [comment]
Needs updates based on #712 and have information listed in original post added to drawing covering the switch modification.

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A5A1-1 - ASSY, ECS PANEL v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11408157/OH5A5A1-1.-.ASSY.ECS.PANEL.v5.pdf)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A5A1-1 - ASSY, ECS PANEL v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11414087/OH5A5A1-1.-.ASSY.ECS.PANEL.v6.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.

**Comment by Lazarus94** [comment]
IN BACKCHECK



[OH5A5A1-1 - ASSY, ECS PANEL v7.pdf](https://github.com/jrsteensen/OpenHornet/files/11522778/OH5A5A1-1.-.ASSY.ECS.PANEL.v7.pdf)

**Comment by jrsteensen** [comment]
![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/111b984e-0a85-4b13-baec-68b9ced946da)
![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/466d1745-6238-4dcb-bafe-74e67b70a3de)

Note 3 should read: `FN 28, 30 THRU 33 OF -1 ASSY & FN 3 OF -300 ASSY ARE INCLUDED WITH THEIR RESPECTIVE SWITCHES, AND SHOULD NOT BE ORDERED SEPARATELY.`

**Comment by Lazarus94** [comment]
IN BACKCHECK



[OH5A5A1-1 - ASSY, ECS PANEL v8.pdf](https://github.com/jrsteensen/OpenHornet/files/11522977/OH5A5A1-1.-.ASSY.ECS.PANEL.v8.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
