### ISSUE TITLE
Create Drawing: OH5A5A2 - ASSY, DEFOG/WINDSHIELD PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#550]
Create drawing OH5A5A2 - ASSY, DEFOG/WINDSHIELD PANEL.

**Comment by Lazarus94** [comment]
IN CHECK 



[OH5A5A2-1 - ASSY, DEFOG PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11220119/OH5A5A2-1.-.ASSY.DEFOG.PANEL.v3.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

![Image](https://user-images.githubusercontent.com/2449496/232328972-1e14f86e-27c2-41a1-8b7c-c1d452199667.png)
![Image](https://user-images.githubusercontent.com/2449496/232328985-b2d478bc-dcb4-4c05-b41e-e333c61542f7.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A5A2-1 - ASSY, DEFOG PANEL v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11242993/OH5A5A2-1.-.ASSY.DEFOG.PANEL.v4.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release package and closed.
