### ISSUE TITLE
Create Drawing: OH5A6A1 - ASSY, INTR LT PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#551]
Create drawing OH5A6A1 - ASSY, INTR LT PANEL.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
PAUSED

Waiting on Issue #711

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A6A1-1 - ASSY, INTR LT PANEL v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11366368/OH5A6A1-1.-.ASSY.INTR.LT.PANEL.v2.pdf)

**Comment by Lazarus94** [comment]
IN CHECK

Slightly updated

[OH5A6A1-1 - ASSY, INTR LT PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11366502/OH5A6A1-1.-.ASSY.INTR.LT.PANEL.v3.pdf)

**Comment by jrsteensen** [comment]
Good as-is, added to RC Release Package
