### ISSUE TITLE
Create Drawing: OH5A7A1 - ASSY, SNSR PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#552]
Create drawing OH5A7A1 - ASSY, SNSR PANEL.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A7A1-1 - ASSY, SNSR PANEL v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11331703/OH5A7A1-1.-.ASSY.SNSR.PANEL.v1.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

![Image](https://user-images.githubusercontent.com/2449496/234751696-654ee3c4-0ad2-4697-80b7-3b72d848c878.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

The switch bat is both FN10 and 24?

[OH5A7A1-1 - ASSY, SNSR PANEL v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11343250/OH5A7A1-1.-.ASSY.SNSR.PANEL.v2.pdf)

**Comment by jrsteensen** [comment]
No idea what is happening there but....

![Image](https://user-images.githubusercontent.com/2449496/236069468-4227a1be-4941-4d47-9da5-af32df1902e5.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A7A1-1 - ASSY, SNSR PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11414090/OH5A7A1-1.-.ASSY.SNSR.PANEL.v3.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
