### ISSUE TITLE
Create Drawing: OH5A9A1 - ASSY, KY58 PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#554]
Create drawing OH5A9A1 - ASSY, KY58 PANEL.

**Comment by Lazarus94** [comment]
IN CHECK



[OH5A9A1-1 - ASSY, KY58 PANEL v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11331217/OH5A9A1-1.-.ASSY.KY58.PANEL.v1.pdf)

**Comment by Lazarus94** [comment]
IN CHECK

Slightly Updated


[OH5A9A1-1 - ASSY, KY58 PANEL v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11331579/OH5A9A1-1.-.ASSY.KY58.PANEL.v3.pdf)

**Comment by kbastronomics** [comment]
see boxed area.
it looks like it's projecting the pins of the plug assembly, shouldn't it be a single projection line?  
Might be a fusion limit just pointing it out

![image](https://user-images.githubusercontent.com/19305697/234546059-c596c287-fe4a-4fea-a503-025e217c146f.png)

**Comment by Lazarus94** [comment]
Maybe worth adding a note about mounting of the battery cover on the panel?

**Comment by Lazarus94** [comment]
@kbastronomics #456

**Comment by kbastronomics** [comment]
Thank you. my bad.

**Comment by jrsteensen** [comment]
IN BACKCHECK

![Image](https://user-images.githubusercontent.com/2449496/234753196-926fa667-445c-496e-9cda-83e6043a0436.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK



[OH5A9A1-1 - ASSY, KY58 PANEL v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11343368/OH5A9A1-1.-.ASSY.KY58.PANEL.v5.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and Closed
