### ISSUE TITLE
Create Drawing: OH5A10A1 - ASSY, RIGHT CIRCUIT BREAKERS

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#555]
Create drawing OH5A10A1 - ASSY, RIGHT CIRCUIT BREAKERS.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK 



[OH5A10A1-1 - ASSY, RIGHT CIRCUIT BREAKERS v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11330621/OH5A10A1-1.-.ASSY.RIGHT.CIRCUIT.BREAKERS.v2.pdf)

**Comment by Lazarus94** [comment]
IN CHECK

Slightly Updated

[OH5A10A1-1 - ASSY, RIGHT CIRCUIT BREAKERS v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11331568/OH5A10A1-1.-.ASSY.RIGHT.CIRCUIT.BREAKERS.v4.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK


![Image](https://user-images.githubusercontent.com/2449496/234752215-b19ffebb-24c8-4d51-b172-34a33a567bc7.png)
![Image](https://user-images.githubusercontent.com/2449496/234752180-32977dd3-2361-4137-92b5-b9d97ea91edd.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A10A1-1 - ASSY, RIGHT CIRCUIT BREAKERS v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11343409/OH5A10A1-1.-.ASSY.RIGHT.CIRCUIT.BREAKERS.v5.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and Closed.
