### ISSUE TITLE
Create Drawing: OH5A10A2 - ASSY, CANOPY SWITCH

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#556]
Create drawing OH5A10A2 - ASSY, CANOPY SWITCH.

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A10A2-1 - ASSY, CANOPY SWITCH  v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11242891/OH5A10A2-1.-.ASSY.CANOPY.SWITCH.v2.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

![Image](https://user-images.githubusercontent.com/2449496/232329282-a2a45dd2-ea1e-471f-8701-e6803eb9fef9.png)
![Image](https://user-images.githubusercontent.com/2449496/232329251-55c967fe-76a2-4472-9ca8-a0a11b4e9a15.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A10A2-1 - ASSY, CANOPY SWITCH v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11243025/OH5A10A2-1.-.ASSY.CANOPY.SWITCH.v5.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
