### ISSUE TITLE
Create Drawing: OHC0001 - ASSY, LOCKING TOGGLE & SWITCH BATS

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#564]

**Comment by jrsteensen** [comment]
For check

[OHC0001 - ASSY, SWITCH, LOCKING TOGGLES v5.pdf](https://github.com/jrsteensen/OpenHornet/files/9638976/OHC0001.-.ASSY.SWITCH.LOCKING.TOGGLES.v5.pdf)

**Comment by russellmm** [comment]
looks fine

**Comment by jrsteensen** [comment]
Completed in drawing v5
