### ISSUE TITLE
Create Drawing: OHC0005 - ASSY, MAG HELD SWITCH

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#566]

**Comment by jrsteensen** [comment]
[OHC0005 - ASSY, MAG HELD SWITCH_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/9639087/OHC0005.-.ASSY.MAG.HELD.SWITCH_-_v2.pdf)

In check

**Comment by jrsteensen** [comment]
Updated with switch modification procedure.

[OHC0005 - ASSY, MAG HELD SWITCH_-_v4.pdf](https://github.com/jrsteensen/OpenHornet/files/9639187/OHC0005.-.ASSY.MAG.HELD.SWITCH_-_v4.pdf)

**Comment by russellmm** [comment]
Page 1 shows all switches as "on" in the middle postion under the description. The folliing pages show those positions as "off". Might confuse some but unlikely to affect anything.

**Comment by jrsteensen** [comment]
Fixed in drawing v5.

**Comment by jrsteensen** [comment]
Added bond note for standoff in v6

![Image](https://user-images.githubusercontent.com/2449496/192147895-6d89a117-e306-4140-9c4a-cceb83e6de69.png)
