### ISSUE TITLE
Create Drawing: OHC0007 - COMMON INSTRUMENT COMPONENTS

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#567]

**Comment by jrsteensen** [comment]
in check

[OHC0007 - INSTRUMENT COMPONENTS_-_v4.pdf](https://github.com/jrsteensen/OpenHornet/files/9639779/OHC0007.-.INSTRUMENT.COMPONENTS_-_v4.pdf)

**Comment by russellmm** [comment]
looks fine

**Comment by jrsteensen** [comment]
Completed in drawing v4.

**Comment by jrsteensen** [comment]
Needs a few revisions to bring up to current standards and correct a handful of errors.

**Comment by jrsteensen** [comment]
Closed.

[OHC0007 - INSTRUMENT COMPONENTS_-_v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11402689/OHC0007.-.INSTRUMENT.COMPONENTS_-_v5.pdf)
