### ISSUE TITLE
Create Drawing: OHC0009 - COMMON FASTENERS

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#568]

**Comment by jrsteensen** [comment]
IN CHECK

[OHC0009-1 - FAUX DZUS STUD_-_v2.pdf](https://github.com/jrsteensen/OpenHornet/files/9639654/OHC0009-1.-.FAUX.DZUS.STUD_-_v2.pdf)

**Comment by russellmm** [comment]
looks good

**Comment by jrsteensen** [comment]
Completed in drawing v2
