### ISSUE TITLE
Create Drawing: OHC0013 - ASSY, CONSOLE BULKHEAD PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#569]

**Comment by jrsteensen** [comment]
IN CHECK

[OHC0013 - BULKHEAD INTERCONNECT PANELS_-_v1.pdf](https://github.com/jrsteensen/OpenHornet/files/9639685/OHC0013.-.BULKHEAD.INTERCONNECT.PANELS_-_v1.pdf)

**Comment by russellmm** [comment]
Last Page (Page 8) has callout bubble #1 on the USB connector, should be callout bubble #4. All other pages looked okay

**Comment by jrsteensen** [comment]
Fixed and completed in drawing v2.
