### ISSUE TITLE
Replace "OH2A7A1-109 - UTIL_PHOTOSWITCH" with OHC0007-100 - UTIL PHOTOSWITCH V1

### ISSUE THREAD

**Issue by russellmm** [jrsteensen/OpenHornet#575]
The Photo switch in the "0H2A7A1-200 - Altimeter" which is part number "OH2A7A1-109 - UTIL_PHOTOSWITCH" appears to be a duplicate of the OHC0007-100 - UTIL PHOTOSWITCH V1 used in other dials. 

### Summary:
Replace "OH2A7A1-109 - UTIL_PHOTOSWITCH" with OHC0007-100 - UTIL PHOTOSWITCH V1

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)

### Type:
*Check one item.*
- [X] Maintenance

### Applicable End Item:
*Check one item.*
- [X] Lower Instrument Panel (LIP)
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/35648773/192938330-aa9baf7b-fdef-48aa-a4ca-205c554377c6.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/35648773/192938380-d8e2bff8-7799-4598-8849-9062436348c9.png">

**Comment by jrsteensen** [comment]
Fixed in LIP v102
