### ISSUE TITLE
Landing Gear Lever Mech: Screws missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#576]
### Summary:
There are brass inserts in the mechanism without screws (red circles). Also holes in the backplate that should be filled with inserts and screws (green circles).

### Screenshots:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/62520296/197350299-bca3afce-2f70-4001-8d18-6375de9cae5f.png">

### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A2A1-1

**Comment by jrsteensen** [comment]
Closed in LC v140
