### ISSUE TITLE
Radar Altimeter: LEDs not connected to PCB

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#577]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
LEDs not connected to PCB

### Screenshots:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/62520296/197374791-e7c60973-303f-4ba9-bc2c-85bc95586714.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A4-1

**Comment by jrsteensen** [comment]
Not a bug. Bend the leads.
