### ISSUE TITLE
Parking Brake shaft: Indentations missing?

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#578]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
At the moment there is only one radial indentation to fixate the shaft in the in/out position. Shouldn't there be more, for instance to lock the turned positions (red circle)? Hence the multiple spring plungers.
Also, additional indentations at the end of the shaft might be needed (green circle).

### Screenshots:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/62520296/197375419-c7f3bb95-e701-4779-8eac-90860dcc1d08.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [] Bug
- [] Feature Enhancement
- [ ] Maintenance
- [X] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A3A2

**Comment by jrsteensen** [comment]
Designed correctly as-is. The aft identation at the aft position pulls forward and engages the fwd ball springs. The SHCS in the shaft engages the switches.
