### ISSUE TITLE
Standby Alt, Encoder mount change required 

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#580]
### Summary:
On test asem of the standby Alt it is noted there is not enough thread to secure the top nut, aprox 1mm of matrial is required to be removed from the underside of the Encoder mount 

### Expected Results/How It Should Work:
there should be at least enough thread to enter the nut

### Actual Results/How It Does Work:
there is no thread above the plastice to start turning the nut

### Screenshots:
![image](https://user-images.githubusercontent.com/67782885/197607414-29f01379-4304-4f0b-9004-1a202fa76fb4.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (F360)

### Type:
*Check one item.*
- [X] Bug

### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP) - Standby Gauges

### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by Lazarus94** [comment]
Fixed in [OH2A7A1-200 - ALTIMETER] V8

**Comment by jrsteensen** [comment]
Review Comments

- [ ] Need to update up through the console level - should be fixed in LIP vXXXX with latest components.

**Comment by Lazarus94** [comment]
> ### Review Comments
> * [ ]  Need to update up through the console level - should be fixed in LIP vXXXX with latest components.

Will do.

**Comment by jrsteensen** [comment]
Fixed in LIP v96
