### ISSUE TITLE
Standby Gauge Backlight LED Screen Print

### ISSUE THREAD

**Issue by Ben-F111** [jrsteensen/OpenHornet#582]
### Summary:
Investigation required to confirm the orientation of the FLAT EDGE for the WS2812B LEDs used for the back lighting

### Expected Results/How It Should Work:
Screen print and LED pin out should match the Physical LED Pin out, the "Flat edge" shown on the screen print should match the flat edge of the LED

### Actual Results/How It Does Work:
During testing and install of WS2812B LEDs it has been found this screen print may be 180deg out, de soldering and flipping the LED's to the screen print direction (see pic below) results in corrct operation of the test sets

investigation required per the below

1 are there more than one brand type of WS2821B LEDs with differing Pin outs
2 if not, investigate and confirm the current screen print is OK or needs fllipping
3 if yes, uncover a way of marking thew PCB to allow for both

current investigation, including NEOPixel and Adifuit NEOPixel SHow the DATA OUT Pin on the FLAT EDGE, the current OH design has this on the DATA IN Wire.

note the tracks and circuits function correclty (with the WS21812B LED flipped) and should not need moving

Current 
P4 DATA IN Flat Edge
P3 VDD- 5VDC
P2 GND
P1 DATA OUT
(Does not work when installed flat edge to screen print)

Should be
P4 DATA OUT - Flat Edge
P3 GND 
P2 VDD- 5VDC
P1 DATA IN
![IMG_2700](https://user-images.githubusercontent.com/67782885/198403384-a31ad0ad-4ba5-4f82-b3b9-11e5e533da33.jpg)

![IMG_2698](https://user-images.githubusercontent.com/67782885/198403411-4f3282ad-a8f4-4aeb-9327-09093dc2b54d.jpg)

Uploading IMG_2691.MOV…

![IMG_2692](https://user-images.githubusercontent.com/67782885/198403398-c187dd69-5e5d-461d-97ae-3444e4bb4843.jpg)

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] ECAD (PCB Design or other electrical hardware)

### Type:
*Check one item.*
- [X] Bug
### Applicable End Item:
*Check one item.*
      
- [X] Lower Instrument Panel (LIP) - Standby Gauges 

### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by Ben-F111** [comment]
https://user-images.githubusercontent.com/67782885/198403699-17397b02-1e30-4911-b6e6-85c4d2f5fbcb.MOV

**Comment by Exprezz0** [comment]
@Ben-F111 These are the WS2812B, seen on the backlight boards.

![image](https://user-images.githubusercontent.com/81926396/215648182-0c680aec-c944-4bf9-96a0-b81ed50adc58.png)

But can confirm, Pin #2 is suppose to be Ground.  
WP154A4, https://www.kingbright.com/attachments/file/psearch/000/00/00/L-154A4SUREQBFZGEW(Ver.11A).pdf

The footprint and silkscreen are correct; the pins were just connected to the wrong nets.  I'll fix it and get it pushed up after Issue #592 gets reviewed.

**Comment by Exprezz0** [comment]
Fixed with commit: 2de58f52bfa469f13f1cb1c4f65ecbc64b1d1c8a.  Will be implemented with #592.  The 2x 4-pin LEDs are based on this: https://www.adafruit.com/product/1938.  

Standby Gauge needs to be transitioned and updated to K7.  I'll double check BOM and files again, but this issue specifically has been fixed.
