### ISSUE TITLE
D1 Diode silkscreen incorrect in Hall Effect Sensor board

### ISSUE THREAD

**Issue by geeman-nz** [jrsteensen/OpenHornet#584]
### Summary:
The silkscreen for the Hall effect sensor PCB is incorrect. It displays that the diode should be placed in the incorrect orientation, leading to the polarity being backwards.

### Expected Results/How It Should Work:
The + symbol should be placed on the opposite side to where it is currently placed

### Screenshots:
Note the diode is placed in opposite polarity to the marked silkscreen.
This image was produced by a JLCPCB engineer when this issue was questioned.

![Produce_DanZhi SMT_Snapshot Top 3633949A_Y15 SMT02211071017825 (2)](https://user-images.githubusercontent.com/117061959/201016587-2e980016-545a-406c-b06c-1ec378cf241a.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [X] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [X] Throttle
- [ ] General Software
### Associated Filename(s):
ABSIS_Hall_Sensor

**Comment by Exprezz0** [comment]
@geeman-nz Is there any reason why the Diode can't be rotated 180 degrees instead of adjusting the silkscreen?  The + symbol indicates the correct pad.

![image](https://user-images.githubusercontent.com/81926396/215647158-b9b60c17-f070-45d8-a0e1-71fa38094538.png)

**Comment by Arribe** [comment]
From ordering experience this is confusing.  Shouldn't the silkscreen reflect the direction of the diode and not which pad is '+'? There are instances for using reversed polarity diodes. 
![image](https://user-images.githubusercontent.com/47125808/228558878-9c3cef42-3a23-4935-ae1e-0e6018b29bb7.png)

**Comment by Exprezz0** [comment]
![image](https://user-images.githubusercontent.com/81926396/228634735-75f3aca6-2eac-45ca-a51f-74408ac921e4.png)

Will be closed with #592

**Comment by jrsteensen** [comment]
@Exprezz0 - for brevity, just add the K to the left side, no arrow. Stays more consistent with single character markings of other polarities. Drop the A. (If you don't mind - if you already implemented it, don't worry about it. Nothing I'm going to lose sleep over.)

**Comment by Exprezz0** [comment]
Too easy.  Just figured I'd alleviate all doubt.  Fixed and updated.
