### ISSUE TITLE
Components missing Values on Fire/Test Schematic/PCB

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#586]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
The Fire Test Control/Backlight Board is missing values on all components except the neopixels and the 1000uF cap on back side of PCB, however that Cap (C1) only has it on the legend,  not the component.

### Expected Results/How It Should Work:
Each component should clearly show the Value and package used

### Actual Results/How It Does Work:
Resistor, LED and Caps are all missing Values,

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
![2022-11-17_02-34-49](https://user-images.githubusercontent.com/19305697/202384726-1901de3f-de1d-42b1-8367-2f5fd754a371.png)
![2022-11-17_02-35-17](https://user-images.githubusercontent.com/19305697/202384730-33a4184c-8b8f-42e8-9832-53042d8d8c0c.png)
![2022-11-17_02-33-53](https://user-images.githubusercontent.com/19305697/202384732-8fbe499c-a2eb-48fd-af8b-db6b020a4bde.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Ch one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*FIRE TEST Panel PCB V2.sch.*

**Comment by Exprezz0** [comment]
Fixed with commit e3a25a4.
