### ISSUE TITLE
ABSIS_HID_Bus_Master: SOIC-8 wrong angle

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#587]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
After uploading the necessary files on JLCPCB I noticed that the SOIC-8 is rotated 270 degress. As a result the pins don't match the PCB. The rotation should be 180 or 0 degress, depending on the circuits.

### Screenshots:
![image](https://user-images.githubusercontent.com/62520296/202841103-3da727f6-6acd-4bf8-86cc-c19eff12e9ab.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Upper Instrument Panel (UIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
ABSIS003 ABSIS_HID_BUS_MASTER

**Comment by Higgins-OH** [comment]
The "align" command seems to fix the problem. Manfuacturing will tell...

**Comment by jrsteensen** [comment]
> The "align" command seems to fix the problem. Manfuacturing will tell...

Align command on what? Sorry, need more detail here.

**Comment by Higgins-OH** [comment]
The SMD parts are always far from the PCB in JLCPCB's preview window. I just accidently clicked on the "align" button and every part was at its intended place. Including the SOIC. 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/62520296/202862322-173a4007-db5c-4061-a43c-dfc9947c9a03.png">

**Comment by Exprezz0** [comment]
This is an issue with JLC, not the BOM/CPL.  Fixed with #592
