### ISSUE TITLE
Util_Photoswitch: Different names/part numbers in Fusion

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#590]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
Altimeter: The photoswitch is called OH2A7A1-109 UTIL_PHOTOSWITCH
VVI & Airspeed Indicator: Photoswitch is called OHC007-100 UTIL PHOTOSWITCH

### Expected Results/How It Should Work:
OH's principle of same part, same name should be valid here as well.

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [x] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Duplicate issue to #575
