### ISSUE TITLE
UFC Incorrect Pin Spacing on UFCOptionDigit

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#595]
### Summary:
The UFCOptionDigit displays from Tekcreation do not fit on the V5 UFC Board.   Pins are 0.055 in (1.3mm) closer together than the should be.  correct distance is 0.500 in

### Expected Results/How It Should Work:
The UFCOptionDigit should fit the pad precisely.

### Actual Results/How It Does Work:
The UFCOptionDigit does not correctly fit the pads on the PCB due the pads are 0.055" to close,  this causes bending the UFCOptionDigit leg beyond what can be comfortably used

### Screenshots:

*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.

**V5 PCB as manufactured from JCLPCB**
![IMG_4840](https://user-images.githubusercontent.com/19305697/204425315-b8f638a3-74f6-4a23-97cb-841c24e8e86a.jpg)

**Image showing how the UFCOptionDigit fits on the pcb** 
![IMG_4838](https://user-images.githubusercontent.com/19305697/204425314-53ab6030-53b8-43f6-be0f-9f0bc47f1a77.jpg)

**Image show sample adjustment to one pin of the footprint**
![2022-11-27_23-36-38](https://user-images.githubusercontent.com/19305697/204426210-d475dc78-c9c3-4611-a8d7-6a5df6f1cfe4.png)

**Images shows UFCOptionDigit fitting correctly on a printed copy of the PCB design after fixing the footprint**
![IMG_4847](https://user-images.githubusercontent.com/19305697/204425313-bb3dc704-ed5e-406d-afde-4ef853b8a608.JPG)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [X] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
ufc_v5_main.pro

**Comment by jrsteensen** [comment]
This will need to be factored in with the UFC redesign.

**Comment by jrsteensen** [comment]
Fixed footprint, will be reflected in UFC v5.5 PCB.
