### ISSUE TITLE
HYD ISOL Switch Incorrect

### ISSUE THREAD

**Issue by Exprezz0** [jrsteensen/OpenHornet#597]
### Summary:
In the current build, the HYD ISOL switch is listed as a SPDT On-Off-On switch and should be  SPDT Momentary (On)-On switch as described below.

### Expected Results/How It Should Work:
According to the NATOPs:  The HYD ISO should be a SPDT switch used for two options: ORIDE and NORM.  ORIDE is used to charge the APU and Brake accumulators (under certain conditions) which suggests that the switch has a Momentary (On).  The following also asserts this suggestion as having it locked in the ORIDE would risk pumping all hydraulic fluid out if there was a leak.

![image](https://user-images.githubusercontent.com/81926396/204640996-e804a409-82f6-42a6-9470-1a4e6f186381.png)

### Actual Results/How It Does Work:
![image](https://user-images.githubusercontent.com/81926396/204638707-a998fa6b-08f4-49af-8366-c67ddcfe7214.png)

### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):

***OH4A7A3-1 - ASSY, MC HYD ISOL PANEL v1***

**Comment by jrsteensen** [comment]
Fixed in LC v131
