### ISSUE TITLE
OBOGS Knob/Rotate Switch - Misaligned

### ISSUE THREAD

**Issue by Exprezz0** [jrsteensen/OpenHornet#598]
### Summary:
Alignment of OBOGS Knob on rotary switch **OR** rotation of the Rotary Switch that controls oxygen flow inhibits the direction that the OBOGS Knob arrow points at the "OXY FLOW _ON_ and _OFF_

### Expected Results/How It Should Work:
With the knob correctly aligned on the rotary switch, the arrow should point to either *On* or *Off* with the rotation of travel (90 degrees) from the 9-o-clock to the 12-o-clock position, by way of the 10-o-clock.  

### Actual Results/How It Does Work:

![image](https://user-images.githubusercontent.com/81926396/204878510-84a652ea-9609-4e0d-82c8-f32e77b278dc.png)

In this configuration with the rotary switch mounted to the backplate and the indexing pin (*#1*) at the 12-o-clock position, the shaft is currently rotated all the way to the **LEFT** 90 degrees.  This results in the flat edge of the shaft (*#2*) facing the 12-o-clock position as well.  

![image](https://user-images.githubusercontent.com/81926396/204886217-e8406695-02bd-4e79-8aa8-03471782143f.png)

With P/N A11405RNZQ:  After testing and verifying, the "Far left rotation" has the flat edge of the rotary switch shaft facing the index pin.  A 90 degree rotation to the right would have the flat edge facing the 3-o-clock position.

####Solution:

Option A:  Easiest solution is to rotate the entire switch assembly 90 degrees to the left and extrude a new hole in the backplate for the indexing pin.

Option B:  Rotate the OBOGS Knob 90 degrees to the left and perform a Cut in the model so that the knob fits on the rotary shaft.  Flat part would be facing the 3-o-clock position inside the knob.

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
- [x] MCAD (Fusion 360)

### Type:
- [X] Bug

### Applicable End Item:
- [X] Left Console

### Associated Filename(s):

*OH4A7A2-1 - ASSY, OBOGS PANEL.*

**Comment by Exprezz0** [comment]
Fixed Model OH4A7A2-1 - ASSY, OBOGS PANEL

Process:
1:  Deleted Rigid Joint.  Rotated Rotary Switch 90* to the left.
2:  Filled hole in *OH4A7A2-11 - OBOGS BACKPLATE* that was left behind from indexing pin on rotary switch.
3:  Cut new hole (.125) in *OH4A7A2-11 - OBOGS BACKPLATE* to facilitate new position of indexing pin.
4:  Added new Rigid Joint
5:  Dissolved Extrudes/Deleted Sketches from Browser 
6.  Saved User Version with Remarks. (v19 --> v20)
7. 
![image](https://user-images.githubusercontent.com/81926396/204893921-a9b22ec4-e15e-4727-8fde-7e5b3e825fe2.png)

OBOGS Knob will now point to "OFF" position in model, but will function properly once produced.

**Comment by jrsteensen** [comment]
Closed per above! Thanks @Exprezz0
