### ISSUE TITLE
Master Arm Module Spacer: Hole missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#599]
### Summary:
One hole for the screw is missing in the Master Arm Module Spacer

### Expected Results/How It Should Work:
Needs hole for the middle screw.

### Screenshots:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/62520296/205478931-ec7f51b8-2d11-47c9-be08-dd21e92ed3b9.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Upper Instrument Panel (UIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH1A2-14

**Comment by Lazarus94** [comment]
Fixed in OH1A2-1 - ASSY, PANEL, MASTER ARM V13 and OH1A2-1_MOD_A - ASSY, PANEL, MASTER ARM V6

**Comment by jrsteensen** [comment]
### Review Comments

- [ ] Need to update up through the console level - should be fixed in UIP vXXXX with latest components.

**Comment by jrsteensen** [comment]
Fixed in UIP v68
