### ISSUE TITLE
Rudder Pedal Adjust Handle

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#6]
Design and integrate a Rudder Pedal Adjust Handle that clamps/glues over the switch bat for releasing the rudder pedal locking solenoid.

**Comment by jrsteensen** [comment]
@crosshairs2230 is working reference.

**Comment by crosshairs2230** [comment]
[Pedals_FrictionLever.zip](https://github.com/jrsteensen/OpenHornet/files/3969506/Pedals_FrictionLever.zip)

**Comment by jrsteensen** [comment]
Plan:
- [ ] Remove existing toggle.
- [ ] Add rudder pedal adjust lever with structure.
- [ ] Use snap action switch to actuate solenoid for rudders.

Thanks @crosshairs2230! Looks great!

**Comment by jrsteensen** [comment]
Completed in 86af002
