### ISSUE TITLE
DDI Mounting Spacer: Holes for Screws to attach at UIP face too shallow

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#600]
### Expected Results/How It Should Work:
For the screws to fit, the holes need to be deeper.

### Actual Results/How It Does Work:
At the moment the holes are just deep enough for the inserts, but not for the screws.

### Screenshots:
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/62520296/205485364-e14e3f56-05b5-459d-9148-2c3a4b85272a.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Upper Instrument Panel (UIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH1A3-18 - DDI Mounting Spacer

**Comment by jrsteensen** [comment]
Fixed in UIP v70
