### ISSUE TITLE
SNSR engraving panel: radial cutouts for backlight missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#603]
### Summary:
The knobs are supposed to be backlit, the engraving is missing at the RADAR and INS holes.

### Screenshots:

![](https://cdn.discordapp.com/attachments/392833351238811650/1053665605598838846/image.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A7A1-12

**Comment by kbastronomics** [comment]
Fixed in OH5A7A1-1 - ASSY, SNSR PANEL v18

**Comment by jrsteensen** [comment]
### Review Results:

- [ ] Please ensure you update all assemblies up to the console level with the latest version.

![image](https://user-images.githubusercontent.com/2449496/227736729-9cdf7b1d-63de-493b-9105-fa3fae0ecec6.png)

**Comment by jrsteensen** [comment]
Closed in RC v114
