### ISSUE TITLE
Incorrect switches (2x) used on OH1A7-1 - ASSY, PANEL, HUD v5

### ISSUE THREAD

**Issue by Exprezz0** [jrsteensen/OpenHornet#605]
### Summary:
Referencing the B1HWF model, the DAY/NIGHT and ALT select switches are displaying as `100SP3T8B13M1QEH - Toggle Switches SPDT ON-OFF-ON SLDR` on the HUD Panel Assembly.  

### Expected Results/How It Should Work:
The Day/Night Hud selector only has two options.  Same goes for the Altimeter selection switch (BARO and RDR).
Both Switches should be `100SP1T8B13M1QEH - Toggle Switches SPDT ON-ON SLDR MNT`.  This switch is in keeping with the same characteristics and dimensions as the current switch with the only difference being extra "OFF" position.

### Screenshots:
![image](https://user-images.githubusercontent.com/81926396/209005598-8604602b-34f0-4f2f-9795-ff55b53ecbd6.png)

### Category:
*Check one or more items.*
- [x] MCAD (Fusion 360)

### Type:
*Check one item.*
- [x] Bug

### Applicable End Item:
*Check one item.*
- [x] Main Instrument Panel (MIP)

### Associated Filename(s):
OH1A7-1 - ASSY, PANEL, HUD v5

**Comment by Lazarus94** [comment]
Fixed in OH1A7-1 - ASSY, PANEL, HUD V6.

**Comment by jrsteensen** [comment]
### Review Comments

- [ ] Need to update up through the console level - should be fixed in UIP vXXXX with latest components.

**Comment by jrsteensen** [comment]
Fixed in UIP v69
