### ISSUE TITLE
Gen Tie Sticker should be named Gen Tie Legend Plate, letters need to be recessed

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#607]
### Summary:
Gen Tie sticker seems to be a relic from the former version (non-backlit). Now it's a legend plate.
According to this, the letters need to be recessed. At the moment they are level with the surface of the panel.

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Fixed in Left Console v126
