### ISSUE TITLE
 Inboard & Outboard Throttle Legend plate lettering not engraved

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#608]
### Summary:
The Inboard & Outboard Throttle Legend plate lettering is not set at -0.003" for engraving or 3d printing.

### Expected Results/How It Should Work:
We should be able to engrave or print these parts

### Actual Results/How It Does Work:
Since these are only surface details they will not export in STL/3MF or as a SVG/AI file for printing or engraving.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.
<br>**PRO-TIP:** Just paste the images here.*
As it is
![2022-12-25_13-58-55](https://user-images.githubusercontent.com/19305697/209479358-2ce5e922-b1ea-4b40-9ab5-5a69ae47e3fe.png)
As it should be
![2022-12-25_13-59-24](https://user-images.githubusercontent.com/19305697/209479354-7a0762b9-8d94-41d4-8cdb-b6b3686fccfd.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (Fusion360)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [x] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A9A4-13 - INBOARD THROTTLE QUADRANT LEGEND PLATE
OH4A9A4-11 - OUTBOARD THROTTLE QUADRANT LEGEND PLATE

**Comment by jrsteensen** [comment]
Fixed in Left Console v125
