### ISSUE TITLE
Spin Panel: BRT marker missing?

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#610]
### Summary:
The HMD Brightness doesn't have a "BRT" marker, unlike the engravings for the AOA on the HUD panel.
Sources are not consistent, so this is more a question than a definite issue. Shouldn't there be a marker of some sort?

### Screenshots:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/62520296/210090178-b6267bea-d64a-4745-93bb-8d782b2db082.png">

### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Upper Instrument Panel (UIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH1A6-12 Spin Panel Legend Plate

**Comment by kbastronomics** [comment]
While not the perfect reference it does have the marking in DCS
![image](https://user-images.githubusercontent.com/19305697/210093795-aea62374-c39d-458f-9525-3a4b0f217e4f.png)

**Comment by Higgins-OH** [comment]
Well, the DCS panel looks different than the OH panel - different versions or missing lines?
<img width="224" alt="image" src="https://user-images.githubusercontent.com/62520296/210095138-62483f31-a070-45ad-b26d-bb1c47529eed.png">

**Comment by jrsteensen** [comment]
We are using a different version, more accurate to the Block that we are representing. I believe this is correct as-is.
