### ISSUE TITLE
Ext Lt panel: "LT" engraving missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#611]
### Summary:
The engraving "LT" is missing.
EDIT: Also the PCB has no LEDs to backlight the missing letters.

### Screenshots:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/62520296/210099759-8b7d9e98-6647-442e-b646-b18f2ca8bf6b.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A4A2-13 Ext Lt Legend Plate

**Comment by jrsteensen** [comment]
The block of F-18 we are replicating does not have the LT marking there.

Will take no action on this item.
