### ISSUE TITLE
LDG Gear Panel: Engraving wrong colour

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#612]
### Summary:
Panel only showing yellow and black engraving, there should also be white.

### Expected Results/How It Should Work:
According to various sources there aren't only yellow stripes, but white/yellow alternating like on the other panels.

### Actual Results/How It Does Work:
Stripes in black and yellow only.

### Screenshots:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/62520296/210101481-912c7c2a-d4a7-4fcd-9249-c6b8915c025b.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/62520296/210101804-fdb34838-741b-4b4f-af54-a9f669b66558.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*
OH4A2A1-13 Landing Gear Panel Legend Plate

**Comment by Exprezz0** [comment]
The lines are already sketched and separated on the panel, but they weren't filled with the appropriate color.  The only modification that needs to happen to fix this issue is application of color using the Appearance menu option (see attached):

![image](https://user-images.githubusercontent.com/81926396/210370473-1870d0c3-1f9b-46b0-8b75-c9d682a75dc4.png)

**Comment by jrsteensen** [comment]
Please feel free @Exprezz0!

**Comment by Exprezz0** [comment]
Legend Panel fixed.  File saved on the cloud with description (v20).

**Comment by jrsteensen** [comment]
Thanks @Exprezz0!
