### ISSUE TITLE
Design ideas

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#613]
### Summary:
Ideas:
1. There is no mouse integrated in the cockpit. Why not integrating a trackball? It could fit right next to the View knob on the Sim Cntl panel.
2. There is no button to center a VR headset yet. One of the buttons of the HUD box could surely fulfill that function.

### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [x] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by jrsteensen** [comment]
I am going to leave the mouse up to the user. I was thinking something next to the right or left knee. 

As to the second item, the TM stick grip has extra buttons. That is something you can assign there, and is probably useful to have at your fingertips.
