### ISSUE TITLE
OH1A1-1 - ASSY, UPPER INSTRUMENT PANEL_OH1A1-20 - MFD LOWER SUPPORT B v3 - needs notch to provide monitor clearnace

### ISSUE THREAD

**Issue by bnepethomas** [jrsteensen/OpenHornet#616]
### Summary:
OH1A1-1 - ASSY, UPPER INSTRUMENT PANEL_OH1A1-20 - MFD LOWER SUPPORT B v3

The standby instruments screen sits slightly higher than the base of the two cylinders which means the lower support isn't able to sit snugly against the standby instrument assembly.

Add notch from rear approx 9mm and 4.8mm from base of cylinder

Fusion file with Notch able to be supplied

# Screenshots:

![OH1A1-1 - ASSY, UPPER INSTRUMENT PANEL_OH1A1-20 - MFD LOWER SUPPORT B v3](https://user-images.githubusercontent.com/16440158/210430357-3392bccd-266f-4547-8826-658ccfe35c71.jpg)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [X] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):

OH1A1-1 - ASSY, UPPER INSTRUMENT PANEL_OH1A1-20 - MFD LOWER SUPPORT B v3

**Comment by jrsteensen** [comment]
Fixed in UIP v74
