### ISSUE TITLE
DDI brightness selector/power switch is wrong component

### ISSUE THREAD

**Issue by DeadMeatDCS** [jrsteensen/OpenHornet#617]
### Summary:
Wrong rotary switch component for DDI brightness selector/power switch. 
Current component is a switch with an index angle of 60 degrees. Should have been a switch with a 45 degree index angle to match legend and reference.

### Expected Results/How It Should Work:
Legend marks in model and in reference pictures indicate 45 degrees switch steps, calling for a rotary switch with the same index angle.

Appropriate switch would be a **MRX108** (2-8 positions, 45 degree index angle) if we want stick with the same NKK family as the _current MRY106_. It has a few differences however so a small update is necessary to the DDI mounting spacer:

- Keyway and locking ring sit at a different angle to the flat on the switch shaft, so the hole for that needs to be moved (see below).
- _Diameter is the same, but the switch bushing is 0.004" taller. It should stay clear of the DDI PCB though._
- _Switch body and common terminal is longer, adding 0.095" to the length but there's nothing behind the DDI, so not a problem._

### Actual Results/How It Does Work:
Current switch in the model is a MRY106, which has 60 degree index angle (2-6 positions), not matching legend and reference.

### Screenshots:
Reference
![image](https://user-images.githubusercontent.com/52100072/211295982-b4507dd9-9db8-4602-9890-70194af35e7a.png)

Legend in model
![image](https://user-images.githubusercontent.com/52100072/211295963-517813fa-f9aa-4397-bbe9-fcfe95dda0b8.png)

Anti rotation hole to be moved
![image](https://user-images.githubusercontent.com/52100072/211297635-67b5d765-f228-4620-981e-2ebb056c76ad.png)

Current switch
![image](https://user-images.githubusercontent.com/52100072/211299000-636679c7-b8a1-40c3-90f4-571cccd240f3.png)

Suggested switch
![image](https://user-images.githubusercontent.com/52100072/211299035-933064dc-613b-49ad-b789-aadcc560d4fd.png)

### Category:
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [x] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH1A3-18 - DDI MOUNTING SPACER
MRY106 - SWITCH, ROTARY, 2-6 POS, NKK

**Comment by jrsteensen** [comment]
Thanks for the write up @DeadMeatDCS! This is an example of an excellent issue writeup!

**Comment by jrsteensen** [comment]
Fixed in UIP v71
