### ISSUE TITLE
Hook Lever LEDs: Holders don't fit in chassis

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#618]
### Summary:
The assigned LED holders (CR-104) are too big for the cutout in the lever chassis.

### Screenshots:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/62520296/212465959-b5bf3fe8-c2a4-4d65-ad89-0374d3a0e7a0.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/62520296/212465983-190dc2a1-c423-4335-a154-5fb2b540d93f.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A1-10 - Assy, hook lever

**Comment by jrsteensen** [comment]
No room for geometry modifications. Instead, add note to drawing to remove the R-104 ring and glue the C-104 clip on front face to the -12 Mounting Plate.
