### ISSUE TITLE
 ABSIS ATX Power Distribution Board PCIE1/2 Connectors to close together

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#619]
### Summary:
The PCIE1 and PCIE2 connector sit too close together which make is extremely difficult to remove the PCIE2 connector as you can not squeeze the release catch

### Expected Results/How It Should Work:
you should be able to remove either connector with little effort

### Actual Results/How It Does Work:
Since the PCIE2 connector sits so close to the PCIE1 connector and the catch for the PCIE2 connector faces the PCIE1 connector the catch will not release without using force which could damage the connector and/or PCB.

### Screenshots:
![image](https://user-images.githubusercontent.com/19305697/215307428-1cb9d257-3329-4eec-bed6-7c43de0da432.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [X] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
ABSIS_ATX_PSU_Board

**Comment by Exprezz0** [comment]
Fixed with commit #592 76ae24b8a8a5f743163ccd1a70e7d358459507ca

![image](https://user-images.githubusercontent.com/81926396/216282843-5cd85496-bac2-453f-84a4-c75cc52a2270.png)
