### ISSUE TITLE
RALT CNTRL: BUS IN/BUS OUT connectors too close (similar to ATX PSU)

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#620]
### Summary:
see ATX PSU PCIE connector issue

### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by Exprezz0** [comment]
Fixed with commit #8eeb1a8ef16387a407aaea08bc6af90a570dd349
