### ISSUE TITLE
Spin Panel backplate modifications needed: LED D16 & D17 cutouts too high for PCB V2.1; cutout needed for ready LED

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#621]
The LED cutouts don't fit the PCB's LEDs D16 & D17, the holes need to be moved a bit downwards.
In addition, the backplate needs a cutout for the PCB pins of the "ready" LED.

### Screenshots:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/62520296/215559927-785e8a51-1a5a-4e33-a317-5f0b6d5cf821.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [x] UIP          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH1A6-10 Spin Panel Backplate

**Comment by jrsteensen** [comment]
Fixed in UIP v73.
