### ISSUE TITLE
AV COOL lightplate cutout too small for switch nut

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#626]
### Summary:
The lightplate cutout needs to be a little bit bigger for the switch's nut to fit.

### Screenshots:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/62520296/218326187-5b8e2ee0-d46f-46f4-b612-8252e98c8887.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A3-10 AV Cool Lightplate

**Comment by jrsteensen** [comment]
FIxed in RC v112
