### ISSUE TITLE
Defog Backplate: Cutout for resistor needed

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#627]
The Defog Panel Backplate needs a cutout for the PCB's resistor. Otherwise it will put pressure on the resistor.

### Screenshots:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/62520296/219872830-531ce4d3-7c17-4e89-a5fd-08839965d9af.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A5A2-10 Defog Backplate

**Comment by jrsteensen** [comment]
Fixed in RC v113
