### ISSUE TITLE
PCB QOL proposal: capacitors not too close to BL connectors

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#628]
In some cases the capacitor is almost touching the BL connector. Therefore removing or repairing it at a later time would be hard. It might be better to either rotate them or move them away from the connectors.

### Screenshots:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/62520296/219883200-3fef3aae-9dfb-4575-a185-c412c5c80300.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [x] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by jrsteensen** [comment]
Since this would be a major change across many of the PCBs, and it is fairly easily worked around by desoldering the connector next to it, we will not plan on implementing as a change. It has been noted as a design consideration for future designs however.
