### ISSUE TITLE
Comm Panel Backplate: Cutout for ready LED pins missing, holes for poti nuts too small

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#629]
The backplate lacks a cutout for the solder pins of the ready LED.
Also, the holes for the poti nuts are 0.394 inches in diameter. The potis' nuts are 0.44 inches in diameter.

### Screenshots:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/62520296/219931661-142af433-bb84-4254-be3c-12de225af5ef.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A7A1-11 Comm Panel Backplate

**Comment by Arribe** [comment]
Agree with the poti nut cut out. I did a recut to increase the hole diameter to get it to fit. I do not have the ready LEDs yet.

**Comment by jrsteensen** [comment]
Fixed in LC v129
