### ISSUE TITLE
FCS Panel: Threads of pushbutton not long enough.

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#630]
### Summary:
Pushbutton can't be fastened the way it's illustrated in the plans: Threads not long enough.
Either we need to find another pushbutton or the button is fastened on the PCB. In the latter case the backplate need a bigger cutout to make space for the button.

Update: It seems the best option is to fasten the pushbutton on the backplate. For this to work the backplate needs a cutout for the button's nut. Otherwise the button would be a bit too short to be pushed conveniently when lightplate is mounted.

### Screenshots:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/62520296/219936521-8fef6b77-b393-4f6f-b210-2f887fa43831.png">
<img width="473" alt="image" src="https://user-images.githubusercontent.com/62520296/219969933-e959d063-0b88-42f4-ba8d-1e18d45407c0.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
PNP8S2T2Y03QE C&K Pushbutton
OH4A6A1-11 FCS Panel Backplate

**Comment by jrsteensen** [comment]
Fixed in LC v135 (Replaced pushbutton with NKK MB2011SB1W01-DA)

Switch Cap screws on so will have to design custom screw cap once I can figure out what the screw thread on it is.
