### ISSUE TITLE
FCS Panel ABSIS adapter plate: One hole too large

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#631]
### Summary:
One hole of the three connecting the adapter plate to the panel is too big for either the screw and the hex standoff.

### Screenshots:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/62520296/219940730-06dbcfe4-825d-4a7b-b8ff-ef63f3aa453a.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A6A1-19: FCS ABSIS Adapter Plate

**Comment by jrsteensen** [comment]
Fixed in LC v136
