### ISSUE TITLE
Radar Altimeter: LED pin length, stepper axis lenght

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#632]
### Summary:
The pin length of the LED forces us to mount the LEDs with an angle, so they barely touch the backside of the PCB. 

Since the axis of the stepper motor barely looks out of the dial face leaving no room for error it might be a good idea to reduce the width of the RAlt stepper mount. With PCB and stepper closer to the dial face (even 1mm might suffice) both problems could vanish.

### Screenshots:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/62520296/219966864-94d75db3-e1b8-4e39-a1fe-a73e7f6ce8f4.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A4-15 Ralt Stepper Standoff

**Comment by jrsteensen** [comment]
Add note to drawing to trim leads of LEDs, and solder them with jumper wires to PCB.
