### ISSUE TITLE
OH4A1A1-44 - LEFT AUX VENT PLUG - Geometry Issues

### ISSUE THREAD

**Issue by ajmilner85** [jrsteensen/OpenHornet#633]
### Summary:
Component contains some extra bodies left over from a cut operation, and some bad geometry/extra faces in the vent area.

### Screenshots:
Overview
![Screenshot 2023-02-23 120528markup](https://user-images.githubusercontent.com/22624641/220979704-34d8062b-f00d-4dde-aaf4-8e46b07aac82.png)

Detail
1.
![Screenshot 2023-02-23 120606](https://user-images.githubusercontent.com/22624641/220979707-c07d421e-15f4-481d-877c-0d7dc71dfc6c.png)
![Screenshot 2023-02-23 120755](https://user-images.githubusercontent.com/22624641/220979713-61bbd894-49be-4418-91d2-51905018395b.png)

2.
![Screenshot 2023-02-23 120634](https://user-images.githubusercontent.com/22624641/220979709-1cc987be-3a40-4905-b5d4-7cf1e40c9312.png)

3.
![Screenshot 2023-02-23 120654](https://user-images.githubusercontent.com/22624641/220979711-bf3cabb6-e677-4bf1-bed5-8c91b506b087.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A1A1-44 - LEFT AUX VENT PLUG (Fusion 360)

**Comment by jrsteensen** [comment]
Fixed in LC v137
