### ISSUE TITLE
OH4A8A2-10 - DISP_BUTTON_BASE - Through Holes for 8-32 Brass Inserts Too Small

### ISSUE THREAD

**Issue by ajmilner85** [jrsteensen/OpenHornet#634]
### Summary:
OH4A8A2-10 - DISP_BUTTON_BASE has four through holes intended for McMaster part 93365A140 - INSERT, 8-32, BRASS, FOR PLASTICS. These holes are undersized in the Fusion 360 model (OH4A8A2-1 - ASSY, DISPENSE BUTTON).

### Expected Results/How It Should Work:
Hole size for 8-32 Brass Insert should be 0.235in. 

Inserting the bottom portion of the brass insert into the hole should be possible without heat with a properly sized hole. Pressing an unheated brass insert into a correctly sized hole should result in the knurling of the brass insert self-aligning against the face of the part.

### Actual Results/How It Does Work:
Hole size in OH4A8A2-10 - DISP_BUTTON_BASE is only 0.177in.

Inserting an 8-32 Brass Insert is not possible without heat. Heating the insert allows insertion, but forces a large volume of plastic through the back of the hole, preventing screw insertion.

### Screenshots:
![image](https://user-images.githubusercontent.com/22624641/221472406-643ab5b5-152c-4e45-8e1c-9bef13dbcd37.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A8A2-1 ASSY, DISPENSE BUTTON
OH4A8A2-10 - DISP_BUTTON_BASE

**Comment by jrsteensen** [comment]
Fixed in LC v138
