### ISSUE TITLE
Ejection Seat Tube Properties

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#635]
### Summary:
Update ejection seat tube properties material name to reflect it's designed to use schedule 40 PVC.

### Expected Results/How It Should Work:
Material Name Schedule 40 PVC

### Actual Results/How It Does Work:
Current Properties:

	Part Number	OH3A2-103
	Part Name	OH3A2-103 - DROGUE DEPLOYMENT CATAPULT BODY
	Description	DROGUE DEPLOYMENT CATAPULT BODY
	Material Name	N/A

	Part Number	OH3A2-201
	Part Name	OH3A2-201 - PARACHUTE DEPLOYMENT ROCKET BODY
	Description	PARACHUTE DEPLOYMENT ROCKET BODY
	Material Name	N/A

	Part Number	OH3A2-11
	Part Name	OH3A2-11 - SEAT CATAPULT
	Description	SEAT CATAPULT
	Material Name	N/A

### Screenshots:
![image](https://user-images.githubusercontent.com/47125808/221639695-fe73d400-939d-4216-b92e-5b34bc34c1ba.png)

### Category:

- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [X] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [X] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH3A2-103 - DROGUE DEPLOYMENT CATAPULT BODY
OH3A2-201 - PARACHUTE DEPLOYMENT ROCKET BODY
OH3A2-11 - SEAT CATAPULT

**Comment by jrsteensen** [comment]
Fixed in CT v39.
