### ISSUE TITLE
OH4A1A1-49 - LEFT AUX SUPPORT BRACKET Interference with OH4A1A1-45 LEFT AUX PANEL Mounting Hardware

### ISSUE THREAD

**Issue by ajmilner85** [jrsteensen/OpenHornet#636]
### Summary:
The bottom right #6-32 X 0.5" pan head screw (Component 91249A148 - PHS, #6-32 X .50, 18-8, BLK v1:11 in the F360 Browser) used to mount the LEFT AUX PANEL intersects with the LEFT AUX SUPPORT BRACKET body. Suggest adding a recess in the LEFT AUX SUPPORT BRACKET to accommodate the full length of the 0.5" screw or designate shorter hardware.

### Screenshots:
![image](https://user-images.githubusercontent.com/22624641/222015716-44af4778-ab3b-431c-8a34-0acf1d681375.png)
![image](https://user-images.githubusercontent.com/22624641/222017057-736f8b75-f4a6-4dd6-add0-70bad8bac03a.png)
![image](https://user-images.githubusercontent.com/22624641/222017109-4d11d132-a604-4292-8d15-0d3fcbecc016.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A1A1-49 LEFT AUX SUPPORT BRACKET

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/227755321-c8e5c976-e3e5-46ba-8d89-0ca4d5869528.png)

**Comment by jrsteensen** [comment]
Fixed in LC v138
