### ISSUE TITLE
RWR control: rotary switch nut missing, legend plate cutout too small for standard nut

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#637]
### Summary:
The nut of the rotary switch is missing in the plans, therefore it isn't obvious the standard nut doesn't fit the cutout.

### Expected Results/How It Should Work:
Either we need to find a smaller, non-standard nut or the cutout needs to be larger for it to fit.

### Actual Results/How It Does Work:
At the moment the switch's standard nut doesn't fit the cutout.

### Screenshots:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/62520296/222892354-90b81ea4-7379-41e5-bcaa-4075177185f7.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH2A4A1-11 RWR control panel legend plate

**Comment by jrsteensen** [comment]
@Lazarus64 is claiming this one.

**Comment by Lazarus94** [comment]
Fixed in LIP V98

**Comment by jrsteensen** [comment]
Small correction: This is how the file properties should look - only a part number in the part number field, only description in the description field, and combined/separated in a dash in the part name.
![image](https://user-images.githubusercontent.com/2449496/227799835-8d939faa-ce4e-4722-a9e2-12363d2a7926.png)

Fixed in LIP v99
