### ISSUE TITLE
OH4A6A1-102 - RUD TRIM, UPPER BRACKET - 6-32 Insert Holes Oversized

### ISSUE THREAD

**Issue by ajmilner85** [jrsteensen/OpenHornet#638]
### Summary:
Holes for 6-32 Brass Inserts on the Upper Bracket faces that mate with the Lower Mount Plate are oversized.

### Expected Results/How It Should Work:
Hole size for 6-32 Brass Inserts should be 0.22 in, and should be the same throughout the model.

### Actual Results/How It Does Work:
Hole sizes in OH4A6A1-102 RUD TRIM, UPPER BRACKET vary. On the face adjacent to the FCS Panel Backplate the holes are 0.22 in. The holes on the face adjacent to the Lower Mount Plate are 0.227 in. When printed, these larger holes allow the Brass Inserts to be press fit without any heat, casting their holding strength in doubt.

### Screenshots:
Upper Surface (Adjacent to FCS Panel Backplate)
![image](https://user-images.githubusercontent.com/22624641/222930561-d53314b7-3535-476e-854e-9e9386d7af00.png)

Lower Surface (Adjacent to Lower Mount Plate)
![image](https://user-images.githubusercontent.com/22624641/222930592-b4233fbc-ebd4-457c-bf03-4cc8257ceed6.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A6A1-102 - RUD TRIM, UPPER BRACKET

**Comment by jrsteensen** [comment]
Fixed in LC v132
