### ISSUE TITLE
OH4A6A1-100 RUDDER TRIM MECHANISM - PRM162-K420K-103B1 Motorized Potentiometer Deformed by Pinion Gear Set Screw

### ISSUE THREAD

**Issue by ajmilner85** [jrsteensen/OpenHornet#639]
### Summary:
The PRM162-K420K-103B1 Motorized Potentiometer used in the Rudder Trim Mechanism has a knurled shaft with a slot approx 0.039" wide that makes it easy to deform when tightening the pinion gear set screw. If the shaft becomes deformed, the pinion gear does not run concentrically. A spacer is needed to fill the slot so that the shaft does not deform when fixing the pinion gear set screw.

A simple rectangular spacer 0.2250" x 0.3875" x 0.039" is sufficient to fill the slot.

### Screenshots:
The slot in the knurled shaft. 
![image](https://user-images.githubusercontent.com/22624641/222930819-574f1988-4ca5-418c-a251-e4fcd30f2e05.png)

3D Printed Spacer
![image](https://user-images.githubusercontent.com/22624641/222931145-71bf503a-ca21-4ec0-9ff6-27885eac6949.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A6A1-100 RUDDER TRIM MECHANISM

**Comment by jrsteensen** [comment]
Fixed in LC v132
