### ISSUE TITLE
Text on RWR CONTROL LEGEND COVER, ALR-67 PWR vs Legend plate

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#640]
### Summary:
Button text on clear acrylic cover vs the legend plate.

### Expected Results/How It Should Work:
The text should be on the legend plate

### Actual Results/How It Does Work:
Part of the button text is on the clear legend plate.

### Screenshots:
![image](https://user-images.githubusercontent.com/47125808/225047370-0be80836-b96d-42ba-883f-f3820fe9efa6.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH2A4A1-502 - RWR CONTROL LEGEND COVER, ALR-67 PWR
OH2A4A1-503 - RWR CONTROL LEGEND, ON

**Comment by jrsteensen** [comment]
Designed as intended. ALR-67 POWER should always be visible in white legend, with the ON being the indicator legend.
