### ISSUE TITLE
HUD Panel missing engravings for backlighting of knobs

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#643]
### Summary:
All 4 Knobs on the HUD panel should be backlit but there is no engraving to allow backlight to come thru

### Expected Results/How It Should Work:
Knobs should be backlit.

### Actual Results/How It Does Work:
no engraving to allow backlight to come thru prevents knobs from be lit up
### Screenshots:

![2023-03-27_11-49-25](https://user-images.githubusercontent.com/19305697/227997609-c386368b-086b-4387-a861-841e0ce3aa12.png)
![2023-03-27_11-52-17](https://user-images.githubusercontent.com/19305697/227997612-f4fccdc2-0a11-4b43-b2af-324008f2a072.png)
![2023-03-27_11-05-49](https://user-images.githubusercontent.com/19305697/227997605-befb5721-d545-4b78-bae3-1fb2239f3b3e.png)

### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library

### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation

### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [X] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
- [ ] 
### Associated Filename(s):
OH1A7-1 - ASSY, PANEL, HUD

**Comment by kbastronomics** [comment]
Fixed in UIP v75

**Comment by jrsteensen** [comment]
Closed with Sandra's fix.
