### ISSUE TITLE
UFC v5.5

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#644]
## Justification
The UFC v5 IO Expander (AW9523BTQR) IC is End Of Life (EOL). That said, there are about 25k of them still available so no pressing need for a redesign for Beta1.

**UPDATE 04/03/2023: Found an issue with reversal of level shifters. Busses A need to be reversed with bus B, and OE tied to 3.3V instead of GND. Critical, breaking issue.**

## Requirements
- [x] #595
  - This is not a breaking issue, since we install the displays with a standoff from the actual PCB.
- [x] #596
  ![image](https://user-images.githubusercontent.com/2449496/229680417-c107286b-fa49-4403-8c46-f59c18a2610c.png)
- [x] #659 
  - This is a critical, breaking issue that must be resolved.
- [x] Find a suitable replacement for AW9523BTQR IO Expander with a similar form factor and capability.
  - Option 1: [TCA8418RTWR](https://jlcpcb.com/partdetail/TexasInstruments-TCA8418RTWR/C138713)
    - Using to scan buttons, and source GO and NO-GO LEDs which do not require PWM brightness control.
    - Will use a PCA9555RGER for AP PCB 
- [x] Drive Panel and Switch BL from PWM line from ESP32 with diode level shifter (or...IC level shifter?)
      ![Image](https://user-images.githubusercontent.com/2449496/229661936-177e8611-33ce-4a8f-a78f-9ba66460d960.png)
- [x] Require no UFC MCAD changes (drop-in replacement)
- [x] Add a 5V PWR LED
- [x] Add a 3.3V PWR LED
- [x] Add reverse polarity protection on 5V line.
- [x] Use native SDA/SCL lines on microcontroller.
- [x] Update AP board with new IO expander.
- [x] Move encoders directly to ESP32. No level shifters required. ([Source](https://www.reddit.com/r/AskElectronics/comments/aorj6d/can_a_pec11r_rotary_encoder_be_driven_with_33v/))
- [x] Drive pots on ESP-provided 3.3v. No level shifters required.
- [x] Add 100nF pots from analog pin to GND.
- [x] If possible, group pin headers better than having them randomly scattered all over the PCB.

@kbastronomics please chime in as necessary so we can start hammering out requirements.

### Timeline: 
Prior to Beta1

## Dependencies
#592 is a blocking dependency.

**Comment by jrsteensen** [comment]
Evaluate the following IO Expanders for use with the UFC:
https://jlcpcb.com/partdetail/TexasInstruments-TCA8418RTWR/C138713
https://jlcpcb.com/partdetail/TexasInstruments-TCA6408ARSVR/C2649390
https://jlcpcb.com/partdetail/TexasInstruments-PCA9555RGER/C2652275
https://jlcpcb.com/partdetail/TexasInstruments-TCA6416ARTWR/C182336
https://jlcpcb.com/partdetail/Onsemi-FXL6408UMX/C457770
https://jlcpcb.com/partdetail/TexasInstruments-PCF8574RGTR/C2652270
https://jlcpcb.com/partdetail/NxpSemicon-PCA9557BS118/C2652288

**Comment by kbastronomics** [comment]
TCA8418RTWR supports keyboard  matrix with 18 IO in hardware which is perfect for the UFC.
the UFC is basically a DSKY (if you know the reference) having key scanning in hardware vs doing thru bit banging a IO multplex will make for more reliable code from my POV..   we can drive the backlight from the processor.

a 5x4 matrix will cover the UFC itself,   you can then add either the AP keys directly or put a TCA6408ARSVR on the AP board

**Comment by jrsteensen** [comment]
> TCA8418RTWR supports keyboard matrix with 18 IO in hardware which is perfect for the UFC. the UFC is basically a DSKY (if you know the reference) having key scanning in hardware vs doing thru bit banging a IO multplex will make for more reliable code from my POV.. we can drive the backlight from the processor.
> 
> a 5x4 matrix will cover the UFC itself, you can then add either the AP keys directly or put a TCA6408ARSVR on the AP board

The only problem with the TCA, is that its 3.3v and not 5v tolerant. So now I have to run a 3.3v and 5v i2c network, and complicates routing on the board if I locate the IC near the micro instead of in the 5V power fill zones.

I'm not entirely sure if I get your bitbanging issue - there are Arduino libraries already existing for these IO expanders that make them pretty transparent from a programming standpoint?

**Comment by jrsteensen** [comment]
[UFC_Main.zip](https://github.com/jrsteensen/OpenHornet/files/11172411/UFC_Main.zip)
For schematic review

**Comment by jrsteensen** [comment]
Redlines implemented as discussed, PCB routed. For review.

[UFC_Main-CHK2-Routed.zip](https://github.com/jrsteensen/OpenHornet/files/11175125/UFC_Main-CHK2-Routed.zip)

**Comment by kbastronomics** [comment]
So far looking good,
**Encourage anyone with PCB experience to take a look**

**Comment by jrsteensen** [comment]
Yes, please. Any and all eyes we can get on this the better.

**Comment by jrsteensen** [comment]
![image](https://user-images.githubusercontent.com/2449496/230558964-0c3b6c2e-943c-4434-8402-9dd84b4783fe.png)
![image](https://user-images.githubusercontent.com/2449496/230558977-13c01d14-337f-4f1c-ba1c-3a1d1c5534db.png)

- [ ] Verify, and likely fix and reroute footprint for TCA. Verify all other footprints.

**Comment by jrsteensen** [comment]
Its correct as is. Its on the back face, rotated 180*. Got a little ahead of myself at 0100 local.

**Comment by jrsteensen** [comment]
Production candidate files

[UFC_Main.zip](https://github.com/jrsteensen/OpenHornet/files/11181731/UFC_Main.zip)
[UFC_Function Select.zip](https://github.com/jrsteensen/OpenHornet/files/11181739/UFC_Function.Select.zip)

**Comment by jrsteensen** [comment]
Prototype PCBs ordered. Considering this closed.
