### ISSUE TITLE
Integrate latest SEL JETT PCB to Left AUX Console

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#646]
Get and integrate the latest SEL JETT PCB into the SEL JETT ASSY and Left AUX Console.

**Comment by jrsteensen** [comment]
This issue should also include #657 fix

**Comment by Exprezz0** [comment]
Left Aux Panel updated to receive PCB Revision 4.  
-inlay adjusted to fit PCB, specifically in top left corner where PCB was exposed and collided with Left Rib (A?)
-8x32 PHS mounting screw in bottom right corner (hidden by PCB) countersunk to prevent collision with PCB.
-Hole added to accept Ready LED on PCB (closed in different issue)
-Left Aux Panel interior wall adjusted (.1-.2in) to close exposed gap from PCB/Backlight panel.  Doesn't collide or prevent SEL JETT ASSY from connecting.

![image](https://user-images.githubusercontent.com/81926396/232337758-0685844a-5813-4566-ac51-5b5d1b35e515.png)

![image](https://user-images.githubusercontent.com/81926396/232338347-0ac047aa-a96a-4e57-b442-e7e85bd9bf29.png)

Should be ready for #514 once reviewed.
