### ISSUE TITLE
Create Drawing: OH4A10-1 - ASSY, TRANSDUCER GAIN REMOTE

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#651]
Create Drawing: OH4A10-1 - ASSY, TRANSDUCER GAIN REMOTE

**Comment by Lazarus94** [comment]
Add to project OpenHornet v1.0.0-beta1 Release

**Comment by Lazarus94** [comment]
IN CHECK

[OH4A10-1 - ASSY, TRANSDUCER GAIN REMOTE v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11129690/OH4A10-1.-.ASSY.TRANSDUCER.GAIN.REMOTE.v1.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK
![image](https://user-images.githubusercontent.com/2449496/229306568-1a506cdc-cfc5-46a3-9c80-a03a313bab39.png)

**Comment by jrsteensen** [comment]
Incorporated backcheck comments, added to RC release package, and closed.

[OH4A10-1 - ASSY, TRANSDUCER GAIN REMOTE_-_v3.pdf](https://github.com/jrsteensen/OpenHornet/files/11132973/OH4A10-1.-.ASSY.TRANSDUCER.GAIN.REMOTE_-_v3.pdf)
