### ISSUE TITLE
OH4A9-205 - ASSY, OUTBOARD THROTTLE GRIP - P3-11122 Button Retaining Washer Too Small

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#653]
### Summary:
The spec’d 90618A200 washer between the two P3-11122 is too small to retain both in the throttle grip.

### Expected Results/How It Should Work:
The washer should be large enough to retain both buttons at the same time while being able to tighten the retaining screw.  To overcome a modified washer 96765A115 filed down on two edges will span more of both buttons making it easy to assemble.

### Actual Results/How It Does Work:
The spec'd washer barley spans the gap let alone cover the button boddies.  It will not retain both and shifts easily while tightening the retaining screw.

### Screenshots:

Spec'd screw
![](https://cdn.discordapp.com/attachments/1078030751838257233/1091847587251900426/IMG_0314.jpg)

One potential workaround
![](https://cdn.discordapp.com/attachments/1078030751838257233/1091847587851681812/IMG_0316.jpg)
## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Fixed in throttle quadrant v20
