### ISSUE TITLE
HUD Panel PCB

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#654]
HUD Panel has a poor distribution of LEDs and several interfere with the potentiometer nuts.

Redesign BL PCB for HUD Panel

![Image](https://user-images.githubusercontent.com/2449496/229367605-0df1880c-7ff3-4d54-8246-4eeb157231f3.png)

**Comment by Exprezz0** [comment]
Fixed with cbd3a8d2b94fde9d1af5b288b04dab8aa95fb0d0.  Will be implemented with #592.
