### ISSUE TITLE
Spin Recovery Panel missing HMD Knob backlight engraving

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#661]
### Summary:
The HMD Knob on the spin recovery panel is missing the backlight engraving.

### Expected Results/How It Should Work:
The PCB is designed to backlight the HMD Knob and should be backlit

### Actual Results/How It Does Work:
The PCB is designed to backlight the HMD Knob and should be backlit but no engraving exists to allow the backlight to pass and illuminate the knob

### Screenshots:
![image](https://user-images.githubusercontent.com/19305697/229955563-5caacfd0-adef-4553-9570-d599b6af6aa9.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [X] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH1A6-1 - ASSY, PANEL, SPIN RECOVERY

**Comment by jrsteensen** [comment]
Fixed in SPIN PANEL v16
