### ISSUE TITLE
OH5A2A2-13 - WING FOLD .250 SHAFT - Material Change Needed

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#662]
### Summary:
OH5A2A2-13 - WING FOLD .250 SHAFT not durable enough as PETG.

### Expected Results/How It Should Work:
The wing fold shaft needs to be stronger to withstand repeated pull/rotation movements.  PETG printed part will shear between the layers.

### Actual Results/How It Does Work:
A printed shaft breaks after a small number of movements.  Swapping out for aluminum rod still makes the part accessible to build, but more robust.

### Screenshots:
*Pictures are worth 1000 words. Take some screen grabs of the model, circle things with the snipping tool...you can't put too much info here.

![image](https://user-images.githubusercontent.com/47125808/230134966-5a20c23c-38fa-4ba3-858c-dafc0eadacda.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Fixed in v10
