### ISSUE TITLE
Sim Pwr lightplate too thin

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#663]
### Summary:
The Sim Pwr lightplate is 0.125 in, it should be 0.188 according to the pit's standard.
Also, its name is still "Swgnd Pwr" (obsolete).

### Screenshots:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/62520296/230473943-cc69a519-5353-4bb9-a4c6-0d527acfd3b4.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH10A1A1-12 - Swgnd Pwr Lightplate

**Comment by jrsteensen** [comment]
Fixed SIM PWR PANEL v18
