### ISSUE TITLE
Park Break Mech Body: Extrusions in holes for brass inserts

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#664]
### Summary:
There is surplus material in the holes for the brass inserts in the main body, as a result from the screw hole extrusion.

### Screenshots:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/62520296/230571716-fc13161a-dd7f-4ad6-9ced-05d88440d894.png">
## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A3A2-10 Parking Break Mechanism Body

**Comment by jrsteensen** [comment]
Already resolved when drawing was created last week.
