### ISSUE TITLE
Disp-EMC Panel PCB v1: capacitor too close to connectors

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#665]
### Summary:
The capacitor is inconveniently close to the connectors. For maintenance/resoldering after the connectors were soldered on the board, it is very difficult to reach the capacitor.

### Expected Results/How It Should Work:
The capacitor should be further away to have enough space for the usage of a soldering iron.

### Screenshots:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/62520296/230575384-7edadf1c-ae9e-4af5-b673-284784ab61eb.png">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [x] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
DISP-EMC Panel PCB V1

**Comment by jrsteensen** [comment]
This will not be incorporated. In general, you are correct, but it gets busy on the backface of this panel. Just rely on order of operations (solder cap then solder connectors on. If you need to replace cap, desolder connector first.
