### ISSUE TITLE
DDI/AMPCD button board PCBs: Add manufacture .txt with PCA9554 as part alternative

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#674]
### Summary:
At JLCPCB the TCA9554PWR is often in too few numbers in stock for a group buy of AMPCD button board PCBs.
Add manufacture .txt with PCA9554 as part alternative in release folder.

**Comment by jrsteensen** [comment]
Is there any programming considerations, or is it a true drop-in equivalent?

**Comment by kbastronomics** [comment]
the PCA is the old version of the IC,   TCA is replacing it,  TCA is a drop in replacement for the PCA

**Comment by kbastronomics** [comment]
Be sure to specify PCA9554PWR so the correct package is used if this is done

**Comment by Exprezz0** [comment]
Added "Important Manufacturing Instructions.txt" to both DDI/AMPCD PCB folders.  Will be implemented with #592
