### ISSUE TITLE
OH4A7A-11 ANT SEL - Should have 3 positon switches

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#675]
### Summary:
In DCS the ANT SEL panel uses 3 position switches: comm 1 = lower, auto, upper; IFF = lower, both, upper

### Expected Results/How It Should Work:
To fully control the pit the switches should be replaced with the 3-position version.  The interconnect diagram will also need to be updated to account for connecting each switch to 2 pins each on the mega.

### Actual Results/How It Does Work:
The design uses 2 position switches so cannot easily control all the available positions in DCS.

### Screenshots:

![IMG_0336](https://user-images.githubusercontent.com/47125808/230786920-ca250552-7506-4a6e-a784-5577e1644d2e.jpg)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A7A-11 ANT SEL - COMM1 and IFF switches.

**Comment by jrsteensen** [comment]
Verified, and should be incorporated.

- [ ] Update model
- [ ] Update drawing

**Comment by Exprezz0** [comment]
ANT SEL PCB has been updated and will be pushed with #592 PR.
Back Plate needs to be cutout still for F360 Model.

**Comment by jrsteensen** [comment]
Great team effort there, thanks @Exprezz0! Closed with latest commit. (PCB native files will be brought in with #592.)
