### ISSUE TITLE
OH4A9202 - Outboard Throttle Grip Adapter Spacer - slot too narrow for 90176A115 spacer.

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#676]
### Summary:
OH4A9202 - Outboard Throttle Grip Adapter Spacer - slot too narrow for 90176A115 spacer.  The same slot on the inboard grip adapter is perfect.

### Expected Results/How It Should Work:
The spacer should fit in the slot with enough clearance to travel up and down with the finger lift movement.  The spacer drops in to the inboard grip adapter easily with enough clearance to move easily.

### Actual Results/How It Does Work:
The outboard grip adapter is narrower than the spacer.  Even with filing and manual cutting will take additional work to get a good result.

### Screenshots:
Outboard grip with .17" clearance:
![image](https://user-images.githubusercontent.com/47125808/230965117-f5622b24-c1ea-4a87-adc2-08d72f076014.png)

Inboard grip with .198" clearance
![image](https://user-images.githubusercontent.com/47125808/230965277-1ad40f4c-8414-4424-a0eb-6a5d9314402a.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [x] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A9202 - Outboard Throttle Grip Adapter Spacer

**Comment by jrsteensen** [comment]
Closed in Throttle v21
