### ISSUE TITLE
Throttle Finger Lift Lower retaining washer is too small.

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#678]
### Summary:
The finger lifts' lower retaining screw's washer 90618A200 is too small.

### Expected Results/How It Should Work:
The washer should ride on top of the finger lift to allow the movement to not bind or have the washer slip below the surface causing it to dig into the opening.

### Actual Results/How It Does Work:
The washer is too small so it falls below the surface and digs into the finger lift.  This causes the lift to bind and not spring back down freely.  Swapping the spec'd washer out for 96765A115 gives better results.

### Screenshots:
Finger lift on the right has the spec'd washer.  The one on the left is what I found for a quick test/comparison.
![image](https://user-images.githubusercontent.com/47125808/231219627-18900844-5fa2-48eb-b34f-dab4856ccf9c.png)

This is the 96765A115 washer that would look better and is wide enough to cover slot without binding.
![image](https://user-images.githubusercontent.com/47125808/231220214-101dc63c-be9a-4b71-95d2-da4f48708a8f.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [x] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A9-204 - Outboard Finger Lift
OH4A9-104 - Inboard Finger Lift

**Comment by jrsteensen** [comment]
Fixed in Throttle v21
