### ISSUE TITLE
AV COOL minifit connectors detached in model

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#682]
### Summary:
The PCB model is broken. 

### Screenshots:
![Screenshot (532)](https://user-images.githubusercontent.com/68113057/231714714-e9fa381f-cc99-4fd4-85e8-d41232e50e92.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A3-1 - ASSY, AV COOL SWITCH

**Comment by Higgins-OH** [comment]
Isn't that thought as a reminder to use pigtails, like with the landing gear PCB?

**Comment by jrsteensen** [comment]
Its an indicator to pigtail the connectors. Model is not broken. Correct as-is, and pigtails should be called out on the drawing.
