### ISSUE TITLE
Create Drawing: OH4A6A1-100 - ASSY, RUDDER TRIM MECHANISM

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#688]
Create Drawing: OH4A6A1-100 - ASSY, RUDDER TRIM MECHANISM

**Comment by Lazarus94** [comment]
Closed as can be incorporated into FCS panel drawing.

**Comment by Lazarus94** [comment]
IN CHECK

[OH4A6A1-100 - RUDDER TRIM MECHANISM  v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11239572/OH4A6A1-100.-.RUDDER.TRIM.MECHANISM.v4.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

[OH4A6A1-100 - RUDDER TRIM MECHANISM_-_v4-CHK1.pdf](https://github.com/jrsteensen/OpenHornet/files/11243069/OH4A6A1-100.-.RUDDER.TRIM.MECHANISM_-_v4-CHK1.pdf)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH4A6A1-100 - RUDDER TRIM MECHANISM v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11264394/OH4A6A1-100.-.RUDDER.TRIM.MECHANISM.v5.pdf)

**Comment by jrsteensen** [comment]
Show on separate sheets so you can give them dedicated Parts lists
Ensure dash numbers are the dash number of the part.
![Image](https://user-images.githubusercontent.com/2449496/233666865-978d6563-eadc-42a8-bb0e-f7f9d2a7a097.png)
![Image](https://user-images.githubusercontent.com/2449496/233667143-2d6e959f-4cae-473d-aa02-9d2c7a3a0f94.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH4A6A1-100 - RUDDER TRIM MECHANISM v6.pdf](https://github.com/jrsteensen/OpenHornet/files/11300502/OH4A6A1-100.-.RUDDER.TRIM.MECHANISM.v6.pdf)

**Comment by jrsteensen** [comment]
Made required changes, and added to RC Release Package

[OH4A6A1-100 - RUDDER TRIM MECHANISM_-_v8.pdf](https://github.com/jrsteensen/OpenHornet/files/11302018/OH4A6A1-100.-.RUDDER.TRIM.MECHANISM_-_v8.pdf)
