### ISSUE TITLE
Throttle Control Board Missing I2C Pullup Resistors

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#700]
### Summary:
Per I2C specification the SDA/SCL lines require a external pullup resistor on each line.  These pull up resistors if missing will cause I2c to function correctly due to they're being open collector.

### Expected Results/How It Should Work:
Required components per specification must be included.

### Actual Results/How It Does Work:
While reports indicate the board is functioning ok.  to insure there will be no issues for any user the resistors need to be included.
the datasheet shows 10K pullup

### Screenshots:
![image](https://user-images.githubusercontent.com/19305697/232546029-81e067a9-ba95-4eea-923a-b473cc65eaf6.png)

Sample connection for TCA chip showing pull-ups.  they show 10K0 here but 4K7 would also work.
![image](https://user-images.githubusercontent.com/19305697/232546085-7b34d65a-fc7e-4586-af4e-dc417d99e4cd.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [X] Throttle
- [ ] General Software
### Associated Filename(s):
throttle_controller.pro

**Comment by jrsteensen** [comment]
- [ ] Convert PCB to S2 MINI Microcontroller
- [ ] Remove Servo Connections (ATC will be implemented as future separate PCB)
- [ ] Possibly eliminate TCA on PCB due to extra IO of S2 Mini and freed up IO from removal of Servo Connections.
- [ ] Add i2c connection so future ATC PCB can get positional feedback directly from the throttle.
- [ ] Add 3.3V to 5V Level Shifter if necessary.

**Comment by jrsteensen** [comment]
Closed with ee4fbd840e3a8fc679fb13a4bc6513163ceb31bc
