### ISSUE TITLE
UFC 6.0 Update

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#702]
## v5.5 Testing
- [x] Microcontroller powers on
- [x] i2c devices detected (with AP KB PCB connected)
  - UFC GPIO expander detected at 0x34
  - AP KB GPIO expander detected at 0x20
- [x] Keypad pushbutton functionality tested
  - EMCON Switch state changes not detected - Troubleshooting if bad component or PCB issue.
  - Failure determined to be manufacturing defect in PCB, 2x other PCBs did not have defect.
- [ ] Keypad Interrupt Capability Tested
- [ ] VOL 1 pot/VOL2 pot/BRT pot tested
- [ ] Encoder CHAN1/2 tested.
- [x] ADF Toggle Tested
- [ ] HUD BIT pushbuttons tested
- [ ] HUD BIT indicator tested (GO/NOGO)
- [ ] Scratchpad BL tested
- [ ] Scratchpad Display Tested
- [ ] OPT Displays tested
- [ ] COMM Displays tested
- [ ] OPT/COMM Display Dimming Tested
- [ ] UFC Main BL functionality tested
- [x] AP KB pushbuttons tested
- [ ] AP BL tested

## Observations
When PWM is applied to PNL_BL (GPIO 9), all LEDs fade except for key switches, D3 and D34, which remain always on. Keyswitches are medium brightness, D3 is considerably brighter than the keyswitches, and D34 is blindingly bright.

**Comment by kbastronomics** [comment]
on this item
"On spare microcontroller IO, add a two pin header with jumper for software config (DCS-BIOS vs HID/Joystick inputs)"
instead of using an I/O port for this why not PRESS and HOLD I/P BUTTON at POWER UP to select DCS-BIOS, PRESS and HOLD ECM Button to select HID,  I can remember the selection until it's changed

**Comment by SCUBA82** [comment]
Regarding the backlight observations: 

As already mentioned on discord all MOSEFTs (Q1,Q2,Q3) have their source and drain pins swapped. 

This is a screenshot of the original schematic 
![Mosfet-Ori](https://github.com/jrsteensen/OpenHornet/assets/1401408/e1f6c150-95c4-4546-81f5-283f7fafa9de)

and here how it should be ...

![Mosfet-Mod](https://github.com/jrsteensen/OpenHornet/assets/1401408/a4915e02-3def-457f-b07e-f161247cb839)

**BL LEDS general:** 
Each BL LED pair should be current limited with an resistor. Around  33Ohm / pair.

**LEDs D3 and D34:** 

The resistor value of D34 seems to be undersized. It should be around 110 Ohm.
D3 is connected in series with LED of the IP switch. Since the switche LEDs have a different forward voltag than the other BL LEDs D3 is brigther. 

Switch LED brightness:
I've tested generic Aliexpress switches and also noticed that their LEDs are much dimmer. Testing them with different voltages outsided of the UFC PCB showed that I can not make them much brighter. So I don't think there's a major issue with them (besides the current limiting resistors)

**Comment by jrsteensen** [comment]
# v5.6 PCB
## Requirements
### UFC PCB

- [ ] Update BL Circuit so all LEDs light evenly, and are controlled by a single PWM pin from the microcontroller. (KB will remain a separate line.)
- [x] Reverse K/A pins of the SCR BL. (K/1 = SCR_BL; A/2 = +5V)
- [ ] Add Silkscreen for K/A markings.
- [ ] Add resistor to SCR BL net, 20ohm, .5 watt.
- [ ] On spare microcontroller IO, add a two pin header with jumper for software config (DCS-BIOS vs HID/Joystick inputs)
- [ ] Additional two pin headers for additional config?
- [ ] Change analog input to correct pot pin order. 
  - Flip pins 2&3 on J3,J4 and J8 that will move the signal to the center pin and 3.3V to the outer pin.
- [ ] Add 2-3 more TP to GND for convenience during debug.
- [ ] Isolate and switch between VSUB and EXT PWR automatically when EXT PWR is applied.
  ![image](https://user-images.githubusercontent.com/2449496/234437014-592a73cb-c486-48fd-a110-ff3cddd9d95c.png)
- [ ] Add level switched input to spare ESP32 GPIO from EXT PWR (to notify ESP32 when EXT PWR) is applied.
  - Intent is to disable backlight (or limit to low brightness) and limit display brightness so UFC function is preserved when running on USB connection only.
- [ ] Add IRQ line for AP KB GPIO Expander (Replace one GND)
- [ ] Add diodes to key switches/switch matrix to prevent ghosting from multiple simultaneous keypresses. (If possible, not critical for Hornet use case.)


### AP KB PCB

- [ ] Add DNP 4k7 pullup resistors on SDA/SCL lines. 
  - Make DNP, and manually install for debug/testing purposes only.
- [ ] Add IRQ line for AP KB GPIO Expander (Replace one GND)

**Comment by kbastronomics** [comment]
On the LED Backlights,  The values are calculated but based on what's seen the Switch LEDs are just not as bright as the smd leds so that resistor may need to be adjusted.

the **Keyboard/Function Select Daughterboard** is duplicated in the **UFC_Function Select PCB (Keyboard/KB)** item.   probably just remove it

I would also suggest redrawing the LED circuit so it more cleanly shows how the led are hooked up,   LEDS in parallel with each parallel branch having 2 LEDS with a series resistor.

**Comment by kbastronomics** [comment]
Instead of a DCS-BIOS vs HID/Joystick config .   we have to use DCS-BIOS for Backlighting and the Displays so that's a given.  the question then is what about the buttons.   let just go HID as Joystick buttons, all the knobs will be axis and then not worry about configuring anything?

**Comment by jrsteensen** [comment]
> Instead of a DCS-BIOS vs HID/Joystick config . we have to use DCS-BIOS for Backlighting and the Displays so that's a given. the question then is what about the buttons. let just go HID as Joystick buttons, all the knobs will be axis and then not worry about configuring anything?

I'd say HID Joystick for all inputs, DCS-BIOS for all outputs from the PC to the UFC.

Is there any actual need to split the VBUS vs VCC? Or is that already handled on the S2-MINI or in the ESP32? Is there a simpler circuit? The one you took a picture of the schematic was for a high amperage application [source link](https://electronics.stackexchange.com/questions/274338/automatic-switching-between-external-5v-and-usb-bus-power-supplies)
  ![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/4cbe7b46-62dc-4a61-b0ad-0a1e523771e9)

I was thinking of just doing something simple like this:
  ![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/05651f48-0c58-43f5-a6bc-2d023e1c1e6d)

This way we can sense when we have external power which is passed through a spare channel on the level splitter without any further components to a spare IO on the MC. Space is at an absolute premium to keep this a 2 layer PCB.

**Comment by kbastronomics** [comment]
So looking at the S3 schematic,  VBUS goes thru a 3v3 regulator then direct to the VDD lines on the processor. then it also goes to a pin on the S2's header.   the +5V is VBUS   so if you supply +5v and tie to the VBUS you have VBUS being supplied by the PC and a external power source.   probably not a good idea. it won't damage the ESP32 but it could damage the PC.  The ESP32 itself does not use the +5v supply except to be regulated down to 3V3.

so we should protect VBUS and not allow the external supply feed VBUS

**Comment by jrsteensen** [comment]
Okay, is there a simpler circuit? 

Or using the original one, smaller MOSFETs you would recommend for the BSS84/SP247N60S5? (Well stocked by JLC?)

**Comment by kbastronomics** [comment]
depends on what the objective is.   
1.  don't' hook the EXT 5V to VBUS.  since we have to connect to DCS-BIOS the S2 will get its 3V3 thru VBUS which is what is output on pin32 of the S2.  it's not a input pin,  it's a output of VBUS
2. we need to allow either VBUS or 5V external to supply the 5V logic. in that case run 5v thru a Schottky and vbus thru one as well,  that will prevent ext from sending 5V to VBUS but allow either to suppo then combine the output to the +5V supply, 
3. need to select EXT 5v or VBUS to supply 5V rail.  but also allow 5V or VBUS to supply S2.  this is the more complicated circuit

**Comment by jrsteensen** [comment]
@kbastronomics 
@SCUBA82 

Just posting this for a review:
![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/d4098b54-bdb3-4347-96a9-68946d6a9c47)
Please pay close attention to the polarity of the FETs.

Intent is to switch between VBUS and VCC, send a 3.3V signal to the microcontroller to tell it that external power has been applied (to unlock full backlight/display brightness range), and have a external power status LED.

**Comment by SCUBA82** [comment]
@jrsteensen  Sorry can't help with your review request but there are 2 other topics I'm thinking about: 

**GN1640T U5/U6 (COMM 1/2 Displays) connection**
For me it's not clear why the SEG pins on U5 and U6 are connected differently (other pins / reverse order).

![grafik](https://github.com/jrsteensen/OpenHornet/assets/1401408/07860581-5462-41c1-84b4-0db1f57220fd)


I guess this is a legacy from prior UFC versions where only one GN1640T was used for both COMM displays?
Sure this can be handled in software. In my case I defined individual char arrays for both COMM displays. But I guess it would be more convenient to have them connected the same.

**Backlight LEDs **
I noticed you've specified an 33ohm resistor to each LED pair. The LEDs [datasheet ](https://datasheet.lcsc.com/szlcsc/Foshan-NationStar-Optoelectronics-FC-F1005UGK-520M5_C130723.pdf) states a typical forward voltage of 2.8V. Combining 2 LEDs together will exceed the 5V supply voltage. Not sure if it makes any difference.

**Comment by SCUBA82** [comment]
Arghh... there are characters which can't be displayed correctly on the OP Displays since A&B and E&F are combined on a single output pin.
![grafik](https://github.com/jrsteensen/OpenHornet/assets/1401408/04d57ae0-a931-4c7f-b5cf-993ba8e83819)

![grafik](https://github.com/jrsteensen/OpenHornet/assets/1401408/a57c70a2-8b1f-40b2-a927-84d6ad2f7b76)

We still have one free GRID pin on the GN1640 but need a second one...

**Comment by jrsteensen** [comment]
> Arghh... there are characters which can't be displayed correctly on the OP Displays since A&B and E&F are combined on a single output pin.
> We still have one free GRID pin on the GN1640 but need a second one...

Unfortunately this is a limitation using those ICs. I haven't found a more suitable IC, and that is the same IC that Tek is using. I made a quick bitmap to show the allowances for this:
If all segments are controlled independently:
![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/8322e10d-bd62-4420-a1e3-92b350679160)
With the tied AB/EF pins:
![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/01718a2a-1748-48bc-aba0-672765414cb5)



> @jrsteensen Sorry can't help with your review request but there are 2 other topics I'm thinking about:
> 
> **GN1640T U5/U6 (COMM 1/2 Displays) connection** For me it's not clear why the SEG pins on U5 and U6 are connected differently (other pins / reverse order).
> I guess this is a legacy from prior UFC versions where only one GN1640T was used for both COMM displays? Sure this can be handled in software. In my case I defined individual char arrays for both COMM displays. But I guess it would be more convenient to have them connected the same.

This was for routing expediency. But if it would simplify programming, I can look at reversing it?

> **Backlight LEDs ** I noticed you've specified an 33ohm resistor to each LED pair. The LEDs [datasheet ](https://datasheet.lcsc.com/szlcsc/Foshan-NationStar-Optoelectronics-FC-F1005UGK-520M5_C130723.pdf) states a typical forward voltage of 2.8V. Combining 2 LEDs together will exceed the 5V supply voltage. Not sure if it makes any difference.

The issue is when we get the key switch LEDs as part of the pair - might need to just add them when one or two of those LEDs are making up the pair.

**Comment by kbastronomics** [comment]
@SCUBA82 

The Comm displays is a nuisance but not an issue in my mind.

On the C5/D5 Pins,
Yes I brought this up previously,   opened a issue on it,   I did propose that we could C5/D5 to I/O Pins and control manually.  the other way would be to use a TCA6424A or MAX6956  to replace the GN1640T but then we have to drive it completely ourselves 

As for the character set,  yeh the driver we have is from @Tekdept

That might be a custom build of the board as a test though,  not something for beta1

The backlight LEDs 33 Ohm seems really low to me,we need to limit current to 20mA and at 5.6V/.020 = 280ohm for 2 in series and 2.7/.020=135ohm for the single.  

if anyone wants to check my math feel free

**Comment by SCUBA82** [comment]
@kbastronomics 
For my understanding the formular is : R = (Vs - Vf) / If. So (5 - (2 * 2.8)) / 0.02 = -30. So the next higher resistor value is 1Ohm.
That's why I mentioned the problematic combined forward voltage of the LEDs...

 So I guess there are 2 options. Increase source voltage for the backlights (like it's done on the DDIs). Or use one resistor for each led. 

Regarding the comm display: Since it's tested and working I guess it would be best to keep it as it is.

Regarding the OP Displays.: 
The last unused gn1640 pin could be used, in combination with an AND gate to switch B1 and E1. The only character which would be impossible to print would be "[".

I totally understand if you decide to have a feature freeze for 5.6 and having the alternative charset is realistic enough I think.

**Comment by jrsteensen** [comment]
Honestly, @SCUBA82 - I want this iteration of the UFC to be right, and hopefully never touch it again. I'm rolling an experimental version converting to WS2812 backlighting to test, with standard high force tact switches. 

If you would like to submit a redline of what that circuit would look like to fully enable the displays, I'd appreciate it. Needs to be small though. Real estate is going to be at an absolute premium.

**Comment by SCUBA82** [comment]
@jrsteensen  Referring to your character overview, segment B is only active when A is also active. The same is true for E and F. There is no combination where A + B are active while only F is active or vice versa. 
The only exception is character "[" where B and F are used explicit. So this is not a perfect solution... (Do you know in which menu it is displayed?)

So my idea is to define pin GRID16 as "B" and "E" in software. Then AND it together with GRID1 (A) and connect the output of the AND Gate to segment B of the display. This way segment B will only light up if GRID16 and GRID1 are active. 

Something like this: 
![grafik](https://github.com/jrsteensen/OpenHornet/assets/1401408/5a6ed1ed-dbff-4614-9ac7-d7758f3737fc)

**Comment by jrsteensen** [comment]
So, here is the experiment of the function select board, with WS2812B-2020 backlighting, and the high force omron tactiles. Will require a minor MCAD update for the button interface (switches are 3mm shorter than the previous ones. The goal is even, customizable backlighting to eliminate hotspots. So many LEDs are used not because we need the brightness, but because we need to be able to dim them to eliminate those hotspots. I'm sending this to @kbastronomics to order some test units, and if it works well, we will continue with updating the UFC with this.

![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/00893f1a-4ee1-48b0-ba6c-fccf4eb25346)
![image](https://github.com/jrsteensen/OpenHornet/assets/2449496/0871b6e9-798e-4006-953c-0cf15a48307b)

The cap is only 100uF compared to the usual 1000uF, but I just couldn't shoehorn it on due to physical size constraints, and figure some smoothing is better than no power smoothing.

@SCUBA82 That makes a lot of sense. I'd like @kbastronomics opinion as well as far as the complexity it brings to code. Thanks for the support!

**Comment by kbastronomics** [comment]
@SCUBA82 
I did think about doing something like that as well but wasn't sure the introduction of logic gates would be well received.
@jrsteensen This is a good solution with minimal changes to the existing library

on the UFC Function,   I take it the #LED is the Data IN for the 2312s?  should be a issue as long as they are the last one on the string (ie UFC board first then AP board) or you run a seperate IO pin for the AP board,  either works and I like it!
I wouldn't worry so much about the cap,   you could just put but the big cap on the UFC board,   you don't need one also on the AP board if running from same power supply.

**Comment by kbastronomics** [comment]
@SCUBA82 & @jrsteensen,
I did think about one thing,  the grid pins are open drain,   you can't hook up a standard TTL AND gate you'll need a open drain output one,   something like a SN74AHC1G09

**Comment by SCUBA82** [comment]
[UFC_TEST_ESP32S2.zip](https://github.com/jrsteensen/OpenHornet/files/12044225/UFC_TEST_ESP32S2.zip)

Here is my UFC v5.5 test sketch. It's by no means production ready but tests the following main features: 

[x] scratchpad -> DCS-BIOS integartion    
[x] OP Displays 1-5 -> DCS-BIOS integartion  
[x] COMM Displays 1 & 2 -> DCS-BIOS integartion 
[x] Rotary Encoder 1 & 2 -> Interrupt triggered; Serial print a counter 
[x] Keypad Matrix -> Interrupt triggered;  Serial print button name; TODO rework PRESS / RELEASE detection
[x] ADF Switch  -> Interrupt triggered;  Serial print switch status; TODO rework PRESS / RELEASE detection
[x] BIT Switch  -> Interrupt triggered;  Serial print switch status; TODO rework PRESS / RELEASE detection
[x] VOL1, VOL2, BRT potis -> Serial print values every 2 sec
[x] GO / NOGO LED -> blink GO LED 5 sec; blink NOGO LED 2 sec

**Comment by jrsteensen** [comment]
> 
> Here is my UFC v5.5 test sketch. It's by no means production ready but tests the following main features: 
> 
>  (snip)
> 

This is awesome. Thank you!

**Comment by jrsteensen** [comment]
@kbastronomics has several test articles ordered and plans a (rough) ETA of 1DEC23 to have a test article built out. (For what is now the v6 UFC PCB)

Between now and then I will update MCAD to account for the new OMRON switches and WS2812 backlighting.

**Comment by jrsteensen** [comment]
Update UFC Main PCB with:

- [ ] 1. Add 1k resistor across pins 1 & 2 of the 5X OPT Display MOSFETS
- [ ] 2. Note to use tab of display to orient COMM display modules. (Tab up!)
- [ ] 3. Change scratchpad BL to 10ohm resistor and 0-1k ohm trimpot in series. (Mount trimpot on back for accessibility.)

**Comment by jrsteensen** [comment]
Getting a new OPT Display design, which will break the cue digits out to its own digit/segment pins.

(This is tentative, and not for design reference as of now.)
![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/9d592675-a6ee-4df1-a210-0e1eb016b109)

As of now, I am moving the UFC to a future release. I don't want to wait another 6 months to launch the beta1 for OH and want to take the pressure off so we can get it right.

**Comment by jrsteensen** [comment]
### UFC_Main v6.1.0

- [ ] Replace UFCOptionDigit with UFCOptionDigitV3
- [ ] Reroute DS2 thru DS6.
- [ ] Route Cue segment/digit to spare pins on Comm1/2 as appropriate (DS2 thru DS6)
- [ ] Note to use tab of display to orient COMM display modules on schematic notes. (Tab up!)
- [ ] Change scratchpad BL to 10ohm resistor and 0-1k ohm trimpot in series. (Mount trimpot on back for accessibility - ensure clearance in 3D model.
- [ ] Update version on PCB to v6.1.0.
- [ ] Generate new manufacturing files using JLCPCB plugin tools.
- [ ] Copy manufacturing files and schematic PDF to appropriate folder in `release` folder.
- [ ] Generate new STEP file (and ensure all 3D components are populated.)

**Comment by jrsteensen** [comment]
## v6.1.1 Updates

- [ ] Increase OPT display pin holes .02mm (to give .04 total additional tolerance on vertical pin spacing.)
  - **Justification:** This batch of displays has .01-.03mm smaller vertical pin spacing between the two rows, which is still within tolerance, but our footprint is too tight. Can be installed as-is, but difficult.

**Comment by kbastronomics** [comment]
Haven't tested yet but an observation with only USB Power connected
1.  5v, and 3.3V LED are on as expected
2. EXT Power LED is on (shouldn't be??)

**Comment by SCUBA82** [comment]
### Description
As discussed on discord, the current "PWR SUPLLY SWITCH/BYPASS" design deviates from [this suggested circuite](https://electronics.stackexchange.com/questions/274338/automatic-switching-between-external-5v-and-usb-bus-power-supplies).
As a result the board was not powered correctly and issues were notified in the scratchpad area. 

### Schematics
**Here's a updated version of this circuite**
![grafik](https://github.com/user-attachments/assets/74e4cacb-1548-4cb7-8bc0-018227e9ac7f)

**PCB routing**

![grafik](https://github.com/user-attachments/assets/fc671019-a565-421d-90e5-4e6b05ed850b)

**Changes:** 
>  Schematics:
> - Q8
>    - changed Symbol to n-channel
>    - switched drain and source
>    - Updated Datasheet and description
> - Q4, Q6, Q7
>    - changed Part to SKML5203
>    - Updated Datasheet, description, LCSC and PN
>
> PCB:
> - Q8
>    - Updated routing according to schematic

### Simulation
A simulation of this circuite can be found [here](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWK0wHYwA4MDYCcAmBDfDXAZhOxABZIQkE6EBTAWjDACgB3cAkfPmrgw+AUKicASjQzjh7KoOF06telE0wEPAajHK+BiZF1lIww2TJKTZ7HMO06h0zLRUK4VFUVaaatC4-tpmFiBe+PoRYqa81p5iNnJepgAmEQ4xNGCJAuAAcgjo+JwATjF0oin4Vdiq4PBwnADmleD17R5aukJ0kdGpnADO3nl92Q0AZgCGADbDzCOy8iLGKuAgswtLAA45tsIIJKtkPVPtGP212dQQYNBnDyS1CNWv75wXZMd6Sb9Oe6PcDQF6QN5giHEL4CLB-WGOCTWEFPUHEcHvLgVZwCdQ4khyKpNUxtCj9GztH6xSQXKJJG5kykGejQLD4Km4O6lAAeAkgYlYwXZclYVGEYGEADUAEIAVQAymYbld2rgqHFVYkqicNWB+GqjKsNQT4Yy6ZJ4jdzVT4RrGeZhGa4XarXCzdEXS44fjnbp8Xi4Ea-blbiHXMHDgEXHZeHr6VV+OG2sdEUcThNVJxeawyJZqEh09Q5OLhABRAAaABUADrDAAKAHUpFn6II+Kh6G8+WpwMJq7sEJLa7o4yADYyDbr+O74zS1r3xaIx2KXCy2RyuSOlxLF+tJDIDeOxJPNOoyMCGqEKtUVthhEXNGAmiOTg+b5POPsbyGVTmkj1ryXQwOAMZ1wFqThcjEECERAO9YLENJmFmABXOYABdWDmZgMggS9YC4Np4JNB8TUzWNXzkb91VaOD72LBiegAe3AOR4LUSBcGCJAYCaXAfAQbBCE0aCUk4FiJTo09OLkHiUE2LggA)

Additionally I tested this circuite on a breadboard (with off the shelf components).
Testscenario: VBUS @ 3.3V (to make the volatge change obviouse); EXT PWR @5.12 V
Results: 
   - VBUS is distributed when no EXT PWR is supplied
   - Circuite switches to EXT PWR when supplied
   - EXT PWR LED turns on/off 
   - VCC_SNS switches 
 
**Messy Breadboard**
![IMG_20241013_230743](https://github.com/user-attachments/assets/12064d19-0854-4c5f-bf22-a63ccd7eda17)
**VBUS @ 3.3V supplied only**
![IMG_20241014_134311](https://github.com/user-attachments/assets/cea75df3-b6ed-4283-b249-a4a7bab3cf76)
**VBUS @ 3.3V and EXT PWR @ 5.12 V supplied**
![IMG_20241013_230752](https://github.com/user-attachments/assets/e48bb6f6-9c91-4c56-9962-ca6b8be4011f)
**Vaultage reading at VCC_SNS when EXT PWR supplied (0V when not)**
![IMG_20241013_230955](https://github.com/user-attachments/assets/57509eba-f83d-43ff-89a7-a6b4b6074d07)


### Repository 
[Commits ](https://github.com/jrsteensen/OpenHornet/compare/UFC_v6.1.0...SCUBA82:OpenHornet:UFC_v6.1.0) are done in my fork. Pull Request may be done but changes are really minor.
