### ISSUE TITLE
OH4A3A1-100 - Jett Switch Gear Does Not Engage Rotary Switch Head

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#703]
### Summary:
In the F360 model the Gear and grub screw are shown above the top of the switch.  Without the set screw clamping on the switch-head the switch does not rotate with the gear.

### Expected Results/How It Should Work:
The gear should turn the switch.  To ensure that it turns it should have its setscrew clamp the top of the switch in it's flat part.

### Actual Results/How It Does Work:
The set screw rides above the switch in the orientation of the gear per the design.  By flipping both gears over the set screw will engage with the switch, and will rotate the switch.

### Screenshots:
![image](https://user-images.githubusercontent.com/47125808/233725948-aa2e098b-ea25-472a-80e7-c7be88c674ed.png)

![image](https://user-images.githubusercontent.com/47125808/233726014-078b55ef-75bb-4958-a8cc-d6b0ddf1c8b8.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A3A1-100

**Comment by jrsteensen** [comment]
Reversed and relieved top bracket for clearance in SELECT JETT SWITCH MECH v46.
