### ISSUE TITLE
Create Drawing: OH5A5A1-100 - ASSY, DUAL CONCENTRIC SHAFT POTENTIOMETER

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#704]
Create Drawing OH5A5A1-100 - ASSY, DUAL CONCENTRIC SHAFT POTENTIOMETER

**Comment by Lazarus94** [comment]
Add to project

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Lazarus94** [comment]
IN CHECK



[OH5A5A1-100 - ASSY, DUAL CONCENTRIC SHAFT POTENTIOMETER v2.pdf](https://github.com/jrsteensen/OpenHornet/files/11304036/OH5A5A1-100.-.ASSY.DUAL.CONCENTRIC.SHAFT.POTENTIOMETER.v2.pdf)

**Comment by jrsteensen** [comment]
IN BACKCHECK

[OH5A5A1-100 - ASSY, DUAL CONCENTRIC SHAFT POTENTIOMETER_-_v2-CHK1.pdf](https://github.com/jrsteensen/OpenHornet/files/11304151/OH5A5A1-100.-.ASSY.DUAL.CONCENTRIC.SHAFT.POTENTIOMETER_-_v2-CHK1.pdf)

**Comment by Lazarus94** [comment]
IN BACKCHECK


[OH5A5A1-100 - ASSY, DUAL CONCENTRIC SHAFT POTENTIOMETER v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11324026/OH5A5A1-100.-.ASSY.DUAL.CONCENTRIC.SHAFT.POTENTIOMETER.v4.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release package and closed.
