### ISSUE TITLE
Create Drawing: OH5A5A1-200 - ASSY, BLEED AIR KNOB MECHANISM

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#705]
Create Drawing: OH5A5A1-200 - ASSY, BLEED AIR KNOB MECHANISM

**Comment by Lazarus94** [comment]
Add to project

**Comment by Lazarus94** [comment]
IN PROGRESS

**Comment by Exprezz0** [comment]
Fixed and saved.  Should be ready for you unless I spot something else.

**Comment by Lazarus94** [comment]
IN CHECK



[OH5A5A1-200 - ASSY, BLEED AIR KNOB MECHANISM v4.pdf](https://github.com/jrsteensen/OpenHornet/files/11383597/OH5A5A1-200.-.ASSY.BLEED.AIR.KNOB.MECHANISM.v4.pdf)

**Comment by jrsteensen** [comment]
Add the following to drawing:

- [ ] Add modification note to A12405RNZQ 4-position rotary switch to make it continuous rotation.

  1. Add a stripe between switch halves with a paint marker or torque stripe compound to establish a rotational index of the halves of the switch.
  2. Pry 4X tabs apart gently with a flat head screwdriver. (Gently locking the switch in a vice by its shaft may prove helpful.)
  3. There are two spring loaded ball bearings inside that may launch out when opened. Gently remove the cover now.
  4. As shown in the picture, there are two tabs that interface with each other to form a stop.
  5. Grind the tab off the shaft side with a small file.
  6. Carefully reassemble switch.

- [ ] Add image to drawing.

![Image](https://user-images.githubusercontent.com/2449496/192106034-7b98aa58-1c33-4686-b118-128d7d2d6c6d.png)

**Comment by jrsteensen** [comment]
IN BACKCHECK

![Image](https://user-images.githubusercontent.com/2449496/236512475-7d99bf90-b4de-4987-b1fa-a5be2d584c59.png)

Delete duplicate PL from SH2
![Image](https://user-images.githubusercontent.com/2449496/236512721-abca3b79-a283-49ce-a893-dda7d615f3eb.png)

**Comment by Lazarus94** [comment]
IN BACKCHECK

[OH5A5A1-200 - ASSY, BLEED AIR KNOB MECHANISM v5.pdf](https://github.com/jrsteensen/OpenHornet/files/11408381/OH5A5A1-200.-.ASSY.BLEED.AIR.KNOB.MECHANISM.v5.pdf)

**Comment by jrsteensen** [comment]
Add "OH5A5A1-200" in the title block on SH8.
Add view title to modification picture of "FN 7 MODIFICATION"

**Comment by Lazarus94** [comment]
Should I also add a section view of the fully assembled shaft or is it unnecessary?

**Comment by jrsteensen** [comment]
It could be helpful, I don't see any reason not to.

**Comment by Lazarus94** [comment]
Cool will do.

**Comment by jrsteensen** [comment]
Added to RC Release Package and Closed
