### ISSUE TITLE
OH4A6A1-1 FCS Panel - Gain Oride Switch - 3 pos instead of 2 pos

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#707]
### Summary:
The override switch is listed as 100SP3T8B13M1QEH, should be 2-position version 100SP1.

### Expected Results/How It Should Work:
The action in DCS and on DCS Bios shows a 2-position switch.

### Actual Results/How It Does Work:
The design calls for a 3-position switch, so there is an extra position compared to the legend plate's labels.

### Screenshots:
![image](https://user-images.githubusercontent.com/47125808/233819044-6de23a40-3fb8-4f4f-8259-84d13b18c09c.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A6A1-1 FCS Panel

**Comment by Lazarus94** [comment]
Fixed in LC v146
