### ISSUE TITLE
ECS, BLEED AIR MECHNAMISM - Incorrect nut size

### ISSUE THREAD

**Issue by Exprezz0** [jrsteensen/OpenHornet#709]
### Summary:
The size of the jam nut used on the pull shaft coupler for solenoid is incorrectly sized.  

### Expected Results/How It Should Work:
Hole size on pull shaft coupler is for 2-56 x 1.00in screw, which is the screw used and labeled in the model.  The current jam nut is 6-32.

### Screenshots:
![image](https://user-images.githubusercontent.com/81926396/234165735-9b94c3fd-bec8-4490-a67d-e16d3b05ab9a.png)
![image](https://user-images.githubusercontent.com/81926396/234165769-d2e2a207-7a02-426e-8225-831d67a4296c.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A5A1-200 - ASSY, BLEED AIR KNOB MECHANISM
OH5A5A1-1 - ASSY, ECS PANEL _(guilty by association)_

**Comment by jrsteensen** [comment]
@Lazarus94 Can you take care of this as part of the ECS Panel work.

**Comment by Exprezz0** [comment]
The drawing for the Bleed Air Knob Mechanism #705 is in-progress by @Lazarus94.  I'll update the model in Fusion and close this, but he'll need to update it when he does the drawing (which hasnt been started yet by the looks of it.)

**Comment by Lazarus94** [comment]
@Exprezz0 Cool thank you. Will update in the drawing.

**Comment by Exprezz0** [comment]
![image](https://user-images.githubusercontent.com/81926396/234168482-93471451-7ab1-40ba-a0f1-993ed078860e.png)
