### ISSUE TITLE
OH4A6A1: Rudder Trim Mechanism Needs Reduced Internal Friction.

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#714]
### Summary:
The 6389k231 flanged sleeve bearings add too much friction to the gear preventing the motorized pot from turning.

### Expected Results/How It Should Work:
The motor should be able to turn the pot without too much resistance.  

### Actual Results/How It Does Work:
When barely tightening the mechanism the flanges facing the gear clamp down on it preventing the motor from turning.  Perhaps replace with a sleeve that is not flanged or space out top and bottom so that the gear can be held in place in the middle with a gap.  The rod can ride on the lower metal 6338K561 bearing and does not need to be supported by the gear.

### Screenshots:
Here is the tightest it can go while still turning.

![image](https://user-images.githubusercontent.com/47125808/235403187-a092b628-9db2-497a-b4bb-0697abf12b77.png)

This shows that the top and bottom plastic bearing make a clamp for the gear when the parts are tightened.
![image](https://user-images.githubusercontent.com/47125808/235403307-d0deee3b-05d6-4c5e-bbaf-97fa3da63646.png)

A potential approach, replace the 6389k231 with a centering bushing, or shrink the top and bottom printed parts to not need a sleeve.  Then the gear can ride freely in the middle held in place by the set screw.
![image](https://user-images.githubusercontent.com/47125808/235403530-a3700bf0-8f43-41db-9f09-e3f63228a40e.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [x] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH4A6A1: Rudder Trim Mechanism

**Comment by jrsteensen** [comment]
@Arribe  I'm a little bit confused since the mechanism shows the top flanged bushing being recessed which leaves a small clearance gap for the gear, so it should not bind.

![Image](https://user-images.githubusercontent.com/2449496/236684342-369afad2-7e55-4b6f-aba4-b3a459b310ca.png)

**Comment by jrsteensen** [comment]
I'm not seeing that same recess on yours, though it could just be the angle or the slightly low resolution image.

**Comment by jrsteensen** [comment]
Previously resolved in the model when we flipped the gears.
