### ISSUE TITLE
Wing Fold Mechanism Handle Missing Retaining Screw 

### ISSUE THREAD

**Issue by Lazarus94** [jrsteensen/OpenHornet#716]
### Summary:
There is no screw to hold the Wing Fold handle onto the main shaft. 

### Expected Results/How It Should Work:
A screw should go through the modelled holes to hold the handle onto the shaft. The shaft also needs to be rotated in the CAD model.

### Screenshots:
![Screenshot (551)](https://user-images.githubusercontent.com/68113057/235950252-79b00358-0b01-4a2c-bf0c-228091016c91.png)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [X ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A2-1 - ASSY, WING FOLD HANDLE

**Comment by jrsteensen** [comment]
Verify it's not just a hidden body keeping it from being visible before adding the screw.

**Comment by jrsteensen** [comment]
Fixed in Wing Fold Handle v13
