### ISSUE TITLE
ECAD Directory Overhaul - Part 2

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#719]
Tactical Pause.  Directory overhaul is nearing completion with just a few things left to do:

- [x] ABSIS Transition to KiCad 7 
   - [x] Change path of Drawing Sheet for schematic and PCB
   - [x] Verify paths of symbols/footprints within schematic
   - [x] Final review of manufacturing files and assets
- [x] Backlight Panels - Type A - Transition to KiCad 7
   - [x] ANT SEL thru SIM POWER 
   - [x] SNSR PANEL & SPIN RCV PANEL Remaining!
- [ ] Functional PCBs Transition to KiCad 7 
   - [x] Change path of Drawing Sheet for schematic and PCB
   - [ ] Verify paths of symbols/footprints within schematic
   - [ ] Final review of manufacturing files and assets
- [x] Fix any outstanding issues
- [ ] Final Review of Directory:   Check directory and ensure there are no duplicate, excess, or corrupted files.
- [ ] Update and Review Manufacturing.md and ReadMe.md
   - [ ] Add instructions for alternate parts as needed
- [ ] MasterBOM! (Requires everything else to be complete)

**Comment by Exprezz0** [comment]
ABSIS Transition complete.  Could probably use one more review just to make sure everything has updated symbol properties.

**Comment by Exprezz0** [comment]
Backlight PCB Transition complete.  That's the bulk of the work.  Just need to go through the functional stuff and double check.  Then MasterBOM stuff!

**Comment by Exprezz0** [comment]
Need to decide what to do with the Left Circuit Breaker PCB.  Technically, it's not implemented in the assembly drawing, but was completed and exists to allow for use of backlighting the circuit breaker.  I put it in the release package and named it "OH4A8A1-XX - PCB, LEFT CIRCUIT BREAKER" pending feedback.

**Comment by jrsteensen** [comment]
Will be continuing this effort in next release.

**Comment by jrsteensen** [comment]
This issue is abandoned. Will continue to implement on an attrition basis as required. Will reopen if work is to be continued on it.
