### ISSUE TITLE
Create Drawing: OH5A2A6-1 - ASSY, BUNO PLACARD

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#721]
Create Drawing: OH5A2A6-1 - ASSY, BUNO PLACARD

**Comment by Lazarus94** [comment]
IN CHECK



[OH5A2A6-1 - ASSY, BUNO PLACARD v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11414114/OH5A2A6-1.-.ASSY.BUNO.PLACARD.v1.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
