### ISSUE TITLE
Create Drawing: OH5A2A7-1 - ASSY, LDG CHKLST PANEL

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#722]
Create Drawing: OH5A2A7-1 - ASSY, LDG CHKLST PANEL

**Comment by Lazarus94** [comment]
IN CHECK

[OH5A2A7-1 - ASSY, LDG CHKLST PANEL v1.pdf](https://github.com/jrsteensen/OpenHornet/files/11414145/OH5A2A7-1.-.ASSY.LDG.CHKLST.PANEL.v1.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.
