### ISSUE TITLE
Wrong mating connector for TM F/A-18 Stick Grip Specified in Stick Base

### ISSUE THREAD

**Issue by jkkicks** [jrsteensen/OpenHornet#725]
Mini Din 60J connector listed in Stick Assembly is the incorrect connector and should be updated to interface with thrustmaster f18 Stick

Should be replaced with:
Digikey: CP-2650-ND
OR
Digikey: CP-2750-ND

The former seems to be discontinued but is similar to the part originally used by thrustmaster in their base

Mouser also seems to offer a replacement that doesnt show to be end of life or discontinued:
Mouser: 490-MD-50SP

### Screenshots:
![image](https://github.com/jrsteensen/OpenHornet/assets/99859706/1728a7f6-47b7-4766-b58b-cd00915be6dd)

![IMG_5039](https://github.com/jrsteensen/OpenHornet/assets/99859706/ba81a8ab-add3-48ca-bd4b-7cf7a5a5820b)

### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ X ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [  ] Center Tub
- [ X ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*OHA3-40*

**Comment by jrsteensen** [comment]
- [ ] Evaluate MD-50SV connector: https://www.digikey.com/en/products/detail/cui-devices/MD-50SV
- [ ] Evaluate free hanging equivalents.

- MD-50SP is obsolete and not suitable for new design.

**Comment by jrsteensen** [comment]
Ordered a MD-50PL100 for evaluation and fit check: https://www.digikey.com/en/products/detail/cui-devices/MD-50PL100/500828

**Comment by jrsteensen** [comment]
Verified MD-500PL100 compatibility.

![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/532e8d30-7750-4aff-a65a-b7b5ee09082a)

Starting revision/integration of design.

**Comment by jrsteensen** [comment]
Verified MD-500PL100 compatibility.

![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/e403d742-2ab2-4667-9f09-1ce11a1daed3)

Starting revision/integration of design.

**Comment by jrsteensen** [comment]
Fixed in stick extension v14 and dwg v2
