### ISSUE TITLE
Interconnect Diagram for 5A10 ABSIS_ALE Relay Has Pin Conflict

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#732]
### Summary:
Diagram shows RC Hook circuit breaker connecting to pin 2, though pin 2 is listed as the output for the canopy mag switch.

### Expected Results/How It Should Work:
The RC Hook and the mag should use different pins.  Pin 4 is available for the RC Hook circuit breaker switch.

### Actual Results/How It Does Work:
RC Hook cannot be hooked up to the same pin as what is controlling the mag output.

### Screenshots:
![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/bfae766c-456f-4e3d-b318-3eefb5d80afc)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
Interconnect Diagram

**Comment by jrsteensen** [comment]
Will be completed in #389
