### ISSUE TITLE
Generate MFG Files: OH5A10A2-1 - ASSY, CANOPY SWITCH

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#799]
Generate the manufacturing files for Generate MFG Files: OH5A10A2-1 - ASSY, CANOPY SWITCH. 

__Check off each item in issue as you complete it.__

### File generation
- [OH Wiki HOWTO Link](https://github.com/jrsteensen/OpenHornet/wiki/HOWTO:-Generating-Fusion360-Manufacturing-Files)
- [ ] Generate SVG files (if required.)
- [x] Generate 3MF files (if required.)
- [ ] Generate STEP files (if required.)
- [x] Copy the relevant decal PDFs from the art folder to the relevant manufacturing folder (if required.)
### Review your files
- [x] Verify against drawing parts list that all the relevant manufacturing files have been created.
- [ ] Open each SVG in your browser and compare against part to ensure it appears the same and its filename is correct.
- [x] Open each 3MF in a slicer of your choice and verify geometry matches F360 model and its filename is correct.
- [ ] Open each STEP in a STEP file viewer of your choice and verify geometry matches F360 model and its filename is correct.
### Submit your files
- [x] Create a github PR against the beta 1 branch with the manufacturing files located in correct location of the release folder.
- [x] Request a review of the PR.

#### Why a PR?
It gives you credit when I generate the changelog in the release, and (more importantly) adds traceability to the history of the issues.

**Comment by Lazarus94** [comment]
IN PROGRESS
