### ISSUE TITLE
[Obsolescence]: OH5A2A4-1 - Radar Altimeter Discontinued Gear: 615242

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#825]
### Discord Username

Arribe

### Bug Summary

The Servocity gear 615242 is discontinued.  They recommended SKU:  2303-0250-0024 as a replacement, but that gear is too large for a simple drop in replacement.

### Expected Results

Need to identify a replacement gear.

### Actual Results

Cannot buy the spec'd gear, and their suggested replacement is too large.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/b62fe7f6-408d-4655-b434-105b48e6897b)

### Applicable Part Numbers

OH5A2A4-1

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.

**Comment by jrsteensen** [comment]
Technically, this should be an obsolescence report, not a bug report. 😄

**Comment by Arribe** [comment]
too many options...guess I went with the first item I saw on the list.  😁 Printing the gear in PETG is fine.

**Comment by jrsteensen** [comment]
Replaced with printed gears and added a #8-32 X .125 set screw in RALT v17
