### ISSUE TITLE
[Bug]: UIP parts with same part number: OH1A1-28

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#845]
### Discord Username

Arribe

### Bug Summary

On the UIP part number OH1A1-28 is used for both the UPPER UIP FACE MOUNT, RIGHT, and UIP RIGHT GLARESHIELD.

### Expected Results

Parts should have their own part numbers.  If possible please keep UPPER UIP FACE MOUNT, RIGHT associated with OH1A1-28 as that was used to generate the 3mf file.

### Actual Results

Same part number used for 2 different parts.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/e0ca7d2f-8643-4da9-b776-ccd25800c271)

### Applicable Part Numbers

OH1A1-28

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

### Miscellaneous Info

Discovered during manufacturing file generation when comparing the release drawing to the list of exported files.

**Comment by jrsteensen** [comment]
- [ ] Change PN to -29

**Comment by jrsteensen** [comment]
Closed with UIP v106
