### ISSUE TITLE
[Bug]: OH4A10-10 TRANSDUCER GAIN REMOTE PLATE - listed as ACRL should be RMRK

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#859]
### Discord Username

Arribe

### Bug Summary

OH4A10-10 TRANSDUCER GAIN REMOTE PLATE - listed as ACRL should be RMRK on drawing

### Expected Results

Should be RMRK for engraving the lettering.

### Actual Results

Part is listed as acrylic.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/b6926d68-9df7-4303-9ce2-944462c52592)

### Applicable Part Numbers

OH4A10-10

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Left Console (LCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
- [ ] Change to RWMK
- [ ] Generate new drawing and commit PDF to release folder.

**Comment by jrsteensen** [comment]
Fixed in v7
