### ISSUE TITLE
[Bug]: Master Arm Panel - All WS2812B-2020's misrouted 

### ISSUE THREAD

**Issue by Exprezz0** [jrsteensen/OpenHornet#897]
### Discord Username

Exprezzo#3604

### Bug Summary

The traces routed to the WS2812B-2020's that are being used to backlight the Ready, A/A, & A/G switches are misrouted.

https://www.mouser.com/pdfDocs/WS2812B-2020_V10_EN_181106150240761.pdf
![image](https://github.com/jrsteensen/OpenHornet/assets/81926396/9a0e7b0f-95d9-4b1e-8852-62732d5f3d09)

Data is going into Pin 1 and out of Pin 3 throughout the circuit.  Pin's 1 & 3 should be flipped based on the datasheet.

### Expected Results

See Screenshots.

### Actual Results

See Screenshots.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/81926396/b1ec915e-c000-442e-aa26-bb7b260051af)
![image](https://github.com/jrsteensen/OpenHornet/assets/81926396/8a32ae10-1b90-444c-b299-359c99af7278)

### Applicable Part Numbers

PCB, Master Arm Panel

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [ ] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by Exprezz0** [comment]
We're misrouted; looks like the footprints might have gotten flipped 180 degrees.  Rotated all of the LEDs and committing with the K7 transition

**Comment by kbastronomics** [comment]
Interesting since the board works.  
Check https://discord.com/channels/392833351238811648/1078093128675885207/1078093128675885207 for a video of his powering it up and I did do a check as well.   

is it possible it's a footprint labeling issue?

**Comment by Exprezz0** [comment]
A minute late and a dollar short ;)

Already fixed and closed.
