### ISSUE TITLE
[Bug]: OH2A3A1 AMPCD legend plates listed as ACRYL vs RMRK OH2A3A1-22 thru -28

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#908]
### Discord Username

Arribe

### Bug Summary

Material listed as Acrylic vs Rowmark. for OH2A3A1-22 thru -28

### Expected Results

design appears to be for Romark

### Actual Results

material listed as acrylic.

### Applicable Part Numbers

OH2A3A1-22 thru -28

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with AMPCD v17
