### ISSUE TITLE
[Bug]: OH1A2-206 is a duplicate part to OH1A2-205, and named with (1) tiebreaker.

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#911]
### Discord Username

Arribe

### Bug Summary

The master arm panel square button has 2 diffuser parts that are just copies of eachother. The design could be updated to make -206 be another instance of the -205 part.

### Expected Results

1 diffusers with 2 instances 

### Actual Results

each diffuser is a separate part with part number, but names are the same except for (1)

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/e28a20dc-fdb3-4817-9516-81d0005c121c)

### Applicable Part Numbers

OH1A2-206

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v17
