### ISSUE TITLE
[Bug]: OH1A4-1 - ASSY, EYEBROW WARNING MODULE, LEFT legends not extracting properly

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#913]
### Discord Username

Arribe

### Bug Summary

Attempted to extract the legend plates for hte left eyebrow.  None of the letters are coming out.  I did attempt to extrude them thicker for shaper to differentiate the letters.  But that had mixed results and caused the letters to appear thinner than the design.  Also the internal portion of closed letters (ex: A, O, R, etc) do not export cleanly.

### Expected Results

Legend plates extract in shaper with lettering.

### Actual Results

shaper doesn't extract the letters it's just a blank, all black image.

### Applicable Part Numbers

OH1A4-1

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v6. Unblocks #736
