### ISSUE TITLE
[Bug]: OH1A5-1 - ASSY, EYEBROW WARNING MODULE, RIGHT legend plates do not extract

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#915]
### Discord Username

Arribe

### Bug Summary

Spot checked multiple legend plates on the right eyebrow, and they have the same issue as #913.

### Expected Results

Legend plates should extract with lettering.

### Actual Results

Plates are blank or have other issues.  Only spot checked 5 to verify the same issues as the left eyebrow.

### Applicable Part Numbers

OH1A5-1

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed. Unblocks MFG file generation.
