### ISSUE TITLE
[Bug]: OH2A4A1-11_RWR CONTROL PANEL LEGEND PLATE lettering too shallow to export

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#919]
### Discord Username

Arribe

### Bug Summary

The lettering is too shallow in the base design to export via shaper.  I increased the extrusion by .03 to export lettering to svg.

### Expected Results

legend plate is exportable via shaper.

### Actual Results

the plate comes out blank.

### Applicable Part Numbers

OH2A4A1-11

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v16.
