### ISSUE TITLE
[Bug]: OH2A5A1-100 Drawing not exploded on Sheet 2 of OH2A5A1-1 ASSY, PANEL, ECM/DISP 

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#922]
### Discord Username

Arribe

### Bug Summary

The ECM JETT SEL INDICATOR is a little different than other square buttons in the pit with OH2A5A1-106 .55 SQ LEGENDPLATE INSERT.  May be helpful to have an exploded view to show the assembly of the parts.

### Expected Results

Builders may question how the parts are expected to go together beyond what they can see on the outside.  With challenges from people installing and working with F360 having the drawing show the assembly may be helpful.

### Actual Results

The drawaing lists all the parts, but only shows the final assembly of the push button.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/5c0d9c2f-6532-4240-9786-b786d489408f)

### Applicable Part Numbers

OH2A5A1-100

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
This is a standard OH-SPEC-001 indicator type B, method 1 construction. No exploded view required.
