### ISSUE TITLE
[Bug]: OH2A6A1-13 CABIN PRESS DIAL FACE listed as ACRL vs RMRK

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#929]
### Discord Username

Arribe

### Bug Summary

dial face listed as acrylic, should be rowmark.

### Expected Results

RMRK

### Actual Results

ACRL

### Applicable Part Numbers

OH2A6A1-13

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v13
