### ISSUE TITLE
[Bug]: OH2A7A1-200 - ALTIMETER material info missing for -201 to -207

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#932]
### Discord Username

Arribe

### Bug Summary

Material listed as N/A vs suggested design material.

### Expected Results

-201 PETG
-204 RMRK
-205 PETG
-206 ACRL
-207 RESN

### Actual Results

All listed as N/A

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/2b0618a4-6d40-4f9f-a8ee-39e31de5e167)

### Applicable Part Numbers

OH2A7A1-200

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
1. Model and Drawing Updated
2. No MFG file changes

Closed in 8cd353102b6074e2e53a3bb296bb7a1ba6f6b671
