### ISSUE TITLE
[Bug]: OH2A7A1-300 VERTICAL VELOCITY INDICATOR material missing for 301, 304, and 302 missing on drawing part list

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#935]
### Discord Username

Arribe

### Bug Summary

Parts need material listed versus N/A.

Part -302 not on drawing list, but -301 is listed twice.

### Expected Results

-301 PETG
-302 PETG
-304 RMRK

### Actual Results

302 is missing from parts list, and the materials are listed as N/A.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/db9e3e01-1e7f-4429-8eb1-73ba56fc4c90)

### Applicable Part Numbers

OH2A7A1-300

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v10
