### ISSUE TITLE
[Bug]: OH2A7A1-400 RWR material updates for -401, 402, and -405

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#938]
### Discord Username

Arribe

### Bug Summary

material listed as N/A

### Expected Results

-401 PETG
-402 RESN
-405 RMRK

### Actual Results

Listed as N/A

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/cdc50a2f-3d23-4df8-92f8-9ed61af743a5)

### Applicable Part Numbers

OH2A7A1-400

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v12
