### ISSUE TITLE
[Bug]: OH3A3-205 ASSY, GUIDE ROD material listed as STL should be blank

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#943]
### Discord Username

Arribe

### Bug Summary

Material for this assembly is listed as steel.  It's an assembly made up mostly of an aluminum rod.

### Expected Results

material should be blank.

### Actual Results

listed as STL.

### Applicable Part Numbers

OH3A3-205

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Flight Stick

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Fixed in v20
