### ISSUE TITLE
[Bug]: OH1A4-1 - ASSY, EYEBROW WARNING MODULE, LEFT duplicate diffuser parts, and material update

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#947]
### Discord Username

Arribe

### Bug Summary

OH1A5-18 appears to be the same part as these copies for just the left module: OH1A4-24 EYEBROW WARNING SMALL LEGEND DIFFUSER (1) and OH1A4-25 EYEBROW WARNING SMALL LEGEND DIFFUSER (2).  Could streamline by removing the duplicates and setting it as another instance of OH1A5-18

OH1A4-26 EYEBROW WARNING LARGE LEGEND, MASTER CAUTION listed as RMRK.  But all the other legends are listed as ACRL.

### Expected Results

If -24 and -25 are the same as OH1A5-18 then just use another instance of -18.

legend part material consistency

### Actual Results

extra part numbers

one legend out of the entire module listed as RMRK vs ACRL.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/47125808/009fea5d-0076-46fd-beab-92ec152bfcc7)

### Applicable Part Numbers

OH1A4-1

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
- [ ] Change one RWMK diffuser to acrylic.

DIffusers should stay different part numbers because they are different colors.

**Comment by jrsteensen** [comment]
1. -26 changed to ACRL in model
2. Updated Drawing
3. -26 MFG Filename was correct

Closed in 1a25e7c91e18bed964c930845b6a67ddff20a545
