### ISSUE TITLE
[Bug]: Right Console ELEC Panel BATT VOLT BEZEL FACE generated as *.3mf s/b *.svg

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#953]
### Discord Username

smgvbest (aka Sandra)

### Bug Summary

In the Beta1 Manufacturing files for the ELEC panel the Battery Volt Dial face was generated as a 3mf part indicating it's 3d printed.   this part is an engraved part so should be a svg file

### Expected Results

for Engraved Parts SVG files are specified this was not done unfortunately so could not send file to engraving software.

### Actual Results

unable to send 3mf file to laser for engraving

### Applicable Part Numbers

OH5A4A1-104 - BATT VOLT BEZEL FACE

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

### Miscellaneous Info

Just needs the SVG generated and 3mf file removed

**Comment by jrsteensen** [comment]
Closed in 8a4539966eaa26d9a074939dde20515e09df1a46
