### ISSUE TITLE
[Bug]: Mag Switch material specifies ALU as material for the bracket, it should be steel.

### ISSUE THREAD

**Issue by icemarkom** [jrsteensen/OpenHornet#956]
### Discord Username

icemarkom

### Bug Summary

In https://github.com/jrsteensen/OpenHornet/blob/v1.0.0-beta1/release/OHC_Common_Parts/OHC0005%20-%20ASSY%2C%20MAG%20HELD%20SWITCH/OHC0005%20-%20ASSY%2C%20MAG%20HELD%20SWITCH_-_v6.pdf, the material specified for the bracket is aliminium. Per Discord discussion, the bend is optimized for steel.

### Expected Results

Correct material should be specified; or the correct bend should be modeled.

### Actual Results

N/A

### Applicable Part Numbers

OHC0005-10

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Left Console (LCON), Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with 6a6c8a0d09b7265dad9bd6fa1cd7d170fe562ba2
