### ISSUE TITLE
interconnect: Wing Fold microswitches probably wrong name

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#973]
### Summary:
interconnect draft 20221201:
The microswitches for the Wing Fold are named
- Wing Fold Unlock
- WNG Fold Hold
- WNG Fld Spread

Instead of "Hold" (the middle position of the handle), it should be named "Fold", so both rotation microswitches are used.

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [X] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by Arribe** [comment]
<img width="1152" alt="wing fold interconnect" src="https://github.com/jrsteensen/OpenHornet/assets/47125808/567bdc98-a43c-4f26-bf01-beef6eca3237">

**Comment by jrsteensen** [comment]
Fixed in 7182c503bad53378d8f6cd591725b93fc0b9cb15
