### ISSUE TITLE
interconnect: Ant_Gnd connected to D39, not GND

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#974]
### Summary:
The ANT_GND of the ANT SEL PANEL should be shown connected to GND_J5-17. Instead, it is connected to D39.

### Screenshots:
<img width="528" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/654be750-73eb-4515-bb38-1f3f4f8e66af">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by jrsteensen** [comment]
Already fixed on latest interconnect. No action taken.
