### ISSUE TITLE
interconnect: Brk Press Gauge LED falsely stating resistor for DIN

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#976]
### Summary:
The DIN of the Brake Pressure Gauge shows a resistor of 470 Ohms, while there shouldn't be any resistors.

### Screenshots:
<img width="542" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/9d26f00d-3648-4478-8043-e2d31b735745">

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [X] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by jrsteensen** [comment]
Fixed in 29a55098f0a2560070b0ed115b2a45cc64700cf9.

To be uploaded once all interconnect issues are resolved.
