### ISSUE TITLE
[Obsolescence]: Startech USB32HD4 updated, size changed

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#977]
### Discord Username

Higgins

### Bug Summary

The USB32HD4 is no longer available in the size/shape from the original design. The new length is now 4 inches.
See data sheet: https://media.startech.com/cms/pdfs/usb32hd4_datasheet.pdf

### Expected Results

The bracket needs to be a bit longer for the adapter to fit.

### Actual Results

The bracket is too short.

### Screenshots/Images/Files

<img width="261" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/860dd8a0-22bb-412d-b138-4cead1e1e605">

### Applicable Part Numbers

OH2A1-29

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
- [ ] Update Model
- [ ] Evaluate placement in LIP
- [ ] Update LIP
- [ ] Update Manufacturing File for Bracket

**Comment by jrsteensen** [comment]
Closed with b39025a273f53cfa161401ad7a174843c32aa3e3
