### ISSUE TITLE
OH2A1A1-43 - LOWER RIGHT LIP AUX SUPPORT BRACKET - Material in PDF listed as MDF, should be PETG

### ISSUE THREAD

**Issue by 5k33tz** [jrsteensen/OpenHornet#981]
### Summary:
In PDF "OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE_-_v6.pdf" under v1.0.0-beta1, the material for PN 34 "LOWER RIGHT LIP AUX SUPPORT BRACKET" is listed as MDF, but part material should be PETG.

### Expected Results/How It Should Work:
(Explain how you think it should work here. Be very specific.)

### Actual Results/How It Does Work:
(Explain how it actually works here. Be very specific.)

### Screenshots:
![image](https://github.com/jrsteensen/OpenHornet/assets/13365308/831c69f8-2caa-45ad-8568-cc7c3650b8b7)

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [ ] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [X] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [X] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
- [ ] Update material of OH2A1A1-43 to PETG
- [ ] Update OH2A1A1-1 (LIP Structure) drawing.

**Comment by jrsteensen** [comment]
Closed in a89bd74b070fb418a1f26b972df3f3a034d4d53c
