### ISSUE TITLE
[Bug]: RAlt Controller PCB: BL Silkscreen missing

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#985]
### Discord Username

Higgins

### Bug Summary

On the RAlt Controller PCB the labels "in" and "out" are missing.

### Expected Results

It would be better to see which connector is for "in" and which is for "out".

### Actual Results

The BL silkscreen labels are missing.

### Screenshots/Images/Files

<img width="406" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/a3482283-238d-40c1-ab7d-120232f93a87">

### Applicable Part Numbers

CONTROLLER_Radar Altimeter

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

### Miscellaneous Info

There's no version number on the PCB. That would be helpful, too.

**Comment by jrsteensen** [comment]
- Low priority beta1 update, may be bumped to beta 2.

- [ ] Update PCB layout & Gerbers.

**Comment by jrsteensen** [comment]
Closed with f9735d513a1dfb10959a278252fd3cc90c631ef7
