### ISSUE TITLE
[Bug]: Interconnect: Defog Panel missing in the BL interconnect (v4)

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#988]
### Discord Username

Higgins

### Bug Summary

The Defog Panel is missing in the BL interconnect.

### Expected Results

It needs to be included.

### Actual Results

It's missing.

### Screenshots/Images/Files

<img width="991" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/6e5924e9-154a-484a-9602-0a49eeff6438">

### Applicable Part Numbers

OH5A5A2-13

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Right Console (RCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
- [ ] Its missing. It should be added to the interconnect.

**Comment by jrsteensen** [comment]
Completed.
