### ISSUE TITLE
[Bug]: interconnect v5: FCS_5V is unused, but shown as connected

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#990]
### Discord Username

Higgins

### Bug Summary

Interconnect (v5) shows both 5V pins connected, but only 5V_2 is used.

### Expected Results

One of the 5V pins should be x-ed out.

### Actual Results

There is nothing connected to FCS_5V, only to FCS_5V_2.

### Screenshots/Images/Files

<img width="400" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/7405ecf2-7864-4436-b6cc-81c6620016ab">

### Applicable Part Numbers

interconnect v5

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Left Console (LCON)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Updated in interconnect and closed.
