### ISSUE TITLE
[bug]: Power circuits need diodes for power backfeeding prevention

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#991]
- 5V/12V acc 
- if possible on ALEs

### Category:
*Check one or more items.*
- [ ] MCAD (SolidWorks)
- [x] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [x] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software

**Comment by jrsteensen** [comment]
- [ ] Add Shottkey Diodes as reverse polarity protection to all circuits on Power Distro PCB
- [ ] Add Shottkey diode as reverse polarity protection to all power lines on ALE

**Comment by Higgins-OH** [comment]
Some kind of zener diode (or whatever prevents the connection of 5V and 12V through the ProMicros) on the 12V circuit of future ALEs wouldn't be bad, too. This way the 12V devices won't draw current through the ProMicro from the 5V circuit. In case 12V isn't provided, only 5V through USB, that could prevent overloading the system.

**Comment by jrsteensen** [comment]
ALE Updates closed with 3de2140d16f4f755b07b172f658727227580eda7
