### ISSUE TITLE
[FEATURE REQUEST]: PCIe USB card for PC for better connection quality

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#992]
### Summary:
Motherboard USB seems to be too unreliable for the pit's USB. A decent PCIe USB 3 card is recommended for enhancement.

### Type:
*Check one item.*
- [ ] Bug
- [x] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [x] General, Misc.

**Comment by jrsteensen** [comment]
Added note 6 to interconnect:

![Image](https://github.com/jrsteensen/OpenHornet/assets/2449496/c7c2868f-5766-494b-ae4c-6a6cdce79ab1)
