### ISSUE TITLE
[Bug]: interconnect v5 DDIs: BRT/CONT pins swapped in comparison to PCB silkscreen

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#993]
### Discord Username

Higgins

### Bug Summary

On the interconnect, D8/D10 are connected to BRT and D4/D7 are connected to CONT.
On the controller PCBs it's the other way round.

### Expected Results

Same pins on interconnect as on PCBs.

### Actual Results

Wrong rot. encoder names on the interconnect.

### Screenshots/Images/Files

<img width="545" alt="image" src="https://github.com/jrsteensen/OpenHornet/assets/62520296/149ed1c6-cddf-480c-9161-e3764c5e0204">

### Applicable Part Numbers

1A3A1W3P5 et al.

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed with 22bd2215bd6aceef0d8ed82d297d2bb7942c276c
