### ISSUE TITLE
Interconnect V5 stand by instrument Coil connection for VVI and Airspeed incorrect 

### ISSUE THREAD

**Issue by Krikeee** [jrsteensen/OpenHornet#994]
### Discord Username

Krikeee

### Bug Summary

Interconnect v5 lists the Analog instrument PCB Stepper COIL J3-4 connection twice. Additionally, COIL2 and COIL4 are incorrectly attached to J3-2 and J3-4 respectively.

This issue can be seen on the interconnect diagram for the standby Airspeed and VVI gauges (page3)

### Expected Results

Stepper coils should be attached as follows: Coil1 J3-1, Coil2 J3-3, Coil3 J3-4, Coil4 J3-2

J3-4 should not be listed twice.

### Actual Results

It has resulted in Incorrect labeling of the interconnect diagram for the components listed.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/91638076/5ccb4dff-eede-4b05-970a-ebc5e699253e)

### Applicable Part Numbers

2A7A1A3, 2A7A1A5

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Completed as described with interconnect v8.
Closed with 6af8514584e2d954b94658c6033680b5651ae35a
