### ISSUE TITLE
[FEATURE REQUEST]: DDI/AMPCD controllers could need better self-built insulation from displays

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#997]
### Discord Username

Higgins

### Feature/Enhancement Summary

Even with thick adhesive tape under the controller boards there is still a latent risk some pins will stick through and cause short circuits. With a bit rough fiddling (connecting/disconnecting) while the pit is 'hot' the risk is definitely there.

### Justification

A pre-designed housing, holding bracket or clearly worded hint for the reckless or unaware builder would be a big help.

### Applicable Part Numbers

OHC0015-10 PCB, DDI_AMPCD_CONTROLLER

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Top Level Assembly (TLA)

**Comment by jrsteensen** [comment]
Added note to UIP drawing to mount as to avoid shorts on display. 
Closed with 634c5f892d1ca1904b4fe2a0cacf66fbe2f81cfa
