### ISSUE TITLE
[Bug]: OH1A8A1-100 - UFC PANEL_-_v3 and v4 in release folder

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet#998]
### Discord Username

Arribe

### Bug Summary

Versions 3 and 4 of the OH1A8A1-100 - UFC PANEL drawing present in the ..\release\OH1_Upper_Instrument_Panel\OH1A8 - ASSY, UPFRONT CONTROL PANEL folder.

### Expected Results

Only a single copy of the latest version present.

### Actual Results

Both drawing files present in folder.
OH1A8A1-100 - UFC PANEL_-_v3.pdf
OH1A8A1-100 - UFC PANEL_-_v4.pdf

### Screenshots/Images/Files

<img width="642" alt="UFC Drawings" src="https://github.com/jrsteensen/OpenHornet/assets/47125808/7cf2cebc-9db5-48ca-b833-9bb8e1234363">

### Applicable Part Numbers

OH1A8A1-100 - UFC PANEL Drawing

### Release Version

1.0.0-beta.1

### Category

Mechanical (Structure/Panels/Mechanisms)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by jrsteensen** [comment]
Closed in 24af6623856f5c8e89981fd38a3ca84d67ce6f44
